<span style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">An Exception was encountered at '<a href="#papermill-error-cell">In [7]</a>'.</span>

In [1]:
import oceanbench

oceanbench.__version__

'0.0.2'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
import xarray as xr
from datetime import datetime

# 1. on ouvre le sample
ds = xr.open_mfdataset(
    ["https://minio.dive.edito.eu/project-oceanbench/public/XIHE/20240103.zarr"],
    engine="zarr",
    preprocess=lambda d: d.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
)

# 2. on remplace la dimension 'first_day_datetime' par une vraie coordonnée dimensionnelle
ds = ds.assign_coords(first_day_datetime=("first_day_datetime", [datetime(2024, 1, 3)]))

challenger_dataset = ds
print(challenger_dataset)

<xarray.Dataset> Size: 33GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 23,
                         latitude: 2041, longitude: 4320)
Coordinates:
  * depth               (depth) float64 184B 0.494 2.646 5.078 ... 541.1 643.6
  * latitude            (latitude) float32 8kB -80.0 -79.92 ... 89.92 90.0
  * longitude           (longitude) float32 17kB -180.0 -179.9 ... 179.8 179.9
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[ns] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 353MB dask.array<chunksize=(1, 1, 75, 4320), meta=np.ndarray>

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [3]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Surface height,0.077526,0.080072,0.080199,0.080466,0.081674,0.086342,0.084408,0.086351,0.088344,0.088599
Surface temperature,0.750129,0.704030,0.712400,0.754620,0.734946,0.764045,0.738816,0.792204,0.839555,0.831889
Surface salinity,0.724029,0.726620,0.752761,0.747579,0.738520,0.716550,0.707049,0.713106,0.717489,0.697855
Surface northward velocity,0.122258,0.120584,0.120452,0.119975,0.120690,0.120648,0.119357,0.121389,0.120524,0.121266
Surface eastward velocity,0.124803,0.121870,0.121857,0.122193,0.122388,0.123161,0.121867,0.127186,0.128346,0.129918
50m temperature,0.814790,0.781921,0.786976,0.822700,0.819797,0.859901,0.816549,0.862546,0.864641,0.917479
50m salinity,0.389702,0.402725,0.405492,0.403583,0.409325,0.408934,0.395516,0.399368,0.403862,0.425925
50m northward velocity,0.113475,0.110615,0.109836,0.107998,0.108145,0.108293,0.107333,0.107847,0.106804,0.105928
50m eastward velocity,0.114221,0.111020,0.110149,0.109311,0.109308,0.108710,0.107686,0.109260,0.108920,0.108088
200m temperature,0.795006,0.766525,0.782082,0.753980,0.775306,0.768295,0.776432,0.794555,0.779413,0.786228
200m salinity,0.139200,0.140472,0.141203,0.137877,0.138772,0.138474,0.136469,0.137141,0.135836,0.137728
200m northward velocity,0.108221,0.112039,0.109499,0.105461,0.106077,0.105693,0.105331,0.105460,0.103863,0.102867
200m eastward velocity,0.112338,0.115639,0.113555,0.109897,0.111160,0.110652,0.109550,0.110121,0.108799,0.107867
550m temperature,0.511531,0.492621,0.500548,0.484324,0.505068,0.500736,0.496052,0.508549,0.504345,0.500196
550m salinity,0.079122,0.081392,0.080075,0.079249,0.078534,0.079949,0.077258,0.078783,0.077413,0.079033
550m northward velocity,0.095019,0.098985,0.096986,0.093077,0.093534,0.093269,0.092720,0.092153,0.091023,0.089954
550m eastward velocity,0.098367,0.102051,0.100436,0.096787,0.097834,0.097131,0.096388,0.096072,0.095016,0.093961

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth,112.549205,109.982773,111.724014,114.579665,109.869231,112.625966,116.748203,119.97393,120.657651,112.071709

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Northward geostrophic velocity,0.701412,0.699894,0.721076,0.802359,0.791146,0.955004,0.835658,0.807204,0.760776,0.807311
Eastward geostrophic velocity,0.622205,0.639501,0.621422,0.605789,0.605955,0.622894,0.545927,0.582386,0.601647,0.610311

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Surface Lagrangian trajectory deviation (km),14.228609,27.162497,38.904037,49.755318,60.086796,69.893372,79.093712,88.034157

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

<span id="papermill-error-cell" style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">Execution using papermill encountered an exception here and stopped:</span>

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(challenger_dataset)

NameError: name 'DepthLevel' is not defined

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [ ]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(challenger_dataset)

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLOR12 analysis

In [ ]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(challenger_dataset)

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [ ]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(challenger_dataset)