In [1]:
import oceanbench

oceanbench.__version__

'0.1.4'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
from datetime import datetime

import xarray
from oceanbench.core.challenger_datasets import _open_multizarr_forecasts_as_challenger_dataset


def _glonet2_correct_stats_dataset_path(start_datetime: datetime) -> str:
    start_datetime_string = start_datetime.strftime("%Y%m%d")
    return (
        "https://s3.waw3-1.cloudferro.com/oceanbench-bucket/"
        f"dev/ml-forecast-outputs-glonet2-correct-stats/glonet2/{start_datetime_string}.zarr"
    )


challenger_dataset: xarray.Dataset = _open_multizarr_forecasts_as_challenger_dataset(
    _glonet2_correct_stats_dataset_path
)
challenger_dataset

<xarray.Dataset> Size: 163GB
Dimensions:             (first_day_datetime: 52, lead_day_index: 10, depth: 20,
                         latitude: 672, longitude: 1440)
Coordinates:
  * depth               (depth) float32 80B 0.49 2.65 5.08 ... 541.1 643.6 763.3
  * latitude            (latitude) float32 3kB -78.0 -77.75 -77.5 ... 89.5 89.75
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * longitude           (longitude) float32 6kB -180.0 -179.8 ... 179.5 179.8
  * first_day_datetime  (first_day_datetime) datetime64[us] 416B 2024-01-03 ....
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 40GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 40GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 40GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 40GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 2GB dask.array<chunksize=(1, 1, 256, 512), meta=np.ndarray>
Attributes:
    Conventions:                CF-1.8
    challenger:                 glonet2
    forecast_reference_time:    2024-01-03
    ice_mask_min_abs_latitude:  30.0
    oceanbench_source_kind:     challenger
    oceanbench_source_name:     glonet2_correct_stats

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.075844,0.076782,0.082646,0.083316,0.090502,0.091712,0.098420,0.100411,0.106246,0.107902
Temperature (°C) [sea_water_potential_temperature]{surface},0.707694,0.688027,0.827336,0.810215,0.922563,0.919838,1.027823,1.040042,1.144051,1.166040
Salinity (PSU) [sea_water_salinity]{surface},0.702234,0.715186,0.674712,0.685839,0.675512,0.684677,0.688471,0.695579,0.705548,0.711841
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.122121,0.124756,0.126004,0.128719,0.131327,0.134752,0.138277,0.142168,0.145334,0.148753
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.123678,0.127533,0.129607,0.133034,0.136125,0.139727,0.143748,0.147824,0.150929,0.154175
Temperature (°C) [sea_water_potential_temperature]{50m},0.940068,0.923656,1.022227,1.003165,1.102273,1.095086,1.196367,1.199909,1.299378,1.308583
Salinity (PSU) [sea_water_salinity]{50m},0.319030,0.320899,0.327872,0.329842,0.344953,0.347456,0.364090,0.367184,0.384069,0.388102
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.112565,0.113168,0.114117,0.116166,0.118636,0.121637,0.125082,0.128655,0.131547,0.134393
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.114007,0.114480,0.115506,0.117561,0.119926,0.122777,0.125959,0.129378,0.132202,0.135063
Temperature (°C) [sea_water_potential_temperature]{100m},1.059993,1.049756,1.129687,1.118141,1.222798,1.218415,1.323423,1.324631,1.421820,1.424513
Salinity (PSU) [sea_water_salinity]{100m},0.234472,0.234474,0.253651,0.253873,0.277685,0.278551,0.300283,0.301128,0.320627,0.321539
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.110135,0.110032,0.110680,0.112102,0.114162,0.116554,0.119427,0.122374,0.124833,0.127157
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.113534,0.113202,0.113410,0.114829,0.116697,0.118986,0.121668,0.124735,0.127318,0.129855
Temperature (°C) [sea_water_potential_temperature]{200m},0.889256,0.883801,1.011312,1.014784,1.148040,1.162174,1.277453,1.296302,1.395493,1.415931
Salinity (PSU) [sea_water_salinity]{200m},0.163476,0.162884,0.179897,0.179408,0.195434,0.195576,0.210128,0.210834,0.224346,0.225575
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.106801,0.105961,0.105426,0.105801,0.106510,0.107715,0.109276,0.111066,0.112572,0.114057
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.111682,0.110677,0.109999,0.110124,0.110683,0.111672,0.113072,0.114701,0.116222,0.117637
Temperature (°C) [sea_water_potential_temperature]{300m},0.733364,0.730150,0.789843,0.789838,0.850166,0.853717,0.907940,0.914963,0.964571,0.972626
Salinity (PSU) [sea_water_salinity]{300m},0.125148,0.124926,0.137570,0.137763,0.152357,0.153470,0.166883,0.168135,0.180268,0.181653
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.104151,0.103123,0.102264,0.102289,0.102645,0.103464,0.104581,0.105899,0.106982,0.108090
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.107909,0.106740,0.105845,0.105772,0.106006,0.106713,0.107720,0.108964,0.110106,0.111198
Temperature (°C) [sea_water_potential_temperature]{500m},0.547544,0.547023,0.557686,0.560853,0.610808,0.621959,0.677249,0.690820,0.744124,0.756770
Salinity (PSU) [sea_water_salinity]{500m},0.089493,0.089353,0.096327,0.097403,0.109502,0.112115,0.123605,0.126220,0.136820,0.139378
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.095570,0.094433,0.093588,0.093296,0.093386,0.093701,0.094350,0.095065,0.095727,0.096314
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.098931,0.097643,0.096676,0.096291,0.096310,0.096622,0.097228,0.097961,0.098696,0.099411

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},80.183342,80.587997,82.814713,82.857071,85.038872,85.18148,86.574745,86.886566,87.756874,88.072258

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.419449,0.408308,0.412935,0.405971,0.426168,0.429616,0.450582,0.458584,0.478179,0.486374
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.334919,0.318293,0.282350,0.279035,0.280663,0.285766,0.295732,0.303613,0.318753,0.330068

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [7]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},9.999679,19.158875,27.721994,35.998814,44.118416,52.151287,60.114319,67.997627

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [8]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.048995,0.049932,0.059735,0.061327,0.070686,0.073088,0.081992,0.085218,0.092389,0.094988
Temperature (°C) [sea_water_potential_temperature]{surface},0.537222,0.509596,0.706211,0.686998,0.828725,0.827256,0.952678,0.967054,1.081610,1.103796
Salinity (PSU) [sea_water_salinity]{surface},0.337689,0.329413,0.477710,0.469676,0.567992,0.567217,0.640430,0.646194,0.705293,0.713187
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.055728,0.071256,0.080143,0.089853,0.099176,0.108581,0.117927,0.126623,0.133239,0.139417
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.057652,0.075362,0.085507,0.096293,0.105848,0.115381,0.124854,0.133705,0.140150,0.146206
Temperature (°C) [sea_water_potential_temperature]{50m},0.636304,0.613070,0.789017,0.771457,0.913589,0.912916,1.042130,1.051829,1.165929,1.177265
Salinity (PSU) [sea_water_salinity]{50m},0.237481,0.233821,0.312248,0.310515,0.359986,0.360419,0.397691,0.399875,0.430399,0.433529
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.039611,0.050531,0.060114,0.069786,0.079701,0.089724,0.099647,0.108822,0.115644,0.121879
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.040593,0.052344,0.063005,0.073218,0.083074,0.092967,0.102718,0.111725,0.118565,0.124733
Temperature (°C) [sea_water_potential_temperature]{100m},0.641044,0.626466,0.834149,0.829004,1.008981,1.012468,1.161147,1.168610,1.289756,1.292929
Salinity (PSU) [sea_water_salinity]{100m},0.182274,0.179801,0.237412,0.236242,0.277698,0.277845,0.309117,0.309585,0.334823,0.335243
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.037378,0.047140,0.056932,0.066002,0.075538,0.084902,0.094214,0.102703,0.109063,0.114687
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.036957,0.047290,0.057448,0.066937,0.076505,0.085839,0.095012,0.103626,0.110297,0.116155
Temperature (°C) [sea_water_potential_temperature]{200m},0.487777,0.479914,0.688931,0.693809,0.875169,0.893295,1.043187,1.066242,1.188983,1.210504
Salinity (PSU) [sea_water_salinity]{200m},0.105485,0.104518,0.136667,0.135973,0.160809,0.161048,0.181601,0.182532,0.200128,0.201249
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.030774,0.038567,0.047695,0.055928,0.064662,0.073088,0.081502,0.089121,0.094999,0.100106
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.030025,0.038113,0.047549,0.055637,0.064309,0.072409,0.080578,0.087915,0.093816,0.098925
Temperature (°C) [sea_water_potential_temperature]{300m},0.384256,0.377894,0.520192,0.522092,0.634042,0.643171,0.736759,0.750256,0.827187,0.837971
Salinity (PSU) [sea_water_salinity]{300m},0.083543,0.083010,0.110561,0.110970,0.134478,0.136119,0.154843,0.156522,0.171905,0.173356
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.028229,0.035370,0.043709,0.051500,0.059759,0.067737,0.075579,0.082753,0.088248,0.093114
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.027029,0.034652,0.043478,0.051327,0.059437,0.067187,0.074837,0.081811,0.087337,0.092217
Temperature (°C) [sea_water_potential_temperature]{500m},0.257045,0.255060,0.371546,0.382967,0.498337,0.519655,0.610705,0.632121,0.705716,0.722319
Salinity (PSU) [sea_water_salinity]{500m},0.058124,0.057617,0.076475,0.078057,0.097595,0.100958,0.116614,0.119779,0.132847,0.135663
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.024955,0.031491,0.038990,0.045828,0.052918,0.059673,0.066325,0.072380,0.077082,0.081269
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.023584,0.030349,0.038134,0.045012,0.052119,0.058821,0.065411,0.071467,0.076304,0.080649

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},75.629227,76.012535,78.685432,78.759926,81.156929,81.413277,82.855034,83.027519,83.914505,84.269417

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.410454,0.399396,0.405024,0.398621,0.419911,0.424263,0.446396,0.455243,0.475686,0.484313
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.323358,0.306841,0.271667,0.269732,0.272559,0.279478,0.291004,0.300339,0.316435,0.328550

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [11]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},4.714427,9.44894,14.096101,19.238609,25.035793,31.449961,38.423111,45.803799

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [12]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Temperature (°C) [sea_water_potential_temperature]{surface},0.882235,0.848099,0.980622,0.983427,1.106530,1.100990,1.198611,1.216192,1.287226,1.303111
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.894089,0.890104,1.025792,1.010542,1.114844,1.119855,1.173234,1.199414,1.298937,1.325345
Temperature (°C) [sea_water_potential_temperature]{5-100m},1.012522,0.987766,1.115885,1.101720,1.214045,1.205653,1.305376,1.328021,1.415855,1.440062
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.892178,0.871782,0.984919,1.007908,1.141719,1.123518,1.258266,1.305251,1.403417,1.422389
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.553889,0.550575,0.608966,0.617757,0.715644,0.723057,0.798894,0.826129,0.900146,0.930288
Salinity (PSU) [sea_water_salinity]{0-5m},0.299631,0.294696,0.329935,0.301886,0.336420,0.334276,0.357489,0.379870,0.404438,0.407642
Salinity (PSU) [sea_water_salinity]{5-100m},0.233986,0.235470,0.260675,0.260518,0.294612,0.295816,0.321245,0.329266,0.363185,0.358250
Salinity (PSU) [sea_water_salinity]{100-300m},0.152147,0.150475,0.174878,0.175192,0.202776,0.203771,0.225514,0.226946,0.249556,0.250774
Salinity (PSU) [sea_water_salinity]{300-600m},0.092497,0.091363,0.107677,0.108163,0.131178,0.134988,0.150998,0.155983,0.171378,0.173326
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.123209,0.123157,0.126075,0.126957,0.128860,0.130550,0.133437,0.136028,0.139491,0.142238
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.213488,0.216377,0.218003,0.216919,0.218504,0.223078,0.226164,0.227065,0.229854,0.232182
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.196257,0.198076,0.200384,0.201461,0.204171,0.206174,0.209361,0.210243,0.213297,0.217718