In [1]:
import oceanbench

oceanbench.__version__

'0.6.0'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open GLO12 forecasts with oceanbench, for a single first day
from datetime import datetime
import xarray
import oceanbench

challenger_dataset: xarray.Dataset = oceanbench.datasets.challenger.glo12([datetime.fromisoformat("2024-01-03")])

challenger_dataset

<xarray.Dataset> Size: 71GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 50,
                         latitude: 2041, longitude: 4320)
Coordinates:
  * depth               (depth) float32 200B 0.494 1.541 ... 5.275e+03 5.728e+03
  * latitude            (latitude) float32 8kB -80.0 -79.92 ... 89.92 90.0
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * longitude           (longitude) float32 17kB -180.0 -179.9 ... 179.8 179.9
  * first_day_datetime  (first_day_datetime) datetime64[ns] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 18GB dask.array<chunksize=(1, 1, 1, 640, 1280), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 18GB dask.array<chunksize=(1, 1, 1, 640, 1280), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 18GB dask.array<chunksize=(1, 1, 1, 640, 1280), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 18GB dask.array<chunksize=(1, 1, 1, 640, 1280), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 353MB dask.array<chunksize=(1, 1, 640, 1280), meta=np.ndarray>
Attributes:
    oceanbench_source_kind:  challenger
    oceanbench_source_name:  glo12

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.066496,0.067432,0.068384,0.069423,0.070747,0.072818,0.074522,0.076928,0.079110,0.080469,0,0.0
Temperature (°C) [sea_water_potential_temperature]{surface},0.596496,0.597348,0.597267,0.600851,0.606395,0.616655,0.629150,0.638889,0.654936,0.675432,0,0.0
Salinity (PSU) [sea_water_salinity]{surface},0.655742,0.664689,0.665591,0.664050,0.661393,0.664431,0.667166,0.667938,0.667169,0.664478,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.132547,0.135335,0.138334,0.140896,0.143718,0.147327,0.151765,0.156274,0.159910,0.163484,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.133485,0.135687,0.138206,0.141191,0.145182,0.149441,0.154419,0.157166,0.162114,0.165931,0,0.0
Temperature (°C) [sea_water_potential_temperature]{50m},0.984868,0.987826,0.992824,0.991732,0.998524,1.006283,1.012924,1.024986,1.029865,1.034847,0,0.0
Salinity (PSU) [sea_water_salinity]{50m},0.258675,0.258588,0.258843,0.258863,0.258760,0.259334,0.260144,0.261037,0.261534,0.262248,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.125979,0.128635,0.130902,0.133411,0.135613,0.138569,0.141685,0.144796,0.147432,0.150054,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.127465,0.129164,0.131181,0.133563,0.136037,0.138842,0.142002,0.144980,0.147472,0.149985,0,0.0
Temperature (°C) [sea_water_potential_temperature]{100m},1.177098,1.178816,1.179884,1.181027,1.184476,1.191009,1.195699,1.206062,1.216754,1.226750,0,0.0
Salinity (PSU) [sea_water_salinity]{100m},0.201822,0.201580,0.201428,0.201479,0.201783,0.202016,0.202428,0.203253,0.203704,0.203967,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.125606,0.127368,0.129553,0.131362,0.133251,0.135903,0.138477,0.141061,0.143245,0.145098,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.130829,0.132208,0.133717,0.135589,0.137572,0.140032,0.142296,0.144383,0.146378,0.147978,0,0.0
Temperature (°C) [sea_water_potential_temperature]{200m},0.884285,0.886367,0.889250,0.893661,0.899177,0.906599,0.915153,0.924182,0.933245,0.942893,0,0.0
Salinity (PSU) [sea_water_salinity]{200m},0.158664,0.158616,0.158639,0.158950,0.159379,0.159888,0.160676,0.161522,0.162283,0.163209,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.125678,0.127205,0.128267,0.129371,0.130466,0.131929,0.133745,0.135518,0.137085,0.138489,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.130949,0.131805,0.132813,0.134137,0.135756,0.137118,0.138563,0.140330,0.141369,0.142210,0,0.0
Temperature (°C) [sea_water_potential_temperature]{300m},0.752975,0.755829,0.758887,0.763426,0.768823,0.775947,0.784078,0.792688,0.800067,0.808170,0,0.0
Salinity (PSU) [sea_water_salinity]{300m},0.133087,0.133160,0.133292,0.133608,0.134065,0.134689,0.135442,0.136280,0.136974,0.137718,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.121381,0.122527,0.123484,0.124465,0.125631,0.127030,0.128642,0.129950,0.131060,0.132046,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.125236,0.126174,0.126968,0.128026,0.129299,0.130463,0.131636,0.132935,0.133858,0.134819,0,0.0
Temperature (°C) [sea_water_potential_temperature]{500m},0.583518,0.585451,0.587637,0.590469,0.594148,0.598769,0.604482,0.610557,0.615071,0.619764,0,0.0
Salinity (PSU) [sea_water_salinity]{500m},0.102193,0.102249,0.102281,0.102403,0.102630,0.102944,0.103321,0.103758,0.104088,0.104483,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.110767,0.111665,0.112358,0.112926,0.113554,0.114266,0.115299,0.116178,0.117017,0.117935,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.114825,0.115598,0.116170,0.117015,0.117825,0.118296,0.119092,0.119841,0.120415,0.121056,0,0.0

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},22.294844,22.351221,22.493141,22.959343,23.466652,23.573471,23.560162,24.521633,24.890278,25.362614,0,0.0

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.156253,0.158932,0.158206,0.163044,0.165589,0.168383,0.171338,0.174252,0.176608,0.179870,36439,0.006000
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.166361,0.167862,0.171777,0.175597,0.174775,0.180046,0.180275,0.183276,0.185321,0.188613,63940,0.007918

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Observations,Missing
Temperature (°C) [sea_water_potential_temperature]{surface},0.698089,0.927898,0.864189,0.834954,0.769572,0.745146,0.767709,0.787654,0.809103,0.853787,2999,0
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.544097,0.502212,0.485689,0.590999,0.834768,0.542431,0.710689,0.716850,0.512728,0.894847,3784,0
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.869986,0.887278,0.670723,0.916237,1.039579,0.855822,0.943593,0.958123,0.848661,1.237212,55628,0
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.746052,0.926403,0.724052,0.872505,0.863351,0.824564,0.896019,0.969545,0.916117,1.012719,49367,0
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.555713,0.644099,0.535973,0.621094,0.558632,0.513790,0.591061,0.625126,0.576290,0.694691,48406,0
Salinity (PSU) [sea_water_salinity]{0-5m},0.164220,0.234083,0.274495,0.325659,0.204744,0.201835,0.207920,0.341435,0.210575,0.248499,3334,0
Salinity (PSU) [sea_water_salinity]{5-100m},0.162436,0.221071,0.208476,0.202519,0.218712,0.184915,0.234819,0.285956,0.198790,0.234222,44699,0
Salinity (PSU) [sea_water_salinity]{100-300m},0.135557,0.158042,0.121382,0.146824,0.140059,0.131066,0.161915,0.148178,0.134333,0.161744,40755,0
Salinity (PSU) [sea_water_salinity]{300-600m},0.092361,0.109207,0.089212,0.098555,0.088454,0.082343,0.089716,0.098682,0.090965,0.099250,41131,0
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.049941,0.052248,0.054505,0.056901,0.059940,0.064901,0.065340,0.068496,0.069662,0.072145,296169,0
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.123211,0.120236,0.134178,0.144556,0.140371,0.141670,0.147518,0.153985,0.156496,0.156625,22829,0
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.125738,0.126159,0.131603,0.139682,0.144473,0.158124,0.161336,0.150489,0.151333,0.158694,22829,0

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

/scratch/jseillade/oceanbench-class4-gate/.venv/lib/python3.13/site-packages/parcels/fieldset.py:1503: FieldSetWarning: The zonal halo is located at the east and west of current grid, with a dx = lon[1]-lon[0] between the last nodes of the original grid and the first ones of the halo. In your grid, lon[1]-lon[0] != lon[-1]-lon[-2]. Is the halo computed as you expect?
  grid.add_periodic_halo(zonal, meridional, halosize)

/scratch/jseillade/oceanbench-class4-gate/.venv/lib/python3.13/site-packages/parcels/kernel.py:254: KernelWarning: _time declared in multiple Kernels
  kernel_ccode = kernelgen.generate(deepcopy(self.py_ast), self.funcvars)

/scratch/jseillade/oceanbench-class4-gate/.venv/lib/python3.13/site-packages/parcels/fieldset.py:1503: FieldSetWarning: The zonal halo is located at the east and west of current grid, with a dx = lon[1]-lon[0] between the last nodes of the original grid and the first ones of the halo. In your grid, lon[1]-lon[0] != lon[-1]-lon[-2]. Is the halo computed as you expect?
  grid.add_periodic_halo(zonal, meridional, halosize)
/scratch/jseillade/oceanbench-class4-gate/.venv/lib/python3.13/site-packages/parcels/kernel.py:254: KernelWarning: _time declared in multiple Kernels
  kernel_ccode = kernelgen.generate(deepcopy(self.py_ast), self.funcvars)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},11.966262,23.446259,34.348755,44.800011,54.902374,64.765976,74.472092,83.918938

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.010584,0.013134,0.016955,0.021572,0.026335,0.031919,0.037264,0.043218,0.047539,0.049919,0,0.0
Temperature (°C) [sea_water_potential_temperature]{surface},0.115555,0.147651,0.190515,0.239739,0.293110,0.348292,0.403167,0.451911,0.492535,0.536025,0,0.0
Salinity (PSU) [sea_water_salinity]{surface},0.054543,0.068067,0.084395,0.102846,0.124877,0.145569,0.160629,0.178222,0.191667,0.205502,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.032445,0.040633,0.051600,0.064047,0.077703,0.090237,0.102699,0.114199,0.122060,0.129988,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.031411,0.040314,0.052055,0.064029,0.076356,0.089249,0.102693,0.112859,0.123583,0.131331,0,0.0
Temperature (°C) [sea_water_potential_temperature]{50m},0.179044,0.213175,0.261678,0.316171,0.378630,0.448257,0.508074,0.567204,0.607937,0.636307,0,0.0
Salinity (PSU) [sea_water_salinity]{50m},0.041457,0.048778,0.058831,0.070204,0.082625,0.095955,0.108644,0.120632,0.128762,0.136089,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.030866,0.037277,0.045504,0.055495,0.066658,0.078553,0.090562,0.100747,0.108158,0.114525,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.029886,0.036235,0.044531,0.054236,0.065192,0.076479,0.087674,0.097785,0.104851,0.111114,0,0.0
Temperature (°C) [sea_water_potential_temperature]{100m},0.209278,0.242722,0.292385,0.354105,0.423703,0.492280,0.559754,0.622833,0.663046,0.703578,0,0.0
Salinity (PSU) [sea_water_salinity]{100m},0.035086,0.041360,0.049596,0.059398,0.070269,0.081701,0.093003,0.103202,0.109980,0.116108,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.028819,0.034614,0.042245,0.051569,0.062112,0.073240,0.084105,0.093925,0.100702,0.106681,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.028391,0.034303,0.041958,0.050678,0.060446,0.070748,0.081125,0.090434,0.097099,0.102737,0,0.0
Temperature (°C) [sea_water_potential_temperature]{200m},0.150352,0.178173,0.216190,0.263090,0.316347,0.372607,0.429653,0.482676,0.517896,0.551157,0,0.0
Salinity (PSU) [sea_water_salinity]{200m},0.025449,0.030066,0.036088,0.043453,0.051742,0.060488,0.069331,0.077619,0.083524,0.088909,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.023710,0.028424,0.034526,0.042103,0.050765,0.059999,0.069434,0.078188,0.084286,0.089564,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.022462,0.027146,0.033302,0.040787,0.048998,0.057622,0.066253,0.074072,0.079643,0.084621,0,0.0
Temperature (°C) [sea_water_potential_temperature]{300m},0.123842,0.148541,0.181789,0.222611,0.269102,0.319148,0.370091,0.417067,0.449224,0.478850,0,0.0
Salinity (PSU) [sea_water_salinity]{300m},0.020582,0.024671,0.029902,0.036263,0.043399,0.050998,0.058628,0.065678,0.070881,0.075602,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.021609,0.025880,0.031562,0.038505,0.046451,0.054902,0.063634,0.071760,0.077391,0.082287,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.020424,0.024653,0.030105,0.036870,0.044386,0.052285,0.060249,0.067466,0.072678,0.077533,0,0.0
Temperature (°C) [sea_water_potential_temperature]{500m},0.095920,0.114598,0.140126,0.171958,0.207820,0.245988,0.285237,0.321580,0.345971,0.367654,0,0.0
Salinity (PSU) [sea_water_salinity]{500m},0.015713,0.018654,0.022452,0.027086,0.032288,0.037797,0.043398,0.048652,0.052560,0.056027,0,0.0
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.017836,0.021330,0.026032,0.031737,0.038287,0.045424,0.052840,0.059690,0.064452,0.068677,0,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.016795,0.020252,0.024760,0.030251,0.036362,0.042862,0.049526,0.055703,0.060275,0.064582,0,0.0

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},6.40817,8.620281,10.647681,12.530628,14.270584,15.625167,16.624657,18.623198,19.733885,21.026096,0,0.0

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.05201,0.058884,0.067616,0.079881,0.092143,0.104112,0.11743,0.126103,0.133064,0.14082,36439,0.006000
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.05398,0.062213,0.071365,0.083367,0.096477,0.107450,0.11947,0.128591,0.136544,0.14253,63940,0.007918

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

/scratch/jseillade/oceanbench-class4-gate/.venv/lib/python3.13/site-packages/parcels/fieldset.py:1503: FieldSetWarning: The zonal halo is located at the east and west of current grid, with a dx = lon[1]-lon[0] between the last nodes of the original grid and the first ones of the halo. In your grid, lon[1]-lon[0] != lon[-1]-lon[-2]. Is the halo computed as you expect?
  grid.add_periodic_halo(zonal, meridional, halosize)
/scratch/jseillade/oceanbench-class4-gate/.venv/lib/python3.13/site-packages/parcels/kernel.py:254: KernelWarning: _time declared in multiple Kernels
  kernel_ccode = kernelgen.generate(deepcopy(self.py_ast), self.funcvars)

/scratch/jseillade/oceanbench-class4-gate/.venv/lib/python3.13/site-packages/parcels/fieldset.py:1503: FieldSetWarning: The zonal halo is located at the east and west of current grid, with a dx = lon[1]-lon[0] between the last nodes of the original grid and the first ones of the halo. In your grid, lon[1]-lon[0] != lon[-1]-lon[-2]. Is the halo computed as you expect?
  grid.add_periodic_halo(zonal, meridional, halosize)
/scratch/jseillade/oceanbench-class4-gate/.venv/lib/python3.13/site-packages/parcels/kernel.py:254: KernelWarning: _time declared in multiple Kernels
  kernel_ccode = kernelgen.generate(deepcopy(self.py_ast), self.funcvars)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},2.577581,5.65443,9.35242,13.716369,18.872364,24.926565,31.651903,38.742718