In [1]:
import oceanbench

oceanbench.__version__

'0.6.0'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# SPDX-FileCopyrightText: 2025 Mercator Ocean International <https://www.mercator-ocean.eu/>
#
# SPDX-License-Identifier: EUPL-1.2

# Open GLO36V1 forecasts with oceanbench, for a single first day
from datetime import datetime
import xarray
import oceanbench

challenger_dataset: xarray.Dataset = oceanbench.datasets.challenger.glo36v1([datetime.fromisoformat("2023-01-04")])

challenger_dataset["zos"].attrs["standard_name"] = "sea_surface_height_above_geoid"
challenger_dataset["thetao"].attrs["standard_name"] = "sea_water_potential_temperature"
challenger_dataset["so"].attrs["standard_name"] = "sea_water_salinity"
challenger_dataset["uo"].attrs["standard_name"] = "eastward_sea_water_velocity"
challenger_dataset["vo"].attrs["standard_name"] = "northward_sea_water_velocity"
challenger_dataset["latitude"].attrs["standard_name"] = "latitude"
challenger_dataset["longitude"].attrs["standard_name"] = "longitude"

challenger_dataset

<xarray.Dataset> Size: 50GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 7, depth: 50,
                         latitude: 2041, longitude: 4320)
Coordinates:
  * depth               (depth) float32 200B 0.494 1.541 ... 5.275e+03 5.728e+03
  * latitude            (latitude) float32 8kB -80.0 -79.92 ... 89.92 90.0
  * lead_day_index      (lead_day_index) int64 56B 0 1 2 3 4 5 6
  * longitude           (longitude) float32 17kB -180.0 -179.9 ... 179.8 179.9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2023-01-04
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 12GB dask.array<chunksize=(1, 1, 7, 256, 540), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 12GB dask.array<chunksize=(1, 1, 7, 256, 540), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 12GB dask.array<chunksize=(1, 1, 7, 256, 540), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 12GB dask.array<chunksize=(1, 1, 7, 256, 540), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 247MB dask.array<chunksize=(1, 1, 256, 1080), meta=np.ndarray>
Attributes:
    oceanbench_source_kind:  challenger
    oceanbench_source_name:  glo36v1

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Missing fraction
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.155215,0.156728,0.157758,0.157750,0.153628,0.150502,0.152158,0.004783
Temperature (°C) [sea_water_potential_temperature]{surface},0.665675,0.666236,0.668971,0.669832,0.674065,0.683062,0.690108,0.004783
Salinity (PSU) [sea_water_salinity]{surface},0.689931,0.694035,0.696489,0.694867,0.697209,0.702093,0.708864,0.004783
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.169008,0.171432,0.174479,0.177971,0.181054,0.184246,0.187500,0.021592
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.170210,0.173496,0.176848,0.180090,0.183793,0.186388,0.190254,0.021610
Temperature (°C) [sea_water_potential_temperature]{50m},1.039166,1.043895,1.046214,1.050040,1.060366,1.066744,1.075683,0.001505
Salinity (PSU) [sea_water_salinity]{50m},0.334729,0.334988,0.334923,0.334744,0.334696,0.334771,0.335153,0.001505
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.163586,0.165988,0.167990,0.170079,0.171980,0.173889,0.176087,0.018939
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.162945,0.165826,0.168122,0.169979,0.171916,0.173828,0.176105,0.018769
Temperature (°C) [sea_water_potential_temperature]{100m},1.153564,1.156981,1.162204,1.164618,1.173824,1.182703,1.191273,0.001090
Salinity (PSU) [sea_water_salinity]{100m},0.232870,0.232681,0.232448,0.232212,0.232310,0.232527,0.232984,0.001090
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.158490,0.160174,0.162280,0.164546,0.166069,0.167569,0.169403,0.017705
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.159664,0.161743,0.163031,0.164312,0.166117,0.168162,0.170436,0.017530
Temperature (°C) [sea_water_potential_temperature]{200m},0.957408,0.958963,0.962378,0.965451,0.966452,0.969839,0.975099,0.000900
Salinity (PSU) [sea_water_salinity]{200m},0.180879,0.180387,0.180104,0.179890,0.179562,0.179501,0.179619,0.000900
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.146192,0.147810,0.149101,0.150285,0.151414,0.152376,0.153446,0.017024
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.149932,0.151562,0.152828,0.153370,0.154048,0.155399,0.156973,0.016987
Temperature (°C) [sea_water_potential_temperature]{300m},0.810848,0.814909,0.819766,0.824011,0.826955,0.830712,0.835995,0.000931
Salinity (PSU) [sea_water_salinity]{300m},0.151903,0.151675,0.151554,0.151446,0.151296,0.151244,0.151388,0.000931
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.139756,0.141108,0.142327,0.143590,0.144634,0.145573,0.146525,0.017055
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.144129,0.145562,0.146662,0.147270,0.148044,0.149210,0.150433,0.017105
Temperature (°C) [sea_water_potential_temperature]{500m},0.615496,0.619419,0.623549,0.627787,0.631875,0.636932,0.643927,0.000979
Salinity (PSU) [sea_water_salinity]{500m},0.112535,0.112275,0.112096,0.111986,0.111887,0.111906,0.112113,0.000979
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.126165,0.127052,0.127919,0.128847,0.129769,0.130633,0.131326,0.017224
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.130247,0.131347,0.132150,0.132634,0.133311,0.134119,0.135223,0.017424

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Missing fraction
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},24.756285,24.473972,24.634949,24.977373,25.423313,25.686895,25.81818,0.004783

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Missing fraction
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.163268,0.165897,0.168537,0.171045,0.173190,0.175114,0.177441,0.005257
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.159641,0.162355,0.165043,0.166862,0.169047,0.171893,0.174726,0.005385

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

                                             Message
0  Observation-based Class IV scores were not com...

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Lagrangian trajectory deviation (km) []{surface},14.797675,28.752476,41.79464,54.078381,65.844803,77.223824

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Missing fraction
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.132830,0.135011,0.136307,0.135258,0.130190,0.126576,0.127505,0.004783
Temperature (°C) [sea_water_potential_temperature]{surface},0.467767,0.476978,0.487376,0.500124,0.515669,0.538086,0.561383,0.004783
Salinity (PSU) [sea_water_salinity]{surface},0.337514,0.343491,0.349799,0.354086,0.361679,0.373402,0.386378,0.004783
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.140661,0.144091,0.148598,0.153858,0.159287,0.164414,0.171387,0.021593
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.137320,0.142179,0.147499,0.152941,0.159396,0.164407,0.170601,0.021611
Temperature (°C) [sea_water_potential_temperature]{50m},0.655873,0.676183,0.689140,0.703769,0.725207,0.747484,0.773427,0.001505
Salinity (PSU) [sea_water_salinity]{50m},0.244657,0.246750,0.248977,0.251178,0.253552,0.256274,0.259551,0.001505
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.135643,0.138918,0.142623,0.146713,0.150699,0.154600,0.158789,0.018943
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.132147,0.136423,0.140056,0.143926,0.148402,0.152490,0.157082,0.018774
Temperature (°C) [sea_water_potential_temperature]{100m},0.697582,0.713848,0.732500,0.755558,0.782513,0.812538,0.841639,0.001090
Salinity (PSU) [sea_water_salinity]{100m},0.160457,0.162851,0.165447,0.168512,0.171635,0.174873,0.178787,0.001090
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.129766,0.132825,0.136140,0.140134,0.143916,0.147789,0.151703,0.017711
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.127257,0.130713,0.133815,0.137146,0.141344,0.145605,0.149913,0.017536
Temperature (°C) [sea_water_potential_temperature]{200m},0.583189,0.599710,0.616098,0.634465,0.654506,0.676216,0.699626,0.000900
Salinity (PSU) [sea_water_salinity]{200m},0.125318,0.127247,0.129304,0.131678,0.134221,0.136967,0.139932,0.000900
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.110610,0.113637,0.116684,0.120091,0.123457,0.126740,0.129905,0.017027
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.108486,0.111728,0.114848,0.117830,0.121034,0.124469,0.128035,0.016990
Temperature (°C) [sea_water_potential_temperature]{300m},0.515024,0.531024,0.547463,0.564641,0.582531,0.601597,0.622289,0.000931
Salinity (PSU) [sea_water_salinity]{300m},0.105204,0.107106,0.109012,0.111099,0.113437,0.115970,0.118632,0.000931
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.102956,0.105647,0.108438,0.111730,0.115026,0.118250,0.121312,0.017057
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.100470,0.103614,0.106612,0.109347,0.112495,0.115762,0.119014,0.017108
Temperature (°C) [sea_water_potential_temperature]{500m},0.401546,0.414780,0.429168,0.445301,0.462005,0.479272,0.498436,0.000979
Salinity (PSU) [sea_water_salinity]{500m},0.077319,0.078718,0.080192,0.081901,0.083809,0.085850,0.088028,0.000979
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.088352,0.090651,0.093130,0.096040,0.099024,0.101922,0.104544,0.017227
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.085942,0.088765,0.091423,0.093737,0.096224,0.099012,0.102010,0.017427

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Missing fraction
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},19.69573,19.901588,20.456421,21.267048,22.189333,23.112871,23.735374,0.004783

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Missing fraction
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.134636,0.138067,0.142136,0.146588,0.150971,0.155317,0.159834,0.004642
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.131077,0.134935,0.139085,0.143047,0.147169,0.152093,0.157241,0.004598

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Lagrangian trajectory deviation (km) []{surface},11.448439,22.286804,32.480621,42.351879,51.965343,61.347389