In [1]:
import oceanbench

oceanbench.__version__

'0.4.0'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# SPDX-FileCopyrightText: 2025 Mercator Ocean International <https://www.mercator-ocean.eu/>
#
# SPDX-License-Identifier: EUPL-1.2

# Open GLONET forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = (
    xarray.open_mfdataset(
        [
            "https://minio.dive.edito.eu/project-moi-glo36-oceanbench/public/20230104.zarr",
        ],
        engine="zarr",
        combine="nested",
        concat_dim="first_day_datetime",
        parallel=True,
    )
    .rename({"lat": "latitude", "lon": "longitude"})
    .unify_chunks()
    .assign({"first_day_datetime": [datetime.fromisoformat("2023-01-04")]})
)


challenger_dataset["zos"].attrs["standard_name"] = "sea_surface_height_above_geoid"
challenger_dataset["thetao"].attrs["standard_name"] = "sea_water_potential_temperature"
challenger_dataset["so"].attrs["standard_name"] = "sea_water_salinity"
challenger_dataset["uo"].attrs["standard_name"] = "eastward_sea_water_velocity"
challenger_dataset["vo"].attrs["standard_name"] = "northward_sea_water_velocity"
challenger_dataset["latitude"].attrs["standard_name"] = "latitude"
challenger_dataset["longitude"].attrs["standard_name"] = "longitude"

challenger_dataset

print(challenger_dataset)

<xarray.Dataset> Size: 50GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 7, depth: 50,
                         latitude: 2041, longitude: 4320)
Coordinates:
  * depth               (depth) float32 200B 0.494 1.541 ... 5.275e+03 5.728e+03
  * latitude            (latitude) float32 8kB -80.0 -79.92 ... 89.92 90.0
  * lead_day_index      (lead_day_index) int64 56B 0 1 2 3 4 5 6
  * longitude           (longitude) float32 17kB -180.0 -179.9 ... 179.8 179.9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2023-01-04
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 12GB dask.array<chunksize=(1, 1, 7, 256, 540), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 12GB dask.array<chunksize=(1, 1, 7, 256, 540), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 12GB dask.array<chunksize=(1, 1, 7, 256, 540), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 12GB dask.array<chunksize=(1, 1, 7, 256, 540), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 247MB dask.array<chunksize=(1, 1, 256, 540), meta=np.ndarray>

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.155215,0.156728,0.157758,0.157750,0.153628,0.150502,0.152158
Temperature (°C) [sea_water_potential_temperature]{surface},0.665675,0.666236,0.668971,0.669832,0.674065,0.683062,0.690108
Salinity (PSU) [sea_water_salinity]{surface},0.689931,0.694035,0.696489,0.694867,0.697209,0.702093,0.708864
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.169008,0.171432,0.174479,0.177971,0.181054,0.184246,0.187500
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.170210,0.173496,0.176848,0.180090,0.183793,0.186388,0.190254
Temperature (°C) [sea_water_potential_temperature]{50m},1.039166,1.043895,1.046214,1.050040,1.060366,1.066744,1.075683
Salinity (PSU) [sea_water_salinity]{50m},0.334729,0.334988,0.334923,0.334744,0.334696,0.334771,0.335153
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.163586,0.165988,0.167990,0.170079,0.171980,0.173889,0.176087
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.162945,0.165826,0.168122,0.169979,0.171916,0.173828,0.176105
Temperature (°C) [sea_water_potential_temperature]{100m},1.153564,1.156981,1.162204,1.164618,1.173824,1.182703,1.191273
Salinity (PSU) [sea_water_salinity]{100m},0.232870,0.232681,0.232448,0.232212,0.232310,0.232527,0.232984
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.158490,0.160174,0.162280,0.164546,0.166069,0.167569,0.169403
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.159664,0.161743,0.163031,0.164312,0.166117,0.168162,0.170436
Temperature (°C) [sea_water_potential_temperature]{200m},0.957408,0.958963,0.962378,0.965451,0.966452,0.969839,0.975099
Salinity (PSU) [sea_water_salinity]{200m},0.180879,0.180387,0.180104,0.179890,0.179562,0.179501,0.179619
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.146192,0.147810,0.149101,0.150285,0.151414,0.152376,0.153446
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.149932,0.151562,0.152828,0.153370,0.154048,0.155399,0.156973
Temperature (°C) [sea_water_potential_temperature]{300m},0.810848,0.814909,0.819766,0.824011,0.826955,0.830712,0.835995
Salinity (PSU) [sea_water_salinity]{300m},0.151903,0.151675,0.151554,0.151446,0.151296,0.151244,0.151388
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.139756,0.141108,0.142327,0.143590,0.144634,0.145573,0.146525
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.144129,0.145562,0.146662,0.147270,0.148044,0.149210,0.150433
Temperature (°C) [sea_water_potential_temperature]{500m},0.615496,0.619419,0.623549,0.627787,0.631875,0.636932,0.643927
Salinity (PSU) [sea_water_salinity]{500m},0.112535,0.112275,0.112096,0.111986,0.111887,0.111906,0.112113
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.126165,0.127052,0.127919,0.128847,0.129769,0.130633,0.131326
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.130247,0.131347,0.132150,0.132634,0.133311,0.134119,0.135223

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},24.101236,23.806906,23.99403,24.353876,24.828894,25.103966,25.220552

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.192943,0.195740,0.200314,0.204898,0.206384,0.205924,0.203758
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.201235,0.203887,0.202246,0.205156,0.205795,0.207753,0.210375

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

                                             Message
0  Observation-based Class IV scores were not com...

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6
Lagrangian trajectory deviation (km) []{surface},14.796522,28.749208,41.791946,54.065723,65.840233

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.132830,0.135011,0.136306,0.135258,0.130190,0.126575,0.127505
Temperature (°C) [sea_water_potential_temperature]{surface},0.467767,0.476977,0.487375,0.500123,0.515669,0.538085,0.561382
Salinity (PSU) [sea_water_salinity]{surface},0.337515,0.343492,0.349799,0.354086,0.361679,0.373402,0.386378
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.140661,0.144091,0.148598,0.153858,0.159287,0.164414,0.171387
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.137320,0.142179,0.147499,0.152941,0.159396,0.164407,0.170601
Temperature (°C) [sea_water_potential_temperature]{50m},0.656582,0.676856,0.689798,0.704411,0.725821,0.748073,0.773979
Salinity (PSU) [sea_water_salinity]{50m},0.254716,0.256727,0.258867,0.260992,0.263284,0.265901,0.269062
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.135640,0.138914,0.142620,0.146709,0.150695,0.154597,0.158785
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.132145,0.136421,0.140054,0.143924,0.148400,0.152488,0.157080
Temperature (°C) [sea_water_potential_temperature]{100m},0.697711,0.713965,0.732609,0.755661,0.782602,0.812610,0.841695
Salinity (PSU) [sea_water_salinity]{100m},0.160932,0.163320,0.165910,0.168965,0.172076,0.175304,0.179210
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.129764,0.132822,0.136138,0.140131,0.143914,0.147786,0.151700
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.127255,0.130712,0.133813,0.137144,0.141342,0.145603,0.149911
Temperature (°C) [sea_water_potential_temperature]{200m},0.583212,0.599720,0.616094,0.634459,0.654492,0.676196,0.699603
Salinity (PSU) [sea_water_salinity]{200m},0.125835,0.127759,0.129811,0.132181,0.134716,0.137451,0.140409
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.110608,0.113635,0.116682,0.120089,0.123455,0.126738,0.129903
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.108486,0.111727,0.114847,0.117829,0.121033,0.124468,0.128034
Temperature (°C) [sea_water_potential_temperature]{300m},0.515046,0.531046,0.547478,0.564646,0.582531,0.601590,0.622280
Salinity (PSU) [sea_water_salinity]{300m},0.105213,0.107116,0.109022,0.111108,0.113448,0.115984,0.118647
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.102954,0.105645,0.108436,0.111728,0.115024,0.118248,0.121310
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.100470,0.103613,0.106611,0.109347,0.112494,0.115762,0.119013
Temperature (°C) [sea_water_potential_temperature]{500m},0.401600,0.414830,0.429214,0.445342,0.462042,0.479306,0.498465
Salinity (PSU) [sea_water_salinity]{500m},0.077515,0.078911,0.080381,0.082086,0.083989,0.086025,0.088199
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.088350,0.090650,0.093129,0.096039,0.099023,0.101921,0.104542
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.085941,0.088764,0.091422,0.093736,0.096224,0.099012,0.102009

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},19.249165,19.438047,19.993404,20.820271,21.75522,22.670568,23.337448

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.169131,0.172222,0.176603,0.181559,0.185345,0.186389,0.187139
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.175118,0.179872,0.180460,0.183230,0.187518,0.190938,0.193037

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6
Lagrangian trajectory deviation (km) []{surface},11.445717,22.282148,32.474842,42.342556,51.94735