In [1]:
import oceanbench

oceanbench.__version__

'0.6.0'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open GLONET forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://s3.waw3-1.cloudferro.com/oceanbench-bucket/public/ml-forecast-outputs/glonet/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 7GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 21,
                         latitude: 672, longitude: 1440)
Coordinates:
  * depth               (depth) float32 84B 0.494 47.37 ... 4.833e+03 5.275e+03
  * latitude            (latitude) float64 5kB -78.0 -77.75 -77.5 ... 89.5 89.75
  * longitude           (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[ns] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 2GB dask.array<chunksize=(1, 2, 3, 168, 360), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 2GB dask.array<chunksize=(1, 2, 3, 168, 360), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 2GB dask.array<chunksize=(1, 2, 3, 168, 360), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 2GB dask.array<chunksize=(1, 2, 3, 168, 360), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float64 77MB dask.array<chunksize=(1, 2, 168, 360), meta=np.ndarray>
Attributes:
    Conventions:              CF-1.8
    area:                     Global
    challenger:               glonet
    contact:                  glonet@mercator-ocean.eu
    forecast_reference_time:  2024-01-02
    institution:              Mercator Ocean International
    references:               www.edito.eu
    source:                   MOI GLONET
    title:                    Daily mean fields from GLONET 1/4 degree resolu...

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.074807,0.077333,0.076876,0.077340,0.080147,0.082982,0.084067,0.086376,0.088693,0.091225,924,0.000671
Temperature (°C) [sea_water_potential_temperature]{surface},0.654861,0.660455,0.705565,0.718789,0.776509,0.797294,0.864683,0.883868,0.934868,0.940642,924,0.000671
Salinity (PSU) [sea_water_salinity]{surface},0.589053,0.594278,0.593606,0.589564,0.585949,0.580917,0.581901,0.573794,0.574969,0.570810,924,0.000671
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.126571,0.128094,0.131573,0.132314,0.135833,0.137307,0.142662,0.145077,0.149295,0.149207,917,0.000666
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.129273,0.131023,0.133921,0.134595,0.138645,0.139974,0.144052,0.146013,0.148833,0.151239,917,0.000666
Temperature (°C) [sea_water_potential_temperature]{50m},1.036064,1.042687,1.072838,1.078255,1.114608,1.126663,1.169617,1.187405,1.224124,1.243935,754,0.000789
Salinity (PSU) [sea_water_salinity]{50m},0.245872,0.246462,0.251684,0.253498,0.258848,0.261132,0.267207,0.269189,0.274605,0.276569,754,0.000789
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.116857,0.117286,0.117303,0.117915,0.118957,0.120833,0.124273,0.126651,0.128540,0.129310,752,0.000788
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.119026,0.119238,0.119798,0.121373,0.122724,0.124436,0.127117,0.130067,0.133118,0.135079,752,0.000788
Temperature (°C) [sea_water_potential_temperature]{100m},1.156693,1.164308,1.172866,1.175904,1.195542,1.199871,1.228849,1.237754,1.273109,1.287088,620,0.000749
Salinity (PSU) [sea_water_salinity]{100m},0.194433,0.194742,0.194805,0.195661,0.198365,0.199249,0.203292,0.204767,0.209337,0.210638,620,0.000749
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.115273,0.115284,0.114455,0.115187,0.115781,0.117156,0.119301,0.121261,0.122445,0.123817,619,0.000749
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.122381,0.122419,0.122122,0.122645,0.123829,0.125553,0.127238,0.128859,0.130724,0.131236,619,0.000749
Temperature (°C) [sea_water_potential_temperature]{200m},0.892241,0.894258,0.908794,0.913302,0.920181,0.929604,0.936415,0.952802,0.962404,0.982313,605,0.000759
Salinity (PSU) [sea_water_salinity]{200m},0.155576,0.155520,0.156245,0.156481,0.157552,0.157973,0.159688,0.160477,0.162284,0.163213,605,0.000759
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.115543,0.115551,0.113795,0.113917,0.113823,0.114233,0.115008,0.115729,0.116268,0.116710,604,0.000758
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.121413,0.121105,0.119327,0.119354,0.119456,0.119832,0.120423,0.121149,0.121607,0.121554,604,0.000758
Temperature (°C) [sea_water_potential_temperature]{300m},0.755041,0.754119,0.761509,0.762238,0.761363,0.767478,0.770089,0.780063,0.783481,0.793767,418,0.000581
Salinity (PSU) [sea_water_salinity]{300m},0.128521,0.128383,0.128461,0.128577,0.128899,0.129528,0.130179,0.131244,0.132044,0.133351,418,0.000581
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.111839,0.111919,0.110120,0.110237,0.110160,0.110485,0.111136,0.111674,0.112162,0.112172,418,0.000581
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.115529,0.115388,0.113579,0.113516,0.113503,0.113715,0.114090,0.114462,0.114970,0.114991,418,0.000581
Temperature (°C) [sea_water_potential_temperature]{500m},0.568398,0.571183,0.558424,0.562770,0.561880,0.567437,0.571498,0.577440,0.582960,0.588041,344,0.000491
Salinity (PSU) [sea_water_salinity]{500m},0.097412,0.097539,0.097263,0.097562,0.097853,0.098411,0.098927,0.099603,0.100214,0.100904,344,0.000491
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.101687,0.101814,0.100084,0.099957,0.099597,0.099588,0.099966,0.100110,0.100393,0.100484,344,0.000491
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.105600,0.105655,0.103637,0.103704,0.103466,0.103467,0.103596,0.103852,0.104240,0.104383,344,0.000491

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},32.350844,33.335157,34.430146,35.787383,37.30004,38.361283,40.088454,41.747514,42.610658,43.774797,924,0.000671

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.171384,0.177348,0.207699,0.216977,0.241816,0.256136,0.275111,0.293142,0.309230,0.329934,1503,0.001237
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.174580,0.181283,0.211562,0.223356,0.247149,0.259528,0.275540,0.300240,0.310485,0.340377,1409,0.001172

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Observations,Missing
Temperature (°C) [sea_water_potential_temperature]{surface},0.693906,0.904956,0.877292,0.844292,0.770526,0.807540,0.872366,0.855196,0.906132,0.879222,2999,0
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.613869,0.571863,0.546481,0.619500,0.682119,0.672918,0.884027,0.817073,0.846076,0.803362,3784,0
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.988923,1.116357,0.869182,1.066143,1.063498,0.976239,1.050651,1.103831,1.233444,1.359755,55628,0
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.852306,1.011760,0.807804,0.966290,0.950215,0.872566,0.925704,1.025130,0.906065,1.103458,49367,0
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.574940,0.626207,0.493661,0.588334,0.545107,0.482749,0.526752,0.599216,0.558874,0.587968,48406,0
Salinity (PSU) [sea_water_salinity]{0-5m},0.183389,0.239765,0.225042,0.371161,0.233768,0.196111,0.193971,0.248191,0.233785,0.245572,3334,0
Salinity (PSU) [sea_water_salinity]{5-100m},0.163737,0.212626,0.209635,0.215440,0.222296,0.184792,0.225809,0.219244,0.207043,0.215632,44699,0
Salinity (PSU) [sea_water_salinity]{100-300m},0.136914,0.156133,0.116360,0.145010,0.125126,0.117744,0.136231,0.129334,0.124286,0.162776,40755,0
Salinity (PSU) [sea_water_salinity]{300-600m},0.083013,0.101911,0.077352,0.085121,0.083636,0.071402,0.082265,0.100385,0.082556,0.097762,41131,0
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.049950,0.050505,0.050723,0.054259,0.055410,0.059799,0.060109,0.062934,0.064476,0.067870,296169,0
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.109848,0.109138,0.121574,0.131610,0.125672,0.119272,0.124753,0.128191,0.133732,0.132641,22829,0
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.114371,0.110853,0.114608,0.122051,0.128041,0.139676,0.139074,0.127094,0.129392,0.132285,22829,0

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},11.027288,21.413128,31.355328,40.894413,50.211521,59.409519,68.438553,77.333153

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.027536,0.033956,0.035543,0.037809,0.044815,0.050361,0.053951,0.058401,0.061127,0.064226,0,0.000000
Temperature (°C) [sea_water_potential_temperature]{surface},0.413983,0.431588,0.529214,0.550758,0.636960,0.670187,0.755759,0.784928,0.845896,0.856775,0,0.000000
Salinity (PSU) [sea_water_salinity]{surface},0.160955,0.167592,0.224084,0.229338,0.271767,0.280010,0.312231,0.311949,0.341671,0.348189,0,0.000000
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.051835,0.071239,0.087260,0.096436,0.108284,0.117464,0.129621,0.137008,0.144238,0.147582,2,0.000004
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.053059,0.074163,0.088408,0.099031,0.110724,0.118408,0.127200,0.136207,0.142873,0.147262,2,0.000004
Temperature (°C) [sea_water_potential_temperature]{50m},0.746167,0.750885,0.821684,0.843751,0.919511,0.946550,1.021938,1.048480,1.112154,1.133792,233,0.000239
Salinity (PSU) [sea_water_salinity]{50m},0.118600,0.120124,0.155652,0.157877,0.182491,0.185728,0.204919,0.208687,0.223041,0.224290,233,0.000239
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.045324,0.055653,0.066042,0.073581,0.082085,0.090858,0.101056,0.108542,0.114285,0.117933,233,0.000239
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.046699,0.057563,0.067820,0.077142,0.085290,0.092836,0.101922,0.109785,0.116569,0.121781,233,0.000239
Temperature (°C) [sea_water_potential_temperature]{100m},0.577007,0.598091,0.683635,0.716859,0.811006,0.853855,0.935660,0.980559,1.037901,1.068923,225,0.000233
Salinity (PSU) [sea_water_salinity]{100m},0.094246,0.095365,0.119897,0.121495,0.140055,0.142671,0.158230,0.161043,0.172224,0.172949,225,0.000233
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.041392,0.049395,0.058668,0.066353,0.075227,0.083516,0.091897,0.098997,0.104104,0.108633,225,0.000233
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.042521,0.050981,0.060070,0.067818,0.076010,0.084313,0.093212,0.101175,0.107277,0.111765,225,0.000233
Temperature (°C) [sea_water_potential_temperature]{200m},0.426998,0.434528,0.505553,0.523822,0.574268,0.604288,0.650458,0.684707,0.717355,0.745248,197,0.000185
Salinity (PSU) [sea_water_salinity]{200m},0.065365,0.065509,0.083929,0.085322,0.098763,0.101373,0.112075,0.114992,0.122844,0.124718,197,0.000185
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.033264,0.038870,0.046125,0.052756,0.060048,0.067383,0.074822,0.081800,0.086672,0.090967,197,0.000185
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.032933,0.038439,0.045941,0.052088,0.059578,0.066847,0.074430,0.080827,0.085767,0.090118,197,0.000185
Temperature (°C) [sea_water_potential_temperature]{300m},0.369913,0.372999,0.436836,0.448597,0.489530,0.512584,0.550975,0.577013,0.605226,0.623395,190,0.000211
Salinity (PSU) [sea_water_salinity]{300m},0.058626,0.059369,0.073153,0.074893,0.084313,0.087230,0.094886,0.098035,0.103474,0.105729,190,0.000211
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.030382,0.035480,0.042305,0.048622,0.055717,0.062862,0.069833,0.076151,0.080523,0.084562,190,0.000211
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.030397,0.035052,0.042203,0.048039,0.054997,0.061826,0.068946,0.074981,0.079709,0.083997,190,0.000211
Temperature (°C) [sea_water_potential_temperature]{500m},0.242980,0.248431,0.300278,0.310821,0.356933,0.373167,0.414445,0.432214,0.461307,0.472723,157,0.000197
Salinity (PSU) [sea_water_salinity]{500m},0.044216,0.044429,0.056234,0.057069,0.065543,0.067076,0.073712,0.075445,0.080202,0.081455,157,0.000197
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.026695,0.030944,0.037302,0.042811,0.048891,0.055098,0.061224,0.066846,0.071076,0.074785,158,0.000199
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.026275,0.030472,0.037020,0.042218,0.048129,0.053964,0.060083,0.065340,0.069484,0.073356,158,0.000199

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},30.108145,30.977794,33.043268,34.024083,36.051266,36.86713,39.256195,40.284369,41.593263,42.525078,0,0.0

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.138883,0.149742,0.187350,0.197719,0.227837,0.244162,0.268739,0.287717,0.305431,0.327065,3,0.000007
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.145312,0.158885,0.192484,0.207911,0.237197,0.253882,0.272128,0.298728,0.311330,0.340459,2,0.000004

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},4.769426,10.279914,16.329597,22.734585,29.573021,37.108879,45.205467,53.366142