In [1]:
import oceanbench

oceanbench.__version__

'0.4.0'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open GLONET forecast sample with xarray
from datetime import datetime
import xarray
from oceanbench.core.interpolate import interpolate_1_degree

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://s3.waw3-1.cloudferro.com/oceanbench-bucket/public/ml-forecast-outputs/glonet/20240103.zarr",
        "https://s3.waw3-1.cloudferro.com/oceanbench-bucket/public/ml-forecast-outputs/glonet/20240110.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
            datetime.fromisoformat("2024-01-10"),
        ]
    }
)
challenger_dataset = interpolate_1_degree(challenger_dataset)
challenger_dataset

<xarray.Dataset> Size: 823MB
Dimensions:                          (first_day_datetime: 2,
                                      lead_day_index: 10, depth: 21,
                                      latitude: 168, longitude: 360)
Coordinates:
  * depth                            (depth) float32 84B 0.494 ... 5.275e+03
  * lead_day_index                   (lead_day_index) int64 80B 0 1 2 ... 7 8 9
  * first_day_datetime               (first_day_datetime) datetime64[us] 16B ...
  * latitude                         (latitude) float64 1kB -77.5 -76.5 ... 89.5
  * longitude                        (longitude) float64 3kB -179.5 ... 179.5
Data variables:
    sea_water_salinity               (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 203MB dask.array<chunksize=(1, 2, 1, 168, 360), meta=np.ndarray>
    sea_water_potential_temperature  (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 203MB dask.array<chunksize=(1, 2, 1, 168, 360), meta=np.ndarray>
    eastward_sea_water_velocity      (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 203MB dask.array<chunksize=(1, 2, 1, 168, 360), meta=np.ndarray>
    northward_sea_water_velocity     (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 203MB dask.array<chunksize=(1, 2, 1, 168, 360), meta=np.ndarray>
    sea_surface_height_above_geoid   (first_day_datetime, lead_day_index, latitude, longitude) float64 10MB dask.array<chunksize=(1, 2, 168, 360), meta=np.ndarray>
Attributes:
    Conventions:              CF-1.8
    area:                     Global
    challenger:               glonet
    contact:                  glonet@mercator-ocean.eu
    forecast_reference_time:  2024-01-02
    institution:              Mercator Ocean International
    references:               www.edito.eu
    source:                   MOI GLONET
    title:                    Daily mean fields from GLONET 1/4 degree resolu...

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.074619,0.076040,0.076083,0.077714,0.080757,0.083328,0.085179,0.088381,0.090385,0.092795
Temperature (°C) [sea_water_potential_temperature]{surface},0.652528,0.653926,0.698583,0.700048,0.755007,0.769546,0.826720,0.842075,0.882379,0.893457
Salinity (PSU) [sea_water_salinity]{surface},0.499407,0.500453,0.498298,0.496545,0.492931,0.491488,0.490539,0.486594,0.488562,0.486766
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.126199,0.128283,0.132071,0.132466,0.136287,0.137948,0.142672,0.144310,0.148866,0.148727
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.129152,0.131009,0.135246,0.136868,0.140484,0.141797,0.145982,0.147507,0.150640,0.152133
Temperature (°C) [sea_water_potential_temperature]{50m},1.015333,1.026076,1.050361,1.061644,1.093583,1.109044,1.151639,1.171199,1.211692,1.231885
Salinity (PSU) [sea_water_salinity]{50m},0.239840,0.240978,0.243237,0.244817,0.247540,0.249796,0.254122,0.256705,0.261012,0.262946
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.116580,0.117145,0.117022,0.117885,0.119597,0.121646,0.124900,0.127665,0.130423,0.131235
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.119282,0.119655,0.119588,0.120952,0.122718,0.124807,0.127573,0.130039,0.132855,0.134830
Temperature (°C) [sea_water_potential_temperature]{100m},1.144652,1.155714,1.162067,1.170667,1.188752,1.197131,1.222995,1.232723,1.261100,1.272121
Salinity (PSU) [sea_water_salinity]{100m},0.191754,0.192528,0.191360,0.192643,0.193588,0.194946,0.197664,0.199727,0.202572,0.204019
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.115183,0.115403,0.114703,0.115372,0.116036,0.117877,0.120307,0.122672,0.124196,0.125504
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.123082,0.123225,0.122487,0.122694,0.124027,0.125522,0.126692,0.128365,0.130287,0.131541
Temperature (°C) [sea_water_potential_temperature]{200m},0.890901,0.895532,0.908902,0.913137,0.919519,0.928257,0.935038,0.953204,0.961626,0.977164
Salinity (PSU) [sea_water_salinity]{200m},0.154964,0.155454,0.155561,0.155747,0.156421,0.156945,0.158292,0.159329,0.160705,0.161252
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.115234,0.115165,0.113671,0.113856,0.113806,0.114501,0.115447,0.116437,0.117370,0.117927
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.121309,0.120924,0.119132,0.119050,0.119229,0.119544,0.119767,0.120301,0.120815,0.120689
Temperature (°C) [sea_water_potential_temperature]{300m},0.750025,0.748564,0.755133,0.755957,0.754630,0.757930,0.759169,0.769089,0.772835,0.781045
Salinity (PSU) [sea_water_salinity]{300m},0.126805,0.126900,0.126468,0.126565,0.126456,0.126827,0.127144,0.128174,0.128877,0.129814
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.111826,0.111717,0.109974,0.110087,0.110053,0.110535,0.111326,0.111929,0.112570,0.112933
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.115481,0.115177,0.113337,0.113242,0.113269,0.113787,0.113977,0.114227,0.114461,0.114364
Temperature (°C) [sea_water_potential_temperature]{500m},0.562832,0.565969,0.553682,0.558912,0.555220,0.559865,0.564283,0.572129,0.577335,0.583570
Salinity (PSU) [sea_water_salinity]{500m},0.095556,0.095771,0.094893,0.095325,0.094812,0.095288,0.095620,0.096367,0.096781,0.097656
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.101695,0.101865,0.100302,0.100133,0.099879,0.100069,0.100450,0.100378,0.100718,0.100684
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.105540,0.105439,0.103481,0.103418,0.103196,0.103322,0.103504,0.103734,0.103811,0.103919

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},44.358207,44.304271,45.045022,45.222902,46.781342,47.391172,48.558569,49.437008,50.383396,50.768032

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.062093,0.064058,0.067475,0.071041,0.073152,0.077679,0.080788,0.086489,0.087223,0.093512
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.062399,0.067909,0.071857,0.075772,0.077386,0.081425,0.087309,0.091385,0.093637,0.099748

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Temperature (°C) [sea_water_potential_temperature]{surface},0.740377,0.829552,0.823272,0.796854,0.797869,0.823776,0.888996,0.912615,0.967003,0.891948
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.624492,0.620448,0.684111,0.632325,0.641032,0.750998,0.820515,0.828752,0.812411,0.888377
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.911723,1.082018,1.041187,1.007146,1.113241,1.004200,1.039810,1.263613,1.085817,1.292335
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.933362,0.948271,0.864101,0.889127,0.839232,0.940400,0.996264,0.965732,0.919232,0.975473
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.535094,0.549522,0.520502,0.508881,0.498371,0.574513,0.603877,0.561134,0.509138,0.596548
Salinity (PSU) [sea_water_salinity]{0-5m},0.220809,0.195206,0.222592,0.280205,0.227698,0.226738,0.215709,0.239103,0.232819,0.257623
Salinity (PSU) [sea_water_salinity]{5-100m},0.190362,0.175902,0.197807,0.175506,0.197721,0.215337,0.222479,0.199656,0.199856,0.214708
Salinity (PSU) [sea_water_salinity]{100-300m},0.124787,0.131037,0.118239,0.122506,0.114879,0.149576,0.143243,0.121583,0.125763,0.144141
Salinity (PSU) [sea_water_salinity]{300-600m},0.073906,0.081524,0.075358,0.072259,0.080508,0.083347,0.087264,0.089482,0.076631,0.084903
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.053243,0.053691,0.053663,0.055905,0.057143,0.060080,0.062214,0.063206,0.065084,0.068328
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.204774,0.209787,0.218436,0.214117,0.205141,0.211868,0.219013,0.223092,0.227681,0.223514
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.189282,0.190674,0.196456,0.192613,0.196973,0.201271,0.204669,0.208023,0.201874,0.194597

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},10.665209,19.712391,27.89444,35.468391,42.758453,50.028687,57.203995,64.212097

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.026430,0.030974,0.033858,0.038486,0.045447,0.050756,0.055267,0.061102,0.063445,0.066125
Temperature (°C) [sea_water_potential_temperature]{surface},0.421044,0.431532,0.531871,0.543678,0.630812,0.651927,0.728916,0.756919,0.807730,0.822519
Salinity (PSU) [sea_water_salinity]{surface},0.149047,0.154030,0.199788,0.205910,0.243846,0.251206,0.281096,0.287221,0.313373,0.314552
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.052394,0.071750,0.087206,0.097021,0.107578,0.116690,0.128887,0.135761,0.144139,0.147647
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.052766,0.072812,0.087617,0.099584,0.112085,0.121383,0.131710,0.139828,0.146375,0.150155
Temperature (°C) [sea_water_potential_temperature]{50m},0.720475,0.729012,0.790809,0.812893,0.887409,0.915507,0.992013,1.022422,1.088078,1.107961
Salinity (PSU) [sea_water_salinity]{50m},0.111815,0.112424,0.144095,0.146534,0.168451,0.171138,0.188092,0.192149,0.205398,0.207074
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.045584,0.056352,0.066237,0.073935,0.082868,0.090591,0.100209,0.108323,0.115206,0.119772
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.046822,0.057693,0.067950,0.076675,0.085579,0.094024,0.103028,0.110885,0.117134,0.122324
Temperature (°C) [sea_water_potential_temperature]{100m},0.560666,0.578323,0.659257,0.696238,0.788971,0.832615,0.917004,0.960005,1.016460,1.048971
Salinity (PSU) [sea_water_salinity]{100m},0.088303,0.089195,0.112534,0.115216,0.131745,0.134669,0.148227,0.151589,0.161094,0.162544
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.041391,0.049357,0.058644,0.065973,0.074597,0.083213,0.091624,0.099216,0.105304,0.109346
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.042314,0.050674,0.059832,0.067292,0.076375,0.084957,0.093215,0.100710,0.106696,0.111993
Temperature (°C) [sea_water_potential_temperature]{200m},0.420232,0.427802,0.499109,0.513991,0.564385,0.594452,0.642477,0.674840,0.706572,0.734199
Salinity (PSU) [sea_water_salinity]{200m},0.063574,0.063662,0.081797,0.082760,0.095797,0.098424,0.109242,0.111955,0.119128,0.121012
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.032986,0.039142,0.046427,0.053126,0.060577,0.067884,0.075287,0.082136,0.087406,0.091384
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.032665,0.038087,0.045892,0.051891,0.059775,0.067405,0.075058,0.081022,0.085840,0.090661
Temperature (°C) [sea_water_potential_temperature]{300m},0.360596,0.364379,0.425061,0.436001,0.475442,0.499343,0.540027,0.567814,0.593836,0.611261
Salinity (PSU) [sea_water_salinity]{300m},0.056228,0.056941,0.070000,0.071388,0.080352,0.083416,0.091130,0.094394,0.099159,0.101022
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.030394,0.035772,0.042473,0.049081,0.056181,0.063298,0.069956,0.076664,0.081354,0.085046
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.030076,0.034848,0.042032,0.048000,0.055183,0.062034,0.069175,0.074922,0.079310,0.083850
Temperature (°C) [sea_water_potential_temperature]{500m},0.233525,0.239531,0.289956,0.302122,0.346750,0.364389,0.404086,0.423508,0.451614,0.464799
Salinity (PSU) [sea_water_salinity]{500m},0.040848,0.041236,0.052282,0.053463,0.061255,0.062912,0.068970,0.070544,0.074994,0.076421
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.026971,0.031315,0.037525,0.042914,0.049317,0.055287,0.061266,0.067079,0.071688,0.075160
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.026028,0.030597,0.037062,0.042322,0.048420,0.054218,0.060134,0.065352,0.069424,0.073173

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},40.866022,40.842193,42.413561,42.315755,44.244415,44.906734,46.488266,47.098008,48.293673,48.522068

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.038970,0.044569,0.050035,0.055357,0.061494,0.067849,0.073952,0.081830,0.083576,0.090688
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.042321,0.051834,0.057439,0.061657,0.066364,0.073731,0.082687,0.088197,0.089351,0.096050

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},4.760081,9.889909,15.166114,20.51202,26.09532,32.166283,38.58498,45.154427