In [1]:
import oceanbench

oceanbench.__version__

'0.1.4'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open GLONET forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://minio.dive.edito.eu/project-oceanbench/public/glonet_full_2024/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 7GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 21,
                         lat: 672, lon: 1440)
Coordinates:
  * depth               (depth) float32 84B 0.494 47.37 ... 4.833e+03 5.275e+03
  * lat                 (lat) float64 5kB -78.0 -77.75 -77.5 ... 89.5 89.75
  * lon                 (lon) float64 12kB -180.0 -179.8 -179.5 ... 179.5 179.8
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, lat, lon) float64 77MB dask.array<chunksize=(1, 10, 672, 1440), meta=np.ndarray>
Attributes:
    regrid_method:  bilinear

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.072508,0.073793,0.072274,0.071717,0.075423,0.076346,0.078487,0.079753,0.083388,0.084716
Temperature (°C) [sea_water_potential_temperature]{surface},0.644376,0.654298,0.704421,0.705513,0.781977,0.784162,0.876273,0.867717,0.951849,0.935864
Salinity (PSU) [sea_water_salinity]{surface},0.587150,0.592865,0.594579,0.591613,0.587759,0.584523,0.584369,0.580064,0.580542,0.575022
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.133262,0.131148,0.131338,0.132587,0.134195,0.135218,0.138590,0.141328,0.148708,0.149896
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.133718,0.133030,0.134437,0.133772,0.138625,0.138477,0.142897,0.145530,0.148965,0.153766
Temperature (°C) [sea_water_potential_temperature]{50m},1.038822,1.054817,1.083074,1.100245,1.133195,1.176643,1.210009,1.276141,1.300240,1.374742
Salinity (PSU) [sea_water_salinity]{50m},0.245649,0.246552,0.250766,0.252910,0.257139,0.259692,0.264910,0.267383,0.272580,0.274699
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.116738,0.116750,0.115287,0.116010,0.115991,0.118284,0.121514,0.125818,0.127402,0.128510
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.118031,0.118195,0.118443,0.118963,0.119640,0.121946,0.125061,0.128676,0.131982,0.136178
Temperature (°C) [sea_water_potential_temperature]{100m},1.170650,1.173187,1.181395,1.188504,1.194070,1.215214,1.227693,1.266817,1.284110,1.339157
Salinity (PSU) [sea_water_salinity]{100m},0.195141,0.195321,0.194978,0.195981,0.197375,0.198488,0.200784,0.202517,0.205283,0.206751
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.115321,0.115262,0.113276,0.113816,0.113453,0.114562,0.116014,0.117594,0.118782,0.120367
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.122395,0.122878,0.121533,0.121606,0.121855,0.123537,0.125080,0.127192,0.128787,0.129866
Temperature (°C) [sea_water_potential_temperature]{200m},0.894274,0.897706,0.900258,0.905681,0.902057,0.910878,0.913648,0.926979,0.935823,0.952473
Salinity (PSU) [sea_water_salinity]{200m},0.156033,0.156365,0.156461,0.156873,0.157243,0.157927,0.159126,0.160166,0.161470,0.162815
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.114691,0.114603,0.112387,0.112491,0.111614,0.112197,0.112597,0.113671,0.114221,0.115021
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.120949,0.120618,0.119111,0.118999,0.119196,0.119605,0.120418,0.121299,0.121572,0.122239
Temperature (°C) [sea_water_potential_temperature]{300m},0.750386,0.750805,0.747883,0.747877,0.738754,0.741877,0.740228,0.748177,0.749874,0.758353
Salinity (PSU) [sea_water_salinity]{300m},0.128746,0.128804,0.128666,0.128424,0.128569,0.128598,0.129347,0.129591,0.130644,0.131099
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.110779,0.110785,0.108490,0.108635,0.107835,0.108296,0.108629,0.109549,0.109884,0.110298
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.115083,0.114939,0.112990,0.113018,0.112785,0.113082,0.113228,0.113776,0.113918,0.114559
Temperature (°C) [sea_water_potential_temperature]{500m},0.561666,0.564299,0.551568,0.553641,0.553319,0.555726,0.562436,0.565878,0.574238,0.577088
Salinity (PSU) [sea_water_salinity]{500m},0.097598,0.097587,0.097408,0.097373,0.098023,0.098197,0.099144,0.099515,0.100542,0.100966
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.101045,0.101155,0.098849,0.098682,0.097945,0.098043,0.098104,0.098476,0.098643,0.098974
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.105542,0.105473,0.103467,0.103395,0.103030,0.103094,0.103228,0.103687,0.103860,0.104201

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},33.672365,34.486002,36.438264,37.95073,40.502739,41.827043,43.322387,45.25351,45.923866,47.433723

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.168359,0.172381,0.200765,0.207841,0.233131,0.243173,0.260888,0.276450,0.290977,0.313693
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.166392,0.176187,0.204029,0.212550,0.234284,0.248062,0.262177,0.280982,0.293200,0.321107

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Temperature (°C) [sea_water_potential_temperature]{surface},0.653723,0.840537,0.816066,0.792433,0.770084,0.805132,0.894954,0.840426,0.949902,0.901058
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.529958,0.585966,0.642292,0.620779,0.719550,0.712913,0.955274,0.732739,0.890188,0.814080
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.920873,1.118656,0.899150,1.027676,1.128904,1.028957,1.091316,1.075099,1.267462,1.360519
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.827566,1.005783,0.802587,0.937222,0.940708,0.910415,0.898285,1.020846,0.978271,1.165690
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.542744,0.626948,0.479145,0.561024,0.513517,0.462351,0.499836,0.543888,0.534747,0.545642
Salinity (PSU) [sea_water_salinity]{0-5m},0.177553,0.238973,0.252509,0.355636,0.248247,0.173638,0.199230,0.254367,0.202174,0.231234
Salinity (PSU) [sea_water_salinity]{5-100m},0.161322,0.194053,0.205447,0.193984,0.205360,0.186330,0.199426,0.208044,0.195831,0.215112
Salinity (PSU) [sea_water_salinity]{100-300m},0.135474,0.160181,0.110913,0.138495,0.121915,0.120822,0.129178,0.126273,0.129274,0.155930
Salinity (PSU) [sea_water_salinity]{300-600m},0.085784,0.104984,0.079041,0.085178,0.081054,0.067675,0.077050,0.100706,0.080798,0.099444
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.105996,0.106557,0.106983,0.109211,0.109861,0.114117,0.112654,0.115962,0.114628,0.119753
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.197196,0.198873,0.210415,0.210080,0.202925,0.204013,0.217680,0.215999,0.226076,0.228620
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.182244,0.182107,0.195077,0.195816,0.195743,0.206738,0.207162,0.213871,0.208929,0.207087

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},11.025765,21.077646,30.589025,39.883808,49.011955,58.068447,66.960197,75.81778

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.023436,0.027196,0.027744,0.031401,0.039567,0.045390,0.050234,0.056914,0.059042,0.063144
Temperature (°C) [sea_water_potential_temperature]{surface},0.354226,0.377585,0.498732,0.512088,0.628488,0.649774,0.765273,0.768909,0.863407,0.860791
Salinity (PSU) [sea_water_salinity]{surface},0.116846,0.119722,0.186713,0.192016,0.237597,0.248516,0.280858,0.284334,0.310060,0.316567
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.073543,0.076574,0.077150,0.088212,0.096815,0.106992,0.117716,0.126975,0.138335,0.144005
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.071484,0.076598,0.080299,0.089328,0.101153,0.107965,0.118251,0.127879,0.135325,0.143489
Temperature (°C) [sea_water_potential_temperature]{50m},0.708563,0.712666,0.771330,0.802425,0.875232,0.924713,0.995884,1.065222,1.121981,1.193525
Salinity (PSU) [sea_water_salinity]{50m},0.098354,0.099882,0.140684,0.144780,0.169285,0.174501,0.192775,0.198267,0.211903,0.214770
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.053295,0.056231,0.061075,0.066462,0.072275,0.080709,0.090695,0.100317,0.106250,0.111344
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.051088,0.053735,0.061933,0.068176,0.074745,0.082078,0.091573,0.101438,0.109036,0.117217
Temperature (°C) [sea_water_potential_temperature]{100m},0.546387,0.553770,0.642098,0.675035,0.768546,0.825484,0.905428,0.979145,1.047712,1.115494
Salinity (PSU) [sea_water_salinity]{100m},0.077583,0.077878,0.107848,0.108997,0.129656,0.131867,0.148048,0.150271,0.161771,0.161712
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.047459,0.048458,0.053433,0.058388,0.065300,0.073088,0.080538,0.087038,0.092675,0.098142
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.044755,0.047060,0.054130,0.059486,0.065530,0.073652,0.083003,0.091368,0.098135,0.103511
Temperature (°C) [sea_water_potential_temperature]{200m},0.398879,0.403924,0.465960,0.485516,0.531692,0.565514,0.610130,0.647137,0.682641,0.716967
Salinity (PSU) [sea_water_salinity]{200m},0.052245,0.052523,0.074296,0.076097,0.090818,0.093898,0.105190,0.108590,0.116612,0.119407
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.036403,0.036791,0.041042,0.044822,0.050534,0.057427,0.064414,0.071394,0.076919,0.082287
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.034401,0.035105,0.040109,0.044060,0.049705,0.056405,0.063761,0.070643,0.075668,0.081078
Temperature (°C) [sea_water_potential_temperature]{300m},0.340866,0.344665,0.397276,0.410967,0.443947,0.471081,0.503471,0.536888,0.562893,0.591626
Salinity (PSU) [sea_water_salinity]{300m},0.051031,0.051633,0.066670,0.068370,0.078656,0.081590,0.089586,0.092803,0.098490,0.101014
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.032677,0.033140,0.037362,0.041129,0.046717,0.053038,0.059843,0.066390,0.071381,0.076308
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.031174,0.031441,0.036627,0.040488,0.046034,0.052355,0.059156,0.065708,0.070740,0.076239
Temperature (°C) [sea_water_potential_temperature]{500m},0.208455,0.209554,0.267273,0.275047,0.325082,0.339299,0.382543,0.400278,0.432389,0.445044
Salinity (PSU) [sea_water_salinity]{500m},0.038125,0.038217,0.051162,0.051955,0.061503,0.062963,0.070209,0.072009,0.077208,0.078715
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.027582,0.028244,0.032396,0.036309,0.041317,0.046851,0.052661,0.058507,0.063165,0.067527
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.026410,0.026449,0.031494,0.035201,0.040351,0.045664,0.051462,0.057125,0.061755,0.066614

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},31.073182,31.939416,34.852257,36.148963,39.197889,40.453818,42.511673,44.142417,44.973178,46.306992

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.131417,0.138867,0.176312,0.186658,0.213817,0.230366,0.251818,0.270900,0.286140,0.310813
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.134802,0.148871,0.180612,0.193206,0.219343,0.241523,0.256656,0.277364,0.291214,0.317834

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},4.829555,9.268334,13.830937,19.196039,25.309883,32.146145,39.463829,47.078434