In [1]:
import oceanbench

oceanbench.__version__

'0.1.4'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open GLONET forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://minio.dive.edito.eu/project-oceanbench/public/glonet_full_2024/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 7GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 21,
                         lat: 672, lon: 1440)
Coordinates:
  * depth               (depth) float32 84B 0.494 47.37 ... 4.833e+03 5.275e+03
  * lat                 (lat) float64 5kB -78.0 -77.75 -77.5 ... 89.5 89.75
  * lon                 (lon) float64 12kB -180.0 -179.8 -179.5 ... 179.5 179.8
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, lat, lon) float64 77MB dask.array<chunksize=(1, 10, 672, 1440), meta=np.ndarray>
Attributes:
    regrid_method:  bilinear

### Evaluation configuration

In [3]:
region = 'ibi'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.082931,0.075399,0.077091,0.072322,0.071704,0.078468,0.090398,0.086359,0.091556,0.090765
Temperature (°C) [sea_water_potential_temperature]{surface},0.521584,0.526720,0.549355,0.554782,0.616177,0.648212,0.723553,0.767323,0.819546,0.841416
Salinity (PSU) [sea_water_salinity]{surface},0.220093,0.218267,0.222187,0.231750,0.250310,0.259711,0.258374,0.268410,0.279761,0.287631
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.100583,0.103144,0.108263,0.107980,0.112002,0.106021,0.104172,0.108665,0.120731,0.122312
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.105418,0.100450,0.098116,0.093904,0.101813,0.111725,0.119409,0.132083,0.154868,0.166158
Temperature (°C) [sea_water_potential_temperature]{50m},0.809054,0.801153,0.873553,0.861000,0.946146,0.943406,1.028324,1.034296,1.112325,1.125167
Salinity (PSU) [sea_water_salinity]{50m},0.186056,0.184592,0.195805,0.195425,0.210289,0.210029,0.226787,0.225573,0.243217,0.240939
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.084957,0.085020,0.084073,0.084725,0.085020,0.085856,0.087312,0.087132,0.088709,0.088639
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.083033,0.082765,0.082694,0.083031,0.084373,0.084781,0.086736,0.088728,0.090692,0.091200
Temperature (°C) [sea_water_potential_temperature]{100m},0.821509,0.815949,0.861745,0.862239,0.905434,0.915987,0.954488,0.979478,1.015347,1.051154
Salinity (PSU) [sea_water_salinity]{100m},0.169804,0.168559,0.169377,0.170229,0.175482,0.176516,0.182749,0.183737,0.191541,0.192980
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.081055,0.081113,0.079519,0.079621,0.079123,0.079485,0.080184,0.080421,0.080451,0.080942
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.079797,0.079488,0.078431,0.079393,0.079770,0.080530,0.081577,0.082894,0.084375,0.085135
Temperature (°C) [sea_water_potential_temperature]{200m},0.722161,0.732685,0.749534,0.773193,0.757103,0.787031,0.770277,0.800302,0.786257,0.815098
Salinity (PSU) [sea_water_salinity]{200m},0.132583,0.132103,0.140205,0.140212,0.148985,0.149606,0.158628,0.159361,0.168327,0.168736
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.079545,0.078967,0.076775,0.076770,0.075785,0.075961,0.075552,0.075798,0.075519,0.075645
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.077152,0.076575,0.074542,0.074779,0.074417,0.075121,0.075399,0.076321,0.076719,0.077399
Temperature (°C) [sea_water_potential_temperature]{300m},0.651471,0.654995,0.665018,0.680162,0.649715,0.672581,0.644692,0.670002,0.649743,0.675785
Salinity (PSU) [sea_water_salinity]{300m},0.114266,0.113657,0.117005,0.116329,0.121865,0.121809,0.128613,0.128505,0.135832,0.136146
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.080707,0.080119,0.078230,0.077969,0.076985,0.076889,0.076301,0.076277,0.075655,0.075405
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.078634,0.077667,0.075645,0.075559,0.075060,0.075289,0.075374,0.075928,0.076186,0.076634
Temperature (°C) [sea_water_potential_temperature]{500m},0.434283,0.436503,0.435511,0.436449,0.460052,0.460491,0.488792,0.489265,0.518362,0.522729
Salinity (PSU) [sea_water_salinity]{500m},0.110894,0.110663,0.118552,0.118328,0.125557,0.125497,0.131739,0.131797,0.137312,0.137875
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.085356,0.084801,0.082854,0.082392,0.081301,0.080756,0.079923,0.079473,0.078594,0.078016
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.082809,0.081666,0.079267,0.078830,0.078068,0.077750,0.077632,0.077535,0.077641,0.077529

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},65.011551,64.653241,71.759847,76.037965,84.222065,90.460847,92.83202,100.094181,101.385551,108.121692

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.083187,0.080033,0.087518,0.088772,0.095629,0.099242,0.10263,0.103955,0.107945,0.108565
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.070915,0.066428,0.073567,0.072496,0.078630,0.080959,0.08555,0.087977,0.090352,0.091706

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [7]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},8.676305,15.901492,22.058809,28.028336,34.38245,41.02845,48.074253,56.475426

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [8]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.028824,0.033200,0.030080,0.033620,0.040604,0.056600,0.067161,0.068364,0.073465,0.076143
Temperature (°C) [sea_water_potential_temperature]{surface},0.235834,0.247487,0.351546,0.365074,0.483032,0.515212,0.627109,0.670779,0.742644,0.757686
Salinity (PSU) [sea_water_salinity]{surface},0.086930,0.087878,0.136140,0.146912,0.186456,0.180464,0.199227,0.202666,0.228593,0.236339
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.038523,0.054538,0.062281,0.067601,0.078122,0.078373,0.081134,0.091557,0.107314,0.109928
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.046716,0.047701,0.050090,0.057005,0.076348,0.090938,0.102190,0.117334,0.143229,0.156408
Temperature (°C) [sea_water_potential_temperature]{50m},0.721405,0.708395,0.801613,0.788734,0.884176,0.880291,0.971898,0.980891,1.065037,1.092173
Salinity (PSU) [sea_water_salinity]{50m},0.103372,0.102669,0.145730,0.146115,0.178336,0.178273,0.206977,0.204981,0.231494,0.227721
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.028377,0.029735,0.036938,0.043221,0.049542,0.056358,0.061643,0.066731,0.072072,0.076405
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.029048,0.029426,0.040794,0.045669,0.053663,0.058860,0.062313,0.066671,0.071202,0.075536
Temperature (°C) [sea_water_potential_temperature]{100m},0.485230,0.486547,0.615138,0.622919,0.710049,0.731214,0.801711,0.842742,0.890758,0.943119
Salinity (PSU) [sea_water_salinity]{100m},0.084166,0.084269,0.115229,0.117113,0.140308,0.141422,0.160458,0.161819,0.177337,0.178130
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.024966,0.025680,0.031666,0.035758,0.041699,0.047536,0.054064,0.059923,0.063796,0.068449
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.024949,0.025191,0.031845,0.038090,0.045128,0.050996,0.055158,0.058907,0.063645,0.068381
Temperature (°C) [sea_water_potential_temperature]{200m},0.357359,0.375409,0.448658,0.478098,0.501418,0.538041,0.555970,0.592564,0.606268,0.641826
Salinity (PSU) [sea_water_salinity]{200m},0.061189,0.061230,0.085046,0.084448,0.104665,0.105388,0.121935,0.122279,0.136051,0.137009
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.021024,0.021176,0.026329,0.030352,0.035486,0.040555,0.046022,0.051824,0.056825,0.061244
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.020647,0.021252,0.026628,0.030456,0.035801,0.040951,0.046317,0.052051,0.057077,0.062005
Temperature (°C) [sea_water_potential_temperature]{300m},0.374803,0.386339,0.445973,0.467250,0.464454,0.493224,0.494136,0.523863,0.527229,0.558740
Salinity (PSU) [sea_water_salinity]{300m},0.067507,0.068424,0.084836,0.084356,0.097109,0.097740,0.109628,0.110436,0.120865,0.122461
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.019739,0.019729,0.024663,0.028787,0.033496,0.038891,0.044154,0.049846,0.054686,0.059096
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.019978,0.020188,0.025516,0.029005,0.034318,0.039311,0.044927,0.050708,0.055548,0.060374
Temperature (°C) [sea_water_potential_temperature]{500m},0.197622,0.201497,0.277931,0.279167,0.349319,0.351310,0.406511,0.407013,0.452897,0.458719
Salinity (PSU) [sea_water_salinity]{500m},0.064282,0.064327,0.083666,0.083790,0.098069,0.098108,0.109427,0.109309,0.118353,0.118609
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.018646,0.018934,0.024004,0.027533,0.032431,0.037428,0.043584,0.049048,0.054444,0.058917
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.019032,0.019771,0.024874,0.028251,0.033265,0.038963,0.044614,0.049988,0.054582,0.059252

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},73.01044,72.357985,78.462574,82.556341,90.749875,97.099823,99.192825,107.166855,105.543145,113.15962

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.040062,0.040276,0.054697,0.061301,0.072779,0.081816,0.088224,0.092554,0.098631,0.101069
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.032709,0.031087,0.045607,0.048402,0.058616,0.064817,0.071977,0.076419,0.080800,0.084098

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [11]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},3.70703,6.932273,9.263941,12.354067,17.085289,22.573814,29.046593,37.333847

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [12]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Temperature (°C) [sea_water_potential_temperature]{surface},0.538235,0.295759,0.321741,0.273956,0.362181,0.385947,0.486383,0.386291,0.497540,0.419246
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.470342,0.318990,0.464795,0.144860,0.230605,0.337254,0.467296,0.919220,0.387408,0.471932
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.587657,0.750710,0.637427,0.331981,0.507031,0.560122,0.629864,1.001261,0.521970,0.620861
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.491050,0.660789,0.500922,0.463821,0.336756,0.456016,0.532396,0.365960,0.331495,0.445107
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.322109,0.470929,0.315114,0.369913,0.160067,0.332681,0.370678,0.342427,0.475414,0.339071
Salinity (PSU) [sea_water_salinity]{0-5m},0.199783,0.214400,0.183661,0.106491,0.115843,0.104244,0.331118,0.290888,0.023331,0.305176
Salinity (PSU) [sea_water_salinity]{5-100m},0.163657,0.200966,0.186328,0.121027,0.214313,0.178143,0.303473,0.239286,0.068933,0.356576
Salinity (PSU) [sea_water_salinity]{100-300m},0.085237,0.141240,0.085403,0.083148,0.093648,0.106872,0.136859,0.123375,0.093610,0.188765
Salinity (PSU) [sea_water_salinity]{300-600m},0.052182,0.064961,0.052587,0.048973,0.062692,0.062057,0.062738,0.081528,0.105407,0.164127
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.096641,0.103475,0.102840,0.115113,0.117344,0.122606,0.122871,0.129750,0.130452,0.131100
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.148238,0.140563,0.110060,0.143571,0.141246,0.155677,0.138128,0.158412,0.183855,0.189312
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.120630,0.135613,0.136560,0.141963,0.161357,0.147352,0.127864,0.127341,0.146883,0.145942