In [1]:
import oceanbench

oceanbench.__version__

'0.0.2'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open GLONET forecast sample with xarray
from datetime import datetime
import xarray
from oceanbench.core.interpolate import interpolate_1deg

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://minio.dive.edito.eu/project-oceanbench/public/glonet_full_2024/20240103.zarr",
        "https://minio.dive.edito.eu/project-oceanbench/public/glonet_full_2024/20240110.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
            datetime.fromisoformat("2024-01-10"),
        ]
    }
)

challenger_dataset

<xarray.Dataset> Size: 13GB
Dimensions:             (first_day_datetime: 2, lead_day_index: 10, depth: 21,
                         lat: 672, lon: 1440)
Coordinates:
  * depth               (depth) float32 84B 0.494 47.37 ... 4.833e+03 5.275e+03
  * lat                 (lat) float64 5kB -78.0 -77.75 -77.5 ... 89.5 89.75
  * lon                 (lon) float64 12kB -180.0 -179.8 -179.5 ... 179.5 179.8
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[ns] 16B 2024-01-03 20...
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 3GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, lat, lon) float64 3GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 3GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 3GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, lat, lon) float64 155MB dask.array<chunksize=(1, 10, 672, 1440), meta=np.ndarray>
Attributes:
    regrid_method:  bilinear

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [3]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Surface height,0.071096,0.072290,0.072302,0.073306,0.077480,0.078956,0.081981,0.083402,0.086615,0.087981
Surface temperature,0.638770,0.652999,0.692792,0.694646,0.756311,0.757222,0.828448,0.822397,0.894006,0.886419
Surface salinity,0.787755,0.788106,0.789416,0.787156,0.784376,0.779342,0.778374,0.776104,0.779887,0.775945
Surface northward velocity,0.123760,0.121703,0.122712,0.123263,0.125154,0.126226,0.129641,0.131836,0.136873,0.137310
Surface eastward velocity,0.124362,0.123734,0.125237,0.126048,0.129599,0.130045,0.134310,0.135426,0.138867,0.140028
50m temperature,0.962047,0.974890,0.997680,1.016632,1.050316,1.088725,1.127171,1.183793,1.213944,1.280224
50m salinity,0.350927,0.350059,0.358082,0.358304,0.363712,0.364644,0.369605,0.370942,0.375622,0.377686
50m northward velocity,0.108468,0.108318,0.106913,0.107720,0.108248,0.110337,0.112968,0.116609,0.118705,0.120220
50m eastward velocity,0.109790,0.109367,0.108964,0.109861,0.111090,0.113070,0.115855,0.119175,0.122217,0.125916
200m temperature,0.832741,0.838075,0.842132,0.847206,0.847170,0.856055,0.861434,0.874103,0.883540,0.897178
200m salinity,0.154083,0.154454,0.154587,0.154997,0.155490,0.156301,0.157346,0.158482,0.159554,0.160806
200m northward velocity,0.105627,0.105651,0.103790,0.103911,0.103437,0.104042,0.104560,0.105684,0.106138,0.106885
200m eastward velocity,0.110816,0.110542,0.108991,0.108946,0.108920,0.109423,0.110139,0.111180,0.111774,0.112668
550m temperature,0.527654,0.529625,0.518213,0.520483,0.520826,0.524076,0.530127,0.535043,0.543045,0.547744
550m salinity,0.090215,0.090165,0.090131,0.090045,0.090908,0.090984,0.092155,0.092441,0.093602,0.093958
550m northward velocity,0.093249,0.093293,0.091399,0.091342,0.090831,0.091023,0.091110,0.091548,0.091713,0.092066
550m eastward velocity,0.096918,0.096828,0.094973,0.094831,0.094423,0.094641,0.094876,0.095408,0.095686,0.096130

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth,38.100571,39.254677,41.239883,42.636391,45.0397,46.494843,47.829842,49.770035,50.630898,52.424095

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Northward geostrophic velocity,0.175311,0.167098,0.223145,0.214749,0.259953,0.255639,0.290566,0.293279,0.317458,0.327907
Eastward geostrophic velocity,0.145240,0.152701,0.179909,0.184255,0.205635,0.213182,0.228914,0.243071,0.253965,0.272756

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Surface Lagrangian trajectory deviation (km),9.935194,19.064002,27.739551,36.083315,44.174032,52.120537,59.873426,67.454872

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Surface height,0.023639,0.026894,0.028971,0.035024,0.043356,0.049321,0.054740,0.061040,0.063315,0.066557
Surface temperature,0.336712,0.371912,0.468191,0.489811,0.588592,0.610870,0.701858,0.714205,0.787591,0.796598
Surface salinity,0.125938,0.130575,0.191044,0.198945,0.245579,0.256637,0.290153,0.296017,0.323033,0.327686
Surface northward velocity,0.068534,0.070180,0.072092,0.082098,0.089263,0.098636,0.108360,0.116789,0.125809,0.131151
Surface eastward velocity,0.065109,0.069297,0.072828,0.082162,0.092091,0.100803,0.111375,0.119186,0.126140,0.130411
50m temperature,0.700414,0.706011,0.741918,0.767020,0.829630,0.874348,0.941700,1.006677,1.060761,1.127359
50m salinity,0.099265,0.101078,0.139562,0.143118,0.167541,0.171707,0.190129,0.194491,0.208739,0.211740
50m northward velocity,0.048602,0.050583,0.054830,0.059945,0.066264,0.074278,0.082992,0.091857,0.098130,0.103728
50m eastward velocity,0.046658,0.048056,0.054926,0.060690,0.068050,0.075309,0.084113,0.093428,0.101156,0.108831
200m temperature,0.395626,0.401149,0.453493,0.470998,0.508829,0.539690,0.577952,0.613014,0.644412,0.676692
200m salinity,0.050434,0.050729,0.069711,0.071305,0.084499,0.087343,0.097467,0.100686,0.107883,0.110596
200m northward velocity,0.033563,0.033975,0.037873,0.041703,0.047239,0.053816,0.060829,0.067714,0.073037,0.078204
200m eastward velocity,0.031980,0.032292,0.036911,0.040885,0.046321,0.052852,0.060039,0.066959,0.072148,0.077406
550m temperature,0.197530,0.198568,0.250960,0.257978,0.302803,0.316467,0.355724,0.372999,0.402195,0.415714
550m salinity,0.035412,0.035469,0.047386,0.048004,0.056787,0.058040,0.064712,0.066414,0.071158,0.072617
550m northward velocity,0.025717,0.026189,0.030198,0.033914,0.038958,0.044374,0.050214,0.055935,0.060475,0.064845
550m eastward velocity,0.024624,0.024814,0.029398,0.032978,0.037860,0.043236,0.048916,0.054647,0.059210,0.063787

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [8]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth,34.805443,36.207138,39.227291,40.726135,43.808136,45.12402,47.136238,48.789249,49.850784,51.309326

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLOR12 analysis

In [9]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Northward geostrophic velocity,0.146665,0.138087,0.204193,0.196516,0.245439,0.245375,0.283208,0.288370,0.312845,0.324439
Eastward geostrophic velocity,0.112575,0.124881,0.156277,0.164475,0.190124,0.203415,0.221878,0.238447,0.250977,0.269955

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [10]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(challenger_dataset)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Surface Lagrangian trajectory deviation (km),4.33519,8.391204,12.69758,17.588728,23.036142,29.176935,35.920792,43.013325