In [1]:
import oceanbench

oceanbench.__version__

'0.0.3'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open GLONET forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://minio.dive.edito.eu/project-oceanbench/public/glonet_full_2024/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 7GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 21,
                         lat: 672, lon: 1440)
Coordinates:
  * depth               (depth) float32 84B 0.494 47.37 ... 4.833e+03 5.275e+03
  * lat                 (lat) float64 5kB -78.0 -77.75 -77.5 ... 89.5 89.75
  * lon                 (lon) float64 12kB -180.0 -179.8 -179.5 ... 179.5 179.8
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, lat, lon) float64 2GB dask.array<chunksize=(1, 10, 1, 672, 1440), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, lat, lon) float64 77MB dask.array<chunksize=(1, 10, 672, 1440), meta=np.ndarray>
Attributes:
    regrid_method:  bilinear

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [3]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Surface height,0.071949,0.072820,0.071859,0.071713,0.075591,0.076677,0.079617,0.080744,0.083704,0.085077
Surface temperature,0.643190,0.653295,0.699534,0.704682,0.778674,0.781313,0.865711,0.857719,0.935456,0.922106
Surface salinity,0.779758,0.786507,0.791421,0.791442,0.786101,0.780013,0.779620,0.775254,0.776361,0.770886
Surface northward velocity,0.123386,0.121993,0.122560,0.123600,0.125149,0.125567,0.128422,0.130776,0.136783,0.138265
Surface eastward velocity,0.123278,0.123153,0.124322,0.123626,0.127766,0.127864,0.131795,0.133793,0.136874,0.140724
50m temperature,0.962817,0.975939,0.998999,1.014602,1.050895,1.087779,1.124381,1.180384,1.208465,1.271776
50m salinity,0.350439,0.349893,0.358027,0.358860,0.363867,0.365024,0.369743,0.371348,0.375701,0.377770
50m northward velocity,0.108858,0.108948,0.107519,0.108105,0.108173,0.110111,0.112814,0.116390,0.117726,0.118765
50m eastward velocity,0.109431,0.109573,0.109606,0.110109,0.110753,0.112754,0.115448,0.118505,0.121125,0.124500
100m temperature,1.066354,1.068717,1.078701,1.086469,1.095620,1.116014,1.130281,1.166214,1.183511,1.232845
100m salinity,0.245859,0.246112,0.248745,0.250301,0.252068,0.254047,0.255468,0.258381,0.259558,0.262984
100m northward velocity,0.107304,0.107369,0.105635,0.106071,0.105787,0.106861,0.108186,0.109766,0.110801,0.112184
100m eastward velocity,0.112346,0.112779,0.111607,0.111784,0.112027,0.113563,0.114980,0.116927,0.118297,0.119298
200m temperature,0.834070,0.837792,0.840552,0.845890,0.843568,0.852235,0.856268,0.868912,0.877954,0.892907
200m salinity,0.154016,0.154321,0.154285,0.154729,0.155080,0.155826,0.156829,0.157874,0.158982,0.160269
200m northward velocity,0.106041,0.106062,0.104114,0.104210,0.103493,0.104096,0.104595,0.105740,0.106279,0.107064
200m eastward velocity,0.110622,0.110397,0.109074,0.109086,0.109281,0.109776,0.110606,0.111582,0.111937,0.112592
300m temperature,0.707483,0.708772,0.707035,0.708113,0.699633,0.703979,0.702187,0.710766,0.712206,0.721090
300m salinity,0.120464,0.120536,0.120814,0.120710,0.121008,0.121221,0.121864,0.122297,0.123102,0.123760
300m northward velocity,0.102437,0.102518,0.100505,0.100624,0.099959,0.100437,0.100849,0.101825,0.102200,0.102666
300m eastward velocity,0.105606,0.105520,0.103831,0.103918,0.103765,0.104132,0.104420,0.105103,0.105349,0.105956
500m temperature,0.530362,0.532750,0.522252,0.524304,0.524913,0.527600,0.534301,0.538264,0.546361,0.549916
500m salinity,0.090571,0.090572,0.090550,0.090464,0.091281,0.091342,0.092467,0.092669,0.093878,0.094109
500m northward velocity,0.093467,0.093597,0.091576,0.091441,0.090824,0.090969,0.091128,0.091584,0.091788,0.092138
500m eastward velocity,0.096911,0.096864,0.095104,0.095055,0.094774,0.094900,0.095121,0.095643,0.095886,0.096219

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth,37.283077,38.392292,40.421261,42.064754,44.473385,45.723381,46.940174,48.822853,49.406933,50.871098

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Northward geostrophic velocity,0.177760,0.168298,0.221989,0.211756,0.256507,0.252707,0.285321,0.287670,0.310235,0.321718
Eastward geostrophic velocity,0.143302,0.151034,0.173844,0.180668,0.198779,0.209912,0.221779,0.237101,0.247389,0.270136

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(challenger_dataset)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Surface Lagrangian trajectory deviation (km),9.957029,19.147312,27.835867,36.084751,44.031246,51.805172,59.445488,66.990074

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Surface height,0.024599,0.028207,0.028630,0.032637,0.040971,0.046684,0.051873,0.058453,0.060212,0.064197
Surface temperature,0.344180,0.369278,0.471986,0.489345,0.599790,0.622251,0.729002,0.735666,0.821383,0.824426
Surface salinity,0.127618,0.131875,0.194849,0.201929,0.253200,0.263160,0.299412,0.300272,0.329962,0.336686
Surface northward velocity,0.066126,0.069352,0.070810,0.080814,0.088785,0.098111,0.107846,0.116502,0.126081,0.131697
Surface eastward velocity,0.064014,0.069443,0.072513,0.080662,0.091662,0.098541,0.108155,0.116531,0.123267,0.130397
50m temperature,0.702865,0.706803,0.741909,0.768134,0.831487,0.874532,0.938516,0.998735,1.050044,1.113377
50m salinity,0.099048,0.100994,0.139179,0.142658,0.166787,0.171278,0.189481,0.194346,0.208467,0.211197
50m northward velocity,0.048009,0.050362,0.054824,0.059816,0.065701,0.073485,0.082665,0.091306,0.096878,0.101768
50m eastward velocity,0.046179,0.048213,0.055407,0.061074,0.067372,0.074378,0.083125,0.092077,0.098817,0.106026
100m temperature,0.533589,0.538452,0.612355,0.637666,0.722872,0.770038,0.844513,0.906210,0.969325,1.027432
100m salinity,0.078230,0.078487,0.105442,0.105965,0.125535,0.127239,0.143134,0.144875,0.156660,0.156292
100m northward velocity,0.042860,0.043682,0.048258,0.052890,0.059451,0.066866,0.074068,0.080510,0.085916,0.091093
100m eastward velocity,0.040518,0.042406,0.048697,0.053690,0.059486,0.067191,0.075802,0.083688,0.089842,0.094980
200m temperature,0.396792,0.401487,0.452784,0.470327,0.507394,0.538626,0.575846,0.610421,0.640628,0.672385
200m salinity,0.050397,0.050662,0.069489,0.071178,0.084204,0.087161,0.097211,0.100484,0.107640,0.110342
200m northward velocity,0.033647,0.033974,0.037943,0.041654,0.047230,0.053900,0.060753,0.067573,0.072900,0.077997
200m eastward velocity,0.031935,0.032532,0.037134,0.041041,0.046518,0.053103,0.060200,0.066964,0.071847,0.077034
300m temperature,0.342714,0.347857,0.393575,0.407673,0.432679,0.459508,0.484083,0.516888,0.536879,0.565541
300m salinity,0.048829,0.049231,0.063610,0.065174,0.074518,0.077345,0.084295,0.087492,0.092255,0.094934
300m northward velocity,0.030394,0.030785,0.034742,0.038426,0.043864,0.050027,0.056665,0.063076,0.067957,0.072689
300m eastward velocity,0.029072,0.029352,0.034082,0.037913,0.043281,0.049475,0.056087,0.062506,0.067360,0.072567
500m temperature,0.197704,0.198758,0.251566,0.258722,0.304550,0.318125,0.358095,0.375201,0.405212,0.417687
500m salinity,0.035502,0.035557,0.047473,0.048154,0.056996,0.058286,0.065044,0.066666,0.071554,0.072902
500m northward velocity,0.025745,0.026309,0.030229,0.034013,0.038909,0.044318,0.050015,0.055686,0.060185,0.064363
500m eastward velocity,0.024709,0.024812,0.029465,0.033159,0.038125,0.043347,0.048992,0.054519,0.058954,0.063553

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [8]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth,34.251221,35.660194,38.487972,39.945652,42.876293,44.070759,45.909676,47.581657,48.368233,49.674484

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(challenger_dataset)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Northward geostrophic velocity,0.148859,0.139149,0.202781,0.193615,0.241477,0.241683,0.277509,0.282427,0.305651,0.318752
Eastward geostrophic velocity,0.112649,0.124144,0.150791,0.161401,0.183540,0.202152,0.215167,0.232550,0.244356,0.266440

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [10]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(challenger_dataset)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Surface Lagrangian trajectory deviation (km),4.27223,8.400319,12.726268,17.550304,22.861729,28.785055,35.255676,42.048706

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [11]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(challenger_dataset)

,Variable,Depth Range,Number of observations at lead day 1,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
0,temperature,0-5m,3508,0.592478,0.630840,0.665090,0.731709,0.700521,0.872455,0.767952,0.822948,0.836235,0.834227
1,temperature,5-100m,52474,1.107826,0.903215,1.034545,1.119183,1.011152,1.061821,1.074628,1.207565,1.308127,1.174148
2,temperature,100-300m,54597,1.033868,0.788003,0.925397,0.923131,0.902257,0.916716,1.011444,0.952111,1.160114,1.090411
3,temperature,300-600m,55498,0.631611,0.495254,0.553197,0.516818,0.464802,0.480890,0.542277,0.530109,0.531227,0.574376
4,temperature,Sea Surface Temperature,2897,0.867764,0.816412,0.838615,0.738229,0.825657,0.842056,0.879387,0.915239,0.920954,0.933862
5,salinity,0-5m,2726,0.233539,0.279709,0.360804,0.252956,0.171032,0.194950,0.240944,0.207599,0.224398,0.227951
6,salinity,5-100m,37692,0.192404,0.218760,0.196732,0.208689,0.186578,0.196581,0.203997,0.191906,0.217764,0.184705
7,salinity,100-300m,41514,0.161073,0.110118,0.142648,0.123717,0.122463,0.126777,0.125621,0.127092,0.159229,0.148825
8,salinity,300-600m,45710,0.103350,0.075756,0.085201,0.079818,0.070885,0.072757,0.101546,0.077800,0.099662,0.088910
9,sea level anomaly,surface,307732,0.106589,0.107000,0.106920,0.111085,0.111985,0.114212,0.112773,0.118001,0.116517,0.119907
10,eastward velocity,15m,26406,0.194236,0.208593,0.207896,0.200448,0.204617,0.217714,0.216680,0.226131,0.228528,0.226009
11,northward velocity,15m,26406,0.177510,0.191586,0.194584,0.194725,0.206133,0.204987,0.215947,0.209394,0.209605,0.201875