In [1]:
import oceanbench

oceanbench.__version__

'0.2.1'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open GLONET forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://s3.waw3-1.cloudferro.com/oceanbench-bucket/public/ml-forecast-outputs/glonet/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 7GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 21,
                         latitude: 672, longitude: 1440)
Coordinates:
  * depth               (depth) float32 84B 0.494 47.37 ... 4.833e+03 5.275e+03
  * latitude            (latitude) float64 5kB -78.0 -77.75 -77.5 ... 89.5 89.75
  * longitude           (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 2GB dask.array<chunksize=(1, 2, 3, 168, 360), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 2GB dask.array<chunksize=(1, 2, 3, 168, 360), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 2GB dask.array<chunksize=(1, 2, 3, 168, 360), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float64 2GB dask.array<chunksize=(1, 2, 3, 168, 360), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float64 77MB dask.array<chunksize=(1, 2, 168, 360), meta=np.ndarray>
Attributes:
    Conventions:              CF-1.8
    area:                     Global
    challenger:               glonet
    contact:                  glonet@mercator-ocean.eu
    forecast_reference_time:  2024-01-02
    institution:              Mercator Ocean International
    references:               www.edito.eu
    source:                   MOI GLONET
    title:                    Daily mean fields from GLONET 1/4 degree resolu...

### Evaluation configuration

In [3]:
region = 'ibi'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.083860,0.084732,0.084069,0.079361,0.077480,0.083405,0.093118,0.090670,0.095575,0.094305
Temperature (°C) [sea_water_potential_temperature]{surface},0.553061,0.562304,0.597940,0.617005,0.672536,0.709908,0.794987,0.835085,0.905755,0.926640
Salinity (PSU) [sea_water_salinity]{surface},0.224216,0.218398,0.228648,0.232494,0.255074,0.259974,0.263399,0.267302,0.283145,0.281199
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.097769,0.099002,0.107345,0.106395,0.107392,0.110581,0.107593,0.099711,0.103979,0.104503
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.098732,0.094708,0.096057,0.095332,0.110749,0.118031,0.117008,0.112852,0.122503,0.126587
Temperature (°C) [sea_water_potential_temperature]{50m},0.793181,0.793883,0.867346,0.870182,0.948285,0.955799,1.038280,1.049201,1.124821,1.135384
Salinity (PSU) [sea_water_salinity]{50m},0.190667,0.187493,0.205932,0.203680,0.224138,0.222101,0.244549,0.242239,0.265387,0.263247
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.087634,0.087684,0.087237,0.087986,0.088474,0.089662,0.090996,0.090434,0.090940,0.090669
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.085127,0.084779,0.084438,0.084593,0.086018,0.085679,0.087319,0.088366,0.090209,0.089886
Temperature (°C) [sea_water_potential_temperature]{100m},0.831611,0.823847,0.875816,0.867969,0.923292,0.915388,0.968000,0.966063,1.022297,1.024227
Salinity (PSU) [sea_water_salinity]{100m},0.172322,0.169659,0.173307,0.172079,0.181739,0.180521,0.191636,0.189960,0.202647,0.201376
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.083704,0.083845,0.082239,0.082318,0.082199,0.082739,0.083659,0.083526,0.083279,0.083284
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.081996,0.081295,0.080219,0.080890,0.081428,0.081817,0.082749,0.083591,0.084798,0.085200
Temperature (°C) [sea_water_potential_temperature]{200m},0.748825,0.742720,0.800633,0.797966,0.830859,0.833721,0.857872,0.862348,0.884415,0.888621
Salinity (PSU) [sea_water_salinity]{200m},0.134996,0.132892,0.144393,0.142279,0.154163,0.152638,0.164056,0.163146,0.174050,0.173164
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.081276,0.080675,0.078828,0.078703,0.077924,0.078105,0.077902,0.078102,0.077897,0.077815
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.079235,0.078410,0.076876,0.076839,0.076763,0.077148,0.077541,0.078043,0.078490,0.078608
Temperature (°C) [sea_water_potential_temperature]{300m},0.677553,0.668791,0.709718,0.707750,0.708057,0.713565,0.710151,0.718383,0.724174,0.731599
Salinity (PSU) [sea_water_salinity]{300m},0.115460,0.113576,0.118779,0.117608,0.124666,0.124493,0.132615,0.132497,0.141469,0.141709
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.082260,0.081737,0.080077,0.079830,0.079032,0.079016,0.078596,0.078579,0.078064,0.077598
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.081017,0.079991,0.078336,0.078006,0.077889,0.077745,0.078010,0.077982,0.078428,0.078227
Temperature (°C) [sea_water_potential_temperature]{500m},0.452773,0.448506,0.449710,0.448658,0.474440,0.473325,0.506191,0.502219,0.540615,0.534960
Salinity (PSU) [sea_water_salinity]{500m},0.114183,0.113017,0.122627,0.121760,0.130161,0.129693,0.137501,0.136869,0.144674,0.143924
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.086693,0.086227,0.084497,0.084130,0.083337,0.082836,0.082297,0.081930,0.081349,0.080699
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.084986,0.083950,0.081889,0.081429,0.080859,0.080586,0.080475,0.080202,0.080102,0.079805

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},62.52819,64.432331,69.61637,72.139181,78.897142,80.22836,89.305398,90.978632,98.945136,101.200721

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.085547,0.083735,0.090408,0.090839,0.095518,0.099707,0.101351,0.101136,0.103057,0.103760
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.072754,0.070185,0.075938,0.076103,0.080602,0.083623,0.087830,0.088021,0.089688,0.090316

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Temperature (°C) [sea_water_potential_temperature]{surface},0.549299,0.348158,0.376150,0.322310,0.398101,0.366825,0.520123,0.454627,0.558539,0.459529
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.501207,0.346511,0.429309,0.190871,0.331105,0.411921,0.500773,0.924419,0.368556,0.502053
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.652696,0.851972,0.774070,0.430563,0.667770,0.700915,0.602510,1.119336,0.691657,1.019681
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.495203,0.634021,0.488096,0.440319,0.445792,0.542864,0.535492,0.448677,0.527336,1.044834
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.341833,0.482924,0.349053,0.385772,0.221769,0.413630,0.342483,0.390250,0.768639,0.534585
Salinity (PSU) [sea_water_salinity]{0-5m},0.194935,0.213353,0.187585,0.113754,0.075188,0.103515,0.307991,0.266530,0.061529,0.341838
Salinity (PSU) [sea_water_salinity]{5-100m},0.169411,0.208049,0.174492,0.127242,0.208785,0.173233,0.321386,0.263099,0.082888,0.349249
Salinity (PSU) [sea_water_salinity]{100-300m},0.097146,0.147292,0.093105,0.099433,0.082200,0.123181,0.153705,0.138300,0.108302,0.205536
Salinity (PSU) [sea_water_salinity]{300-600m},0.051888,0.065263,0.056754,0.056705,0.045848,0.077147,0.063168,0.083355,0.080365,0.153021
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.046641,0.040875,0.040001,0.042795,0.039054,0.045148,0.043866,0.053597,0.049873,0.064362
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.147976,0.134836,0.118230,0.147872,0.143661,0.151469,0.131954,0.149302,0.166593,0.174003
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.122137,0.128725,0.138929,0.146114,0.158593,0.153209,0.135682,0.132281,0.149691,0.146767

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},8.367398,16.039761,23.378784,30.031338,36.177162,42.41906,48.982414,55.980824

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.040026,0.036188,0.036649,0.037810,0.042551,0.056163,0.062250,0.063595,0.071243,0.073047
Temperature (°C) [sea_water_potential_temperature]{surface},0.307160,0.327992,0.421466,0.450157,0.542557,0.585123,0.700234,0.744033,0.830581,0.851042
Salinity (PSU) [sea_water_salinity]{surface},0.102206,0.106392,0.149477,0.162096,0.191235,0.188472,0.204528,0.209939,0.232765,0.235263
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.038412,0.051864,0.069999,0.074815,0.081597,0.092613,0.092509,0.088441,0.095778,0.097331
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.041089,0.047753,0.056831,0.065750,0.092579,0.102450,0.104406,0.100885,0.114010,0.119454
Temperature (°C) [sea_water_potential_temperature]{50m},0.704807,0.705084,0.794928,0.801538,0.885024,0.897839,0.985081,1.002265,1.084515,1.106239
Salinity (PSU) [sea_water_salinity]{50m},0.114842,0.113444,0.158142,0.158025,0.192812,0.192772,0.224573,0.222889,0.252744,0.249913
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.031819,0.035638,0.043947,0.051389,0.057399,0.064382,0.068817,0.072557,0.075837,0.079800
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.031509,0.036892,0.047429,0.054048,0.061630,0.066250,0.069431,0.071849,0.075380,0.077913
Temperature (°C) [sea_water_potential_temperature]{100m},0.513242,0.520245,0.639606,0.649030,0.741431,0.753361,0.838958,0.855077,0.926861,0.945856
Salinity (PSU) [sea_water_salinity]{100m},0.093990,0.092479,0.122989,0.123852,0.148564,0.148938,0.170660,0.172112,0.190978,0.191453
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.028359,0.031584,0.037922,0.043055,0.049357,0.055320,0.061233,0.065907,0.068757,0.072190
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.027114,0.030993,0.038433,0.045676,0.052875,0.058647,0.062852,0.065830,0.070096,0.073449
Temperature (°C) [sea_water_potential_temperature]{200m},0.384075,0.391680,0.496583,0.506942,0.571352,0.588496,0.641945,0.660455,0.705019,0.721653
Salinity (PSU) [sea_water_salinity]{200m},0.066312,0.065454,0.090223,0.088951,0.110099,0.110517,0.128008,0.128316,0.143012,0.143951
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.023149,0.026538,0.032137,0.037095,0.042153,0.047036,0.052027,0.056805,0.060971,0.064423
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.022796,0.026055,0.032749,0.037754,0.043942,0.049236,0.054633,0.059616,0.063917,0.067300
Temperature (°C) [sea_water_potential_temperature]{300m},0.416544,0.415072,0.500195,0.507817,0.531999,0.547320,0.569032,0.586182,0.611718,0.627832
Salinity (PSU) [sea_water_salinity]{300m},0.071830,0.071375,0.088896,0.088603,0.101760,0.102848,0.115532,0.116527,0.128664,0.130095
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.021434,0.024612,0.030052,0.035171,0.039873,0.044978,0.049779,0.054685,0.058561,0.061863
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.021282,0.024332,0.030838,0.035632,0.041500,0.046651,0.052251,0.057338,0.061619,0.065051
Temperature (°C) [sea_water_potential_temperature]{500m},0.225621,0.228144,0.296867,0.300415,0.366481,0.370364,0.429732,0.427299,0.482829,0.477692
Salinity (PSU) [sea_water_salinity]{500m},0.068231,0.067704,0.088543,0.088670,0.103401,0.103645,0.116118,0.115859,0.126811,0.126225
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.020368,0.023733,0.029459,0.034080,0.039216,0.043928,0.049327,0.054095,0.058190,0.061528
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.020132,0.023830,0.029937,0.034376,0.039761,0.045549,0.051315,0.056401,0.060321,0.063893

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},72.225258,74.427157,76.478044,80.314538,83.436645,87.233153,94.850411,96.665007,103.006058,105.326218

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.044186,0.045346,0.059990,0.065832,0.075872,0.085422,0.089350,0.092807,0.096214,0.098645
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.037005,0.035839,0.049749,0.054314,0.063504,0.070021,0.076447,0.079060,0.082884,0.085152

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},3.354296,7.561906,12.192516,16.906376,22.118134,28.05024,34.343861,41.205933