In [1]:
import oceanbench

oceanbench.__version__

/homelocal/zaissa/.local/share/mamba/envs/oceanbench_test/lib/python3.13/site-packages/requests/__init__.py:92: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

'0.5.1'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open HClimRep forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://s3.waw3-1.cloudferro.com/oceanbench-bucket/public/ml-forecast-outputs/hclimrep/v2/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 1GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 9,
                         latitude: 672, longitude: 1440)
Coordinates:
  * depth               (depth) float64 72B 0.494 47.37 92.33 ... 453.9 541.1
  * latitude            (latitude) float64 5kB -78.0 -77.75 -77.5 ... 89.5 89.75
  * longitude           (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[ns] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 348MB dask.array<chunksize=(1, 1, 1, 672, 1440), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 348MB dask.array<chunksize=(1, 1, 1, 672, 1440), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 348MB dask.array<chunksize=(1, 1, 1, 672, 1440), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 348MB dask.array<chunksize=(1, 1, 1, 672, 1440), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 39MB dask.array<chunksize=(1, 1, 672, 1440), meta=np.ndarray>
Attributes:
    oceanbench_reference_depth_grid_rounding_decimals:  3
    oceanbench_reference_target_depths_m:               [0.494, 47.374, 92.32...
    source:                                             WeatherGenerator infe...
    title:                                              WeatherGenerator GLOR...

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing fraction
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.055117,0.054793,0.053439,0.052376,0.054479,0.055999,0.055283,0.056632,0.057615,0.058677,0.0
Temperature (°C) [sea_water_potential_temperature]{surface},0.573146,0.590380,0.601004,0.615712,0.623219,0.638042,0.661126,0.674482,0.677326,0.685842,0.0
Salinity (PSU) [sea_water_salinity]{surface},0.426739,0.426152,0.422333,0.417323,0.412870,0.409947,0.407375,0.402019,0.399180,0.397536,0.0
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.113272,0.114429,0.116049,0.116924,0.117663,0.118633,0.120580,0.123088,0.123021,0.123108,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.114303,0.116686,0.118176,0.119174,0.121200,0.123875,0.126159,0.128474,0.129324,0.132192,0.0
Temperature (°C) [sea_water_potential_temperature]{50m},0.803841,0.793263,0.783044,0.773640,0.763643,0.760141,0.763474,0.773191,0.775947,0.782551,0.0
Salinity (PSU) [sea_water_salinity]{50m},0.203765,0.200871,0.199573,0.198595,0.196991,0.196304,0.196493,0.196520,0.195856,0.195497,0.0
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.105882,0.105863,0.105953,0.105702,0.105696,0.106350,0.107498,0.108289,0.108495,0.108511,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.106906,0.107067,0.107076,0.106960,0.106892,0.107858,0.108819,0.110115,0.110516,0.110968,0.0
Temperature (°C) [sea_water_potential_temperature]{100m},0.971483,0.961583,0.951327,0.942760,0.934222,0.930789,0.930143,0.933110,0.936677,0.945930,0.0
Salinity (PSU) [sea_water_salinity]{100m},0.162535,0.160713,0.159378,0.158851,0.158633,0.158358,0.158416,0.158635,0.158511,0.158544,0.0
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.103647,0.102924,0.102520,0.102356,0.101703,0.101639,0.102445,0.103143,0.102919,0.103082,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.108839,0.107685,0.107027,0.106415,0.106438,0.106977,0.106750,0.106814,0.106728,0.106281,0.0
Temperature (°C) [sea_water_potential_temperature]{200m},0.730593,0.723847,0.717767,0.713315,0.708759,0.705179,0.705287,0.708941,0.712181,0.716324,0.0
Salinity (PSU) [sea_water_salinity]{200m},0.131358,0.129934,0.128994,0.128239,0.127367,0.126511,0.126228,0.125831,0.125355,0.125152,0.0
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.101885,0.101205,0.100726,0.100271,0.099603,0.098976,0.098936,0.098844,0.098438,0.098144,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.107584,0.106314,0.105799,0.105090,0.104683,0.104324,0.104278,0.104146,0.103642,0.103165,0.0
Temperature (°C) [sea_water_potential_temperature]{300m},0.613326,0.605531,0.599584,0.596638,0.593171,0.591322,0.593498,0.596625,0.596976,0.599060,0.0
Salinity (PSU) [sea_water_salinity]{300m},0.107561,0.106419,0.105331,0.104526,0.103621,0.102746,0.102233,0.101763,0.100974,0.100527,0.0
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.096978,0.096467,0.095945,0.095339,0.094633,0.093971,0.093793,0.093453,0.092925,0.092402,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.100812,0.099902,0.099571,0.099093,0.098782,0.098486,0.098266,0.097947,0.097481,0.097101,0.0
Temperature (°C) [sea_water_potential_temperature]{500m},0.477355,0.471660,0.467951,0.465277,0.461159,0.458211,0.457807,0.457861,0.456370,0.457132,0.0
Salinity (PSU) [sea_water_salinity]{500m},0.081840,0.080854,0.080008,0.079419,0.078737,0.078032,0.077486,0.076880,0.076042,0.075493,0.0
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.084799,0.084360,0.083839,0.083179,0.082577,0.081978,0.081730,0.081142,0.080582,0.080279,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.089472,0.088760,0.088291,0.087890,0.087540,0.086964,0.086641,0.086325,0.085867,0.085490,0.0

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing fraction
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},37.331416,37.586491,38.237437,38.809258,39.475039,39.938817,40.598248,41.599677,41.960573,42.444021,0.1

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing fraction
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.113106,0.111568,0.110801,0.110260,0.109821,0.109734,0.110346,0.110902,0.110828,0.111034,0.0
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.107573,0.105524,0.104783,0.104865,0.104735,0.104890,0.105874,0.106568,0.106748,0.107291,0.0

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Observations,Missing
Temperature (°C) [sea_water_potential_temperature]{surface},0.645740,0.814347,0.819014,0.794435,0.732144,0.766362,0.809652,0.804159,0.850751,0.828721,3003,0
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.563074,0.589030,0.607200,0.598053,0.678682,0.637243,0.801435,0.695530,0.697686,0.737179,3784,0
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.915288,1.049919,0.789206,0.918374,0.971269,0.915091,0.945677,0.932531,1.052565,1.140600,55628,0
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.847156,0.945143,0.767454,0.909134,0.856172,0.821383,0.896466,0.998356,0.878036,0.983917,49367,0
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.542651,0.558149,0.489017,0.534470,0.503711,0.473426,0.492499,0.545922,0.530765,0.531666,48406,0
Salinity (PSU) [sea_water_salinity]{0-5m},0.172065,0.201012,0.214333,0.336096,0.202674,0.169204,0.177789,0.213334,0.166496,0.207661,3334,0
Salinity (PSU) [sea_water_salinity]{5-100m},0.157074,0.197763,0.213740,0.204259,0.207501,0.165750,0.210142,0.200219,0.183807,0.207901,44699,0
Salinity (PSU) [sea_water_salinity]{100-300m},0.126372,0.137486,0.100416,0.129573,0.117857,0.108055,0.128369,0.117845,0.123988,0.144272,40755,0
Salinity (PSU) [sea_water_salinity]{300-600m},0.076280,0.086680,0.070629,0.078370,0.074764,0.066234,0.063270,0.079726,0.076951,0.086634,41131,0
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.058381,0.059215,0.061151,0.063116,0.065087,0.068894,0.068290,0.068994,0.070272,0.071542,298130,0
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.103903,0.104688,0.115524,0.124412,0.121152,0.118175,0.122046,0.122558,0.124710,0.127562,22829,0
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.108718,0.103947,0.106140,0.114517,0.117862,0.127883,0.125369,0.118364,0.117859,0.119812,22829,0

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Lagrangian trajectory deviation (km) []{surface},9.802221,18.99552,27.815538,36.334183,44.727375,53.029926,61.103989,68.863731,76.316811

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing fraction
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.041476,0.044899,0.047805,0.048804,0.054042,0.057487,0.059547,0.062202,0.063782,0.064774,0.0
Temperature (°C) [sea_water_potential_temperature]{surface},0.464190,0.477808,0.498853,0.522473,0.539305,0.566223,0.599353,0.625040,0.636395,0.653972,0.0
Salinity (PSU) [sea_water_salinity]{surface},0.377515,0.388254,0.398926,0.406882,0.417152,0.432513,0.443102,0.451293,0.460473,0.469513,0.0
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.074295,0.082801,0.091236,0.096496,0.102912,0.108243,0.115253,0.121730,0.124037,0.126560,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.077068,0.086757,0.094170,0.100663,0.107117,0.114266,0.120072,0.126281,0.129534,0.132785,0.0
Temperature (°C) [sea_water_potential_temperature]{50m},0.591772,0.609367,0.631719,0.654525,0.687415,0.718150,0.754261,0.785374,0.805403,0.817592,0.0
Salinity (PSU) [sea_water_salinity]{50m},0.154379,0.159984,0.163503,0.166830,0.171273,0.176636,0.181277,0.186307,0.189000,0.191060,0.0
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.066506,0.070397,0.075081,0.079529,0.084823,0.090619,0.097126,0.102326,0.105577,0.107101,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.068166,0.072302,0.076151,0.080959,0.085200,0.090392,0.096309,0.102164,0.104998,0.107419,0.0
Temperature (°C) [sea_water_potential_temperature]{100m},0.632279,0.646684,0.664559,0.685634,0.720905,0.754498,0.786059,0.823240,0.842838,0.858209,0.0
Salinity (PSU) [sea_water_salinity]{100m},0.119386,0.121256,0.122921,0.125091,0.128096,0.131601,0.135298,0.138960,0.140556,0.142189,0.0
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.066174,0.069062,0.072556,0.076877,0.081890,0.087188,0.092199,0.097203,0.099852,0.101750,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.067378,0.070185,0.073160,0.076912,0.081430,0.087037,0.092878,0.097555,0.100436,0.102732,0.0
Temperature (°C) [sea_water_potential_temperature]{200m},0.482838,0.486572,0.500062,0.519242,0.540659,0.564290,0.591613,0.616777,0.634207,0.647147,0.0
Salinity (PSU) [sea_water_salinity]{200m},0.083473,0.084727,0.086281,0.088684,0.091749,0.095167,0.099067,0.102689,0.105245,0.107421,0.0
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.061285,0.063746,0.066439,0.069969,0.073772,0.078144,0.082646,0.087300,0.090026,0.092330,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.060872,0.063239,0.065779,0.069136,0.073140,0.077594,0.082250,0.086753,0.089614,0.092081,0.0
Temperature (°C) [sea_water_potential_temperature]{300m},0.417206,0.427931,0.441399,0.456581,0.475628,0.495500,0.516655,0.535715,0.549129,0.559972,0.0
Salinity (PSU) [sea_water_salinity]{300m},0.071203,0.072485,0.074235,0.076425,0.078980,0.082016,0.085112,0.087911,0.089723,0.091395,0.0
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.059315,0.061398,0.063857,0.067244,0.071121,0.075433,0.079779,0.083934,0.086444,0.088539,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.059109,0.061245,0.063517,0.066677,0.070387,0.074563,0.078963,0.083060,0.085520,0.087715,0.0
Temperature (°C) [sea_water_potential_temperature]{500m},0.345494,0.349329,0.356034,0.365311,0.377948,0.393436,0.409539,0.424923,0.434566,0.442969,0.0
Salinity (PSU) [sea_water_salinity]{500m},0.056488,0.057000,0.057895,0.059075,0.060560,0.062342,0.064297,0.066197,0.067501,0.068743,0.0
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.059219,0.060748,0.062659,0.065237,0.068095,0.071428,0.074978,0.078518,0.080630,0.082344,0.0
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.058379,0.060089,0.062029,0.064468,0.067444,0.070622,0.074029,0.077232,0.079429,0.081330,0.0

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing fraction
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},36.855587,36.914559,37.378481,38.074091,38.581805,39.196614,40.069577,41.048964,41.47038,42.171155,0.0

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing fraction
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.091906,0.090856,0.091587,0.093019,0.094985,0.097948,0.101359,0.104611,0.106512,0.107778,0.0
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.086954,0.085486,0.085726,0.087029,0.088570,0.091438,0.094778,0.098122,0.099648,0.101621,0.0

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Lagrangian trajectory deviation (km) []{surface},6.496556,12.868965,19.327463,25.775967,32.387016,39.3078,46.341232,53.388138,60.322533