In [1]:
import oceanbench

oceanbench.__version__

'0.4.0'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open LangYa forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://s3.waw3-1.cloudferro.com/oceanbench-bucket/public/ml-forecast-outputs/langya/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(7)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 32GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 7, depth: 32,
                         latitude: 2040, longitude: 4320)
Coordinates:
  * depth               (depth) float32 128B 0.494 1.541 2.646 ... 453.9 541.1
  * latitude            (latitude) float64 16kB -80.0 -79.92 ... 89.83 89.92
  * longitude           (longitude) float64 35kB -180.0 -179.9 ... 179.8 179.9
  * lead_day_index      (lead_day_index) int64 56B 0 1 2 3 4 5 6
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 247MB dask.array<chunksize=(1, 1, 256, 512), meta=np.ndarray>
Attributes:
    Conventions:              CF-1.8
    challenger:               langya
    forecast_reference_time:  2024-01-02

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.071301,0.072630,0.070587,0.071139,0.073293,0.076838,0.079311
Temperature (°C) [sea_water_potential_temperature]{surface},0.638079,0.648775,0.626696,0.645852,0.660139,0.697972,0.772120
Salinity (PSU) [sea_water_salinity]{surface},0.641194,0.652574,0.654904,0.656548,0.657788,0.661120,0.662450
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.134069,0.133267,0.133216,0.133755,0.132753,0.140878,0.149294
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.138123,0.141483,0.139058,0.137628,0.139458,0.147773,0.157541
Temperature (°C) [sea_water_potential_temperature]{50m},0.994629,1.004828,0.986395,0.987603,0.991973,1.034178,1.075610
Salinity (PSU) [sea_water_salinity]{50m},0.259823,0.261102,0.261743,0.263043,0.264118,0.267792,0.270872
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.124388,0.122685,0.123614,0.122866,0.121599,0.129638,0.134737
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.124713,0.124185,0.125994,0.125815,0.125740,0.133746,0.138809
Temperature (°C) [sea_water_potential_temperature]{100m},1.177687,1.178090,1.178892,1.184877,1.183192,1.215055,1.237684
Salinity (PSU) [sea_water_salinity]{100m},0.205324,0.205294,0.205187,0.205592,0.206297,0.208045,0.209236
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.121674,0.119595,0.121458,0.121098,0.120048,0.126877,0.131067
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.127559,0.126690,0.127511,0.127114,0.126750,0.132775,0.136086
Temperature (°C) [sea_water_potential_temperature]{200m},0.880686,0.877926,0.880234,0.881536,0.881634,0.892237,0.901279
Salinity (PSU) [sea_water_salinity]{200m},0.163578,0.163554,0.163807,0.164114,0.164476,0.165418,0.166402
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.121756,0.120216,0.121669,0.121124,0.120075,0.123379,0.125016
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.127430,0.126378,0.128036,0.127095,0.126466,0.129708,0.131077
Temperature (°C) [sea_water_potential_temperature]{300m},0.751110,0.750685,0.752428,0.753255,0.754550,0.764724,0.772346
Salinity (PSU) [sea_water_salinity]{300m},0.139762,0.139751,0.139990,0.140181,0.140435,0.141197,0.141880
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.118004,0.116678,0.118127,0.117571,0.116555,0.119553,0.120693
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.121450,0.120456,0.122234,0.121476,0.120874,0.123531,0.124487
Temperature (°C) [sea_water_potential_temperature]{500m},0.583264,0.583165,0.584894,0.586213,0.587616,0.593790,0.599076
Salinity (PSU) [sea_water_salinity]{500m},0.111235,0.111244,0.111371,0.111482,0.111656,0.112071,0.112451
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.107226,0.106263,0.107405,0.106713,0.105863,0.108558,0.109595
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.111757,0.111026,0.112511,0.111874,0.111268,0.113102,0.113809

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},31.325623,30.033549,27.874177,28.973828,29.38172,29.508585,32.611755

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.174274,0.175724,0.167512,0.169522,0.171130,0.175377,0.184238
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.196275,0.194199,0.185916,0.190099,0.193057,0.195057,0.202424

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Temperature (°C) [sea_water_potential_temperature]{surface},0.736811,0.902096,0.872521,0.860243,0.774641,0.808732,0.869366
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.537091,0.570044,0.528467,0.589573,0.542085,0.584475,0.722523
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.817141,0.932769,0.702253,0.916557,0.864614,0.870028,0.910089
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.707087,0.959471,0.699283,0.881753,0.750734,0.779499,0.839114
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.516381,0.585346,0.494411,0.621473,0.546426,0.528155,0.530716
Salinity (PSU) [sea_water_salinity]{0-5m},0.173585,0.257087,0.282211,0.377973,0.236977,0.199168,0.169457
Salinity (PSU) [sea_water_salinity]{5-100m},0.163353,0.246878,0.210183,0.263328,0.273736,0.319501,0.282311
Salinity (PSU) [sea_water_salinity]{100-300m},0.137791,0.159318,0.114593,0.149611,0.117467,0.122788,0.141905
Salinity (PSU) [sea_water_salinity]{300-600m},0.089130,0.107298,0.083325,0.112996,0.089819,0.094902,0.086736
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.051402,0.052538,0.051017,0.053501,0.053697,0.060053,0.062182
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.208806,0.208560,0.223273,0.220389,0.208830,0.212970,0.224291
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.186543,0.192530,0.203114,0.204690,0.202575,0.214319,0.213060

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6
Lagrangian trajectory deviation (km) []{surface},12.469362,23.78054,34.16275,44.180214,53.899921

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.030840,0.033085,0.031341,0.034376,0.040779,0.048614,0.053852
Temperature (°C) [sea_water_potential_temperature]{surface},0.372725,0.420088,0.394988,0.446462,0.483611,0.556630,0.655146
Salinity (PSU) [sea_water_salinity]{surface},0.143840,0.183552,0.212257,0.237762,0.260579,0.282837,0.297918
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.104012,0.101974,0.092703,0.098941,0.104398,0.125458,0.142548
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.106914,0.110915,0.097750,0.102499,0.111599,0.130191,0.146071
Temperature (°C) [sea_water_potential_temperature]{50m},0.407126,0.479177,0.483473,0.541559,0.595853,0.687897,0.760870
Salinity (PSU) [sea_water_salinity]{50m},0.087455,0.109474,0.125346,0.139302,0.150997,0.164652,0.175336
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.086089,0.083711,0.075836,0.081374,0.086630,0.109246,0.123124
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.081662,0.081303,0.077503,0.083192,0.089751,0.108922,0.120106
Temperature (°C) [sea_water_potential_temperature]{100m},0.432956,0.506727,0.550180,0.618292,0.682045,0.785881,0.862962
Salinity (PSU) [sea_water_salinity]{100m},0.075038,0.092162,0.106101,0.118301,0.128873,0.140114,0.148303
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.076629,0.073721,0.069691,0.075942,0.082846,0.104365,0.115519
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.072973,0.074790,0.073829,0.080584,0.087308,0.103934,0.114097
Temperature (°C) [sea_water_potential_temperature]{200m},0.297156,0.350556,0.391674,0.444274,0.492559,0.564638,0.618400
Salinity (PSU) [sea_water_salinity]{200m},0.061132,0.073561,0.084527,0.094198,0.102515,0.111250,0.118306
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.064072,0.061352,0.057366,0.063969,0.070028,0.087950,0.098283
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.059235,0.059177,0.059255,0.064834,0.070843,0.085817,0.094355
Temperature (°C) [sea_water_potential_temperature]{300m},0.249589,0.297336,0.338652,0.385617,0.428930,0.488825,0.533208
Salinity (PSU) [sea_water_salinity]{300m},0.056529,0.066462,0.075577,0.083531,0.090406,0.097412,0.103135
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.058872,0.056594,0.053662,0.060199,0.066221,0.083370,0.093001
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.054864,0.054386,0.054623,0.060306,0.066278,0.079998,0.088163
Temperature (°C) [sea_water_potential_temperature]{500m},0.185899,0.229250,0.269605,0.309201,0.344109,0.388805,0.423693
Salinity (PSU) [sea_water_salinity]{500m},0.050761,0.057285,0.063701,0.069261,0.074031,0.078653,0.082656
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.049356,0.049500,0.049354,0.055856,0.061622,0.074699,0.082799
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.045917,0.047839,0.050347,0.055843,0.061395,0.072298,0.079348

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},26.662515,26.285093,23.489343,25.656545,26.438561,27.571612,30.841715

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.145432,0.153923,0.136895,0.146241,0.151569,0.164506,0.180016
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.174116,0.174553,0.162037,0.166993,0.177443,0.185528,0.196789

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6
Lagrangian trajectory deviation (km) []{surface},8.865746,15.910134,22.094305,28.65818,35.872025