In [1]:
import oceanbench

oceanbench.__version__

'0.2.1'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open WENHAI forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://s3.waw3-1.cloudferro.com/oceanbench-bucket/public/ml-forecast-outputs/wenhai/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 33GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 23,
                         latitude: 2041, longitude: 4320)
Coordinates:
  * depth               (depth) float32 92B 0.494 2.646 5.078 ... 541.1 643.6
  * latitude            (latitude) float32 8kB -80.0 -79.92 ... 89.92 90.0
  * longitude           (longitude) float32 17kB -180.0 -179.9 ... 179.8 179.9
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 353MB dask.array<chunksize=(1, 1, 256, 512), meta=np.ndarray>
Attributes:
    Conventions:              CF-1.8
    challenger:               wenhai
    forecast_reference_time:  2024-01-02

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.114567,0.113746,0.113306,0.113600,0.113692,0.113872,0.114561,0.115642,0.115696,0.116913
Temperature (°C) [sea_water_potential_temperature]{surface},0.673491,0.666563,0.663755,0.668014,0.672251,0.676267,0.676503,0.677266,0.686719,0.694241
Salinity (PSU) [sea_water_salinity]{surface},1.189766,1.189431,1.186998,1.184953,1.182470,1.180674,1.177436,1.173469,1.173681,1.172148
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.163230,0.162594,0.162545,0.163064,0.163548,0.164819,0.166312,0.167931,0.168751,0.170114
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.164581,0.164101,0.163714,0.164386,0.165287,0.166870,0.168997,0.171037,0.171504,0.174171
Temperature (°C) [sea_water_potential_temperature]{50m},0.924798,0.920198,0.919170,0.915280,0.915127,0.917063,0.919177,0.923686,0.925958,0.928797
Salinity (PSU) [sea_water_salinity]{50m},1.111644,1.110939,1.110438,1.109837,1.109293,1.108814,1.108524,1.108338,1.108029,1.107699
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.151770,0.151604,0.151591,0.151901,0.152037,0.152750,0.153879,0.154596,0.155504,0.156151
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.159175,0.158893,0.159140,0.159714,0.160317,0.161310,0.162330,0.163689,0.164467,0.165486
Temperature (°C) [sea_water_potential_temperature]{100m},1.055706,1.052365,1.049507,1.048003,1.046827,1.047611,1.050008,1.053025,1.059427,1.066686
Salinity (PSU) [sea_water_salinity]{100m},1.056016,1.055699,1.055517,1.055376,1.055173,1.055064,1.055076,1.055101,1.055073,1.054955
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.137227,0.136978,0.136826,0.136934,0.137023,0.137523,0.138445,0.139372,0.139692,0.140214
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.141414,0.141207,0.141253,0.141565,0.142134,0.142830,0.143472,0.144275,0.144901,0.145470
Temperature (°C) [sea_water_potential_temperature]{200m},0.847780,0.843855,0.841719,0.840255,0.838982,0.839823,0.843112,0.846190,0.848420,0.850279
Salinity (PSU) [sea_water_salinity]{200m},0.996913,0.996713,0.996605,0.996541,0.996496,0.996447,0.996428,0.996433,0.996451,0.996456
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.125261,0.124923,0.124493,0.124163,0.124001,0.124071,0.124600,0.125208,0.125384,0.125583
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.132382,0.131965,0.131663,0.131583,0.131930,0.132256,0.132670,0.133310,0.133687,0.133944
Temperature (°C) [sea_water_potential_temperature]{300m},0.716937,0.714623,0.712947,0.712859,0.713236,0.715036,0.718065,0.721407,0.723256,0.725767
Salinity (PSU) [sea_water_salinity]{300m},0.923859,0.923761,0.923717,0.923693,0.923670,0.923679,0.923678,0.923686,0.923674,0.923668
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.116705,0.116255,0.115787,0.115454,0.115385,0.115434,0.115832,0.116339,0.116450,0.116499
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.121720,0.121304,0.120917,0.120816,0.120999,0.121179,0.121496,0.121964,0.122275,0.122562
Temperature (°C) [sea_water_potential_temperature]{500m},0.540681,0.539007,0.537889,0.537309,0.537187,0.538368,0.540105,0.541849,0.542793,0.544271
Salinity (PSU) [sea_water_salinity]{500m},0.807592,0.807532,0.807480,0.807444,0.807412,0.807381,0.807370,0.807366,0.807344,0.807316
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.104056,0.103565,0.103060,0.102629,0.102412,0.102284,0.102448,0.102615,0.102599,0.102705
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.105518,0.104932,0.104553,0.104431,0.104420,0.104349,0.104520,0.104833,0.104989,0.105130

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},23.423288,25.411963,27.152802,28.984507,30.598585,31.903612,33.641197,35.264591,36.506405,37.546524

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},2.026182,2.026490,2.026793,2.028250,2.029023,2.030045,2.030873,2.032840,2.033983,2.036388
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},1.369768,1.369781,1.369972,1.371033,1.371097,1.370906,1.371527,1.371941,1.372193,1.372187

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Temperature (°C) [sea_water_potential_temperature]{surface},0.713922,0.940709,0.843074,0.791695,0.727875,0.767347,0.793974,0.777959,0.819239,0.779498
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.488565,0.473296,0.465594,0.527696,0.681199,0.598331,0.667727,0.609393,0.461688,0.603016
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.815482,0.861209,0.667814,0.876469,1.053531,0.854377,0.898323,0.839546,0.787801,0.982125
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.744748,0.906796,0.730967,0.846065,0.843341,0.813939,0.849173,0.914823,0.837617,1.017541
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.533826,0.604197,0.499960,0.631931,0.538357,0.505426,0.502579,0.595597,0.553773,0.633292
Salinity (PSU) [sea_water_salinity]{0-5m},0.165732,0.255944,0.288942,0.322430,0.213349,0.188515,0.198055,0.298511,0.193683,0.219721
Salinity (PSU) [sea_water_salinity]{5-100m},0.161216,0.245051,0.217392,0.235015,0.270819,0.286266,0.289837,0.240665,0.248507,0.321513
Salinity (PSU) [sea_water_salinity]{100-300m},0.155400,0.229373,0.168253,0.142806,0.209005,0.124683,0.146016,0.136246,0.293942,0.383437
Salinity (PSU) [sea_water_salinity]{300-600m},0.088902,0.142383,0.083792,0.112263,0.089303,0.168404,0.083210,0.101036,0.140865,0.401588
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.049270,0.049719,0.051315,0.053479,0.054360,0.057993,0.058777,0.062117,0.063055,0.066254
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.204215,0.205498,0.216193,0.220691,0.207914,0.208075,0.222194,0.227041,0.234158,0.238257
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.187370,0.188463,0.201205,0.206664,0.202321,0.215738,0.216128,0.219554,0.213913,0.218878

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},10.320161,20.025351,29.207161,37.933781,46.157825,53.937405,61.457596,68.841789

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.019577,0.025467,0.027994,0.032401,0.036640,0.039316,0.044672,0.049913,0.052458,0.054989
Temperature (°C) [sea_water_potential_temperature]{surface},0.162308,0.211788,0.252753,0.291044,0.328943,0.375010,0.416236,0.460029,0.493868,0.524039
Salinity (PSU) [sea_water_salinity]{surface},0.135400,0.168527,0.196523,0.226371,0.254339,0.277679,0.292575,0.306062,0.321106,0.339433
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.048547,0.056793,0.065646,0.074831,0.083156,0.092108,0.102096,0.110232,0.115792,0.121364
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.047545,0.058334,0.066815,0.075884,0.084423,0.093780,0.102735,0.113848,0.118951,0.124100
Temperature (°C) [sea_water_potential_temperature]{50m},0.201357,0.264621,0.313628,0.359992,0.403243,0.446811,0.491181,0.534418,0.564787,0.585938
Salinity (PSU) [sea_water_salinity]{50m},0.055096,0.072014,0.085336,0.096434,0.106569,0.117144,0.127207,0.137162,0.143723,0.148762
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.039026,0.048139,0.055589,0.063880,0.071793,0.080248,0.089105,0.096185,0.101312,0.105145
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.038504,0.048317,0.056249,0.063933,0.072069,0.081338,0.089656,0.097686,0.103255,0.107282
Temperature (°C) [sea_water_potential_temperature]{100m},0.231417,0.295075,0.347428,0.401199,0.456159,0.505805,0.560588,0.610387,0.634713,0.662933
Salinity (PSU) [sea_water_salinity]{100m},0.043786,0.058399,0.068942,0.077849,0.086702,0.095405,0.103695,0.111022,0.115649,0.119684
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.034117,0.042766,0.050006,0.057530,0.065983,0.074099,0.081728,0.088916,0.093374,0.097437
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.033686,0.042799,0.050351,0.058064,0.065998,0.074072,0.082207,0.089337,0.094011,0.097551
Temperature (°C) [sea_water_potential_temperature]{200m},0.171978,0.226051,0.269237,0.311345,0.353461,0.396207,0.438897,0.477368,0.502122,0.523129
Salinity (PSU) [sea_water_salinity]{200m},0.032790,0.043706,0.052265,0.059688,0.066556,0.073217,0.079770,0.085709,0.089866,0.093406
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.028271,0.036271,0.042809,0.049505,0.056273,0.063400,0.070458,0.077278,0.081666,0.085530
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.027083,0.035099,0.041825,0.048406,0.055426,0.062553,0.069430,0.075575,0.079716,0.083299
Temperature (°C) [sea_water_potential_temperature]{300m},0.146345,0.197476,0.238025,0.275310,0.312587,0.349677,0.387405,0.421277,0.442512,0.460363
Salinity (PSU) [sea_water_salinity]{300m},0.028461,0.038361,0.046154,0.052731,0.058794,0.064588,0.070241,0.075346,0.078929,0.082069
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.026088,0.034108,0.040578,0.047003,0.053538,0.060248,0.066893,0.073082,0.077130,0.080813
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.024973,0.032744,0.039260,0.045587,0.052135,0.058817,0.065365,0.071134,0.075153,0.078699
Temperature (°C) [sea_water_potential_temperature]{500m},0.118065,0.162826,0.197888,0.228443,0.256696,0.284312,0.312297,0.337797,0.354701,0.369586
Salinity (PSU) [sea_water_salinity]{500m},0.023642,0.031515,0.037783,0.042965,0.047499,0.051728,0.055799,0.059506,0.062290,0.064753
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.023323,0.031337,0.037892,0.043862,0.049528,0.055345,0.061047,0.066379,0.070074,0.073266
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.022211,0.030234,0.036622,0.042408,0.048165,0.053824,0.059446,0.064413,0.068045,0.071311

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},18.325052,23.74819,27.572657,30.908089,33.822559,36.280521,38.853527,40.767788,42.160561,43.344822

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.135103,0.210291,0.269050,0.329090,0.40701,0.463632,0.518733,0.576850,0.653358,0.725851
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.101201,0.129239,0.153585,0.176362,0.19335,0.209920,0.226648,0.244431,0.258947,0.275023

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},4.124032,8.291636,12.831923,17.85659,23.373438,29.459848,36.029953,42.898926