In [1]:
import oceanbench

oceanbench.__version__

'0.2.1'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open WENHAI forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://s3.waw3-1.cloudferro.com/oceanbench-bucket/public/ml-forecast-outputs/wenhai/v2/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 33GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 23,
                         latitude: 2041, longitude: 4320)
Coordinates:
  * depth               (depth) float32 92B 0.494 2.646 5.078 ... 541.1 643.6
  * latitude            (latitude) float32 8kB -80.0 -79.92 ... 89.92 90.0
  * longitude           (longitude) float32 17kB -180.0 -179.9 ... 179.8 179.9
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 353MB dask.array<chunksize=(1, 1, 256, 512), meta=np.ndarray>
Attributes:
    Conventions:              CF-1.8
    challenger:               wenhai
    forecast_reference_time:  2024-01-02

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.063074,0.062588,0.062365,0.062994,0.063905,0.064248,0.065230,0.067347,0.068070,0.069572
Temperature (°C) [sea_water_potential_temperature]{surface},0.596518,0.590913,0.588955,0.592873,0.595755,0.603625,0.608960,0.616724,0.629540,0.641536
Salinity (PSU) [sea_water_salinity]{surface},0.529601,0.532647,0.532889,0.532781,0.533042,0.535434,0.533859,0.530625,0.532641,0.533448
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.121165,0.120748,0.121158,0.122749,0.123791,0.125939,0.128582,0.131146,0.132814,0.134827
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.123259,0.123555,0.123887,0.125701,0.127919,0.130731,0.134664,0.138650,0.140116,0.144594
Temperature (°C) [sea_water_potential_temperature]{50m},0.829766,0.822409,0.820960,0.814201,0.813833,0.816272,0.818814,0.824758,0.827502,0.831484
Salinity (PSU) [sea_water_salinity]{50m},0.250516,0.249589,0.249408,0.248775,0.248336,0.248360,0.248519,0.249153,0.249463,0.250086
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.115582,0.115678,0.115878,0.116522,0.117048,0.118330,0.120149,0.121447,0.123154,0.124240
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.116719,0.116557,0.117278,0.118384,0.119610,0.121684,0.123512,0.126004,0.127567,0.129275
Temperature (°C) [sea_water_potential_temperature]{100m},1.034419,1.031377,1.028606,1.027336,1.026289,1.027745,1.031104,1.035405,1.045253,1.056112
Salinity (PSU) [sea_water_salinity]{100m},0.185750,0.184636,0.183861,0.183484,0.183338,0.183283,0.183419,0.183770,0.183919,0.184055
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.114192,0.113896,0.113859,0.114213,0.114484,0.115269,0.116608,0.117912,0.118413,0.119228
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.118494,0.118377,0.118615,0.119168,0.120069,0.121347,0.122270,0.123333,0.124276,0.125195
Temperature (°C) [sea_water_potential_temperature]{200m},0.819369,0.814304,0.811821,0.809898,0.808264,0.809317,0.813577,0.817351,0.820187,0.822486
Salinity (PSU) [sea_water_salinity]{200m},0.145347,0.144601,0.144041,0.143809,0.143697,0.143712,0.144145,0.144427,0.144582,0.144839
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.112649,0.112244,0.111731,0.111308,0.111082,0.111101,0.111741,0.112496,0.112693,0.112907
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.118779,0.118234,0.117845,0.117727,0.118187,0.118600,0.119086,0.119860,0.120353,0.120675
Temperature (°C) [sea_water_potential_temperature]{300m},0.695919,0.693035,0.690771,0.690688,0.691238,0.693472,0.697236,0.701080,0.703074,0.706187
Salinity (PSU) [sea_water_salinity]{300m},0.120473,0.119941,0.119544,0.119457,0.119464,0.119690,0.120069,0.120501,0.120656,0.120901
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.108312,0.107762,0.107170,0.106761,0.106682,0.106707,0.107173,0.107758,0.107834,0.107788
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.112566,0.112064,0.111588,0.111467,0.111736,0.111937,0.112235,0.112732,0.113076,0.113427
Temperature (°C) [sea_water_potential_temperature]{500m},0.521662,0.519478,0.518160,0.517427,0.517105,0.518522,0.520479,0.522282,0.523224,0.524907
Salinity (PSU) [sea_water_salinity]{500m},0.089821,0.089494,0.089288,0.089199,0.089191,0.089315,0.089458,0.089645,0.089775,0.089912
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.098523,0.097957,0.097342,0.096775,0.096464,0.096233,0.096373,0.096460,0.096389,0.096474
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.102344,0.101670,0.101217,0.101081,0.101056,0.100867,0.100974,0.101249,0.101354,0.101468

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},22.59539,24.948603,26.778231,28.74144,30.362265,31.572649,33.388588,35.141266,36.410656,37.550606

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.145851,0.159104,0.171761,0.183525,0.195941,0.208085,0.219375,0.231180,0.243398,0.254987
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.155376,0.170340,0.182543,0.196607,0.206560,0.217492,0.226314,0.241312,0.255623,0.270796

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Temperature (°C) [sea_water_potential_temperature]{surface},0.713922,0.923327,0.843074,0.791695,0.727274,0.746104,0.781491,0.758163,0.803268,0.779498
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.488565,0.473296,0.465594,0.527696,0.681199,0.598331,0.667727,0.609393,0.461688,0.603016
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.815507,0.861209,0.666708,0.876469,1.049318,0.854622,0.898323,0.839257,0.787801,0.982125
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.741224,0.905688,0.728761,0.846065,0.840496,0.813939,0.849313,0.914823,0.829048,0.965869
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.533826,0.603391,0.499960,0.631931,0.538359,0.500011,0.502617,0.595597,0.550438,0.566588
Salinity (PSU) [sea_water_salinity]{0-5m},0.165732,0.255944,0.288942,0.322430,0.213349,0.188515,0.198055,0.298511,0.193683,0.219721
Salinity (PSU) [sea_water_salinity]{5-100m},0.161223,0.245051,0.216494,0.235015,0.255924,0.283547,0.289837,0.240665,0.248507,0.321513
Salinity (PSU) [sea_water_salinity]{100-300m},0.140734,0.160294,0.121186,0.142806,0.138173,0.124675,0.144122,0.136246,0.128033,0.165001
Salinity (PSU) [sea_water_salinity]{300-600m},0.088902,0.106362,0.083792,0.112263,0.089103,0.079927,0.081994,0.101036,0.090888,0.106106
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.049270,0.049719,0.051315,0.053479,0.054360,0.057993,0.058777,0.062117,0.063055,0.066254
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.204215,0.205498,0.216054,0.216840,0.207685,0.208075,0.222195,0.226159,0.234158,0.238275
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.187370,0.188463,0.201072,0.203149,0.202186,0.215738,0.216130,0.219529,0.213913,0.218889

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},11.801975,23.029974,33.566608,43.733273,53.476604,62.895264,72.124825,81.024292

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.018209,0.023821,0.026342,0.030301,0.035000,0.038480,0.043973,0.049150,0.051675,0.053722
Temperature (°C) [sea_water_potential_temperature]{surface},0.171817,0.223361,0.266498,0.305059,0.343659,0.391896,0.435431,0.481109,0.516431,0.548105
Salinity (PSU) [sea_water_salinity]{surface},0.122405,0.153256,0.179084,0.205684,0.232498,0.254711,0.267707,0.281491,0.294742,0.309172
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.051633,0.061757,0.071259,0.081482,0.090686,0.099614,0.110368,0.118204,0.123889,0.129930
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.051261,0.063809,0.073535,0.083569,0.092270,0.102153,0.111878,0.124070,0.130108,0.135811
Temperature (°C) [sea_water_potential_temperature]{50m},0.224195,0.292445,0.345284,0.395345,0.441888,0.488478,0.536827,0.584169,0.617549,0.640662
Salinity (PSU) [sea_water_salinity]{50m},0.059574,0.076906,0.090826,0.102484,0.113348,0.124566,0.135306,0.145647,0.152314,0.157616
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.043137,0.053106,0.061030,0.069797,0.078052,0.087076,0.096459,0.104063,0.109665,0.113708
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.042741,0.053666,0.062193,0.070193,0.078746,0.088813,0.097748,0.106490,0.112728,0.117125
Temperature (°C) [sea_water_potential_temperature]{100m},0.260717,0.330015,0.387450,0.447490,0.508511,0.562486,0.623346,0.678763,0.704802,0.736847
Salinity (PSU) [sea_water_salinity]{100m},0.047458,0.062914,0.074243,0.083912,0.093356,0.102604,0.111453,0.119232,0.124116,0.128462
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.037516,0.046868,0.054503,0.062408,0.071378,0.079885,0.087792,0.095331,0.099984,0.104406
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.037214,0.047123,0.055096,0.063219,0.071467,0.079942,0.088591,0.096188,0.101257,0.105060
Temperature (°C) [sea_water_potential_temperature]{200m},0.190223,0.249687,0.296628,0.342086,0.387205,0.432895,0.478636,0.520087,0.547220,0.570330
Salinity (PSU) [sea_water_salinity]{200m},0.035961,0.048260,0.057829,0.066057,0.073573,0.080818,0.087927,0.094389,0.098975,0.102902
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.030659,0.039162,0.045886,0.052776,0.059651,0.066945,0.074194,0.081321,0.085912,0.090060
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.029331,0.037827,0.044745,0.051469,0.058662,0.065948,0.072993,0.079348,0.083723,0.087548
Temperature (°C) [sea_water_potential_temperature]{300m},0.160006,0.216451,0.260712,0.300832,0.340648,0.380011,0.419984,0.455938,0.478784,0.498187
Salinity (PSU) [sea_water_salinity]{300m},0.030858,0.042087,0.050836,0.058135,0.064803,0.071120,0.077243,0.082780,0.086711,0.090185
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.028151,0.036687,0.043362,0.049963,0.056648,0.063518,0.070339,0.076721,0.080901,0.084820
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.026903,0.035117,0.041820,0.048294,0.054977,0.061791,0.068502,0.074442,0.078699,0.082494
Temperature (°C) [sea_water_potential_temperature]{500m},0.128424,0.177663,0.216069,0.249161,0.279458,0.308826,0.338489,0.365474,0.383543,0.399544
Salinity (PSU) [sea_water_salinity]{500m},0.025337,0.034211,0.041242,0.047005,0.052003,0.056628,0.061050,0.065069,0.068120,0.070831
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.025106,0.033630,0.040483,0.046663,0.052447,0.058421,0.064288,0.069802,0.073650,0.077023
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.023827,0.032375,0.039008,0.044958,0.050847,0.056586,0.062339,0.067427,0.071257,0.074727

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},17.461185,22.792292,26.479723,29.761879,32.560734,34.826653,37.349609,39.251827,40.565754,41.764843

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.110682,0.143685,0.170066,0.194533,0.216603,0.236271,0.255639,0.274090,0.291155,0.309108
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.121007,0.154443,0.183485,0.210576,0.230549,0.250035,0.269728,0.290795,0.308111,0.327436

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},4.560298,9.382174,14.450933,20.091448,26.372082,33.215736,40.701576,48.603657