In [1]:
import oceanbench

oceanbench.__version__

'0.1.4'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open WENHAI forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://minio.dive.edito.eu/project-oceanbench/public/WENHAI/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 33GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 23,
                         latitude: 2041, longitude: 4320)
Coordinates:
  * depth               (depth) float32 92B 0.494 2.646 5.078 ... 541.1 643.6
  * latitude            (latitude) float32 8kB -80.0 -79.92 ... 89.92 90.0
  * longitude           (longitude) float32 17kB -180.0 -179.9 ... 179.8 179.9
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 353MB dask.array<chunksize=(1, 1, 75, 4320), meta=np.ndarray>

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.095649,0.097373,0.098589,0.099664,0.102468,0.104151,0.104527,0.106520,0.107790,0.109529
Temperature (°C) [sea_water_potential_temperature]{surface},0.724388,0.799886,0.891377,0.986291,1.069567,1.152726,1.238372,1.317715,1.378451,1.444118
Salinity (PSU) [sea_water_salinity]{surface},0.849413,0.854331,0.858332,0.860850,0.861318,0.861080,0.859737,0.856861,0.856577,0.856344
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.154348,0.159789,0.161313,0.163732,0.162241,0.160679,0.161857,0.163891,0.164235,0.165293
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.167476,0.170890,0.174545,0.177766,0.180760,0.185221,0.189532,0.196211,0.201461,0.207517
Temperature (°C) [sea_water_potential_temperature]{50m},1.041344,1.046160,1.064299,1.075715,1.091484,1.116958,1.135893,1.157924,1.182823,1.211235
Salinity (PSU) [sea_water_salinity]{50m},0.956696,0.956062,0.955902,0.955706,0.955523,0.955564,0.955663,0.955923,0.956129,0.956208
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.150541,0.152806,0.153421,0.153348,0.152438,0.152690,0.154125,0.156450,0.158532,0.159309
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.155939,0.158007,0.160909,0.163118,0.164952,0.168041,0.171026,0.174712,0.178676,0.183723
Temperature (°C) [sea_water_potential_temperature]{100m},1.183416,1.179010,1.179852,1.184935,1.185315,1.188206,1.198901,1.205895,1.215999,1.235062
Salinity (PSU) [sea_water_salinity]{100m},0.957714,0.957378,0.957236,0.957141,0.957032,0.956955,0.956973,0.957064,0.957175,0.957221
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.138275,0.138235,0.138347,0.139040,0.139793,0.141053,0.142527,0.143709,0.144582,0.145265
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.143412,0.143593,0.144291,0.145385,0.147347,0.150000,0.151785,0.153241,0.154708,0.156506
Temperature (°C) [sea_water_potential_temperature]{200m},0.932225,0.930480,0.931903,0.934192,0.934618,0.935661,0.940005,0.947490,0.956299,0.964672
Salinity (PSU) [sea_water_salinity]{200m},0.922125,0.921950,0.921873,0.921849,0.921839,0.921829,0.921871,0.921946,0.922044,0.922101
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.129662,0.129157,0.128739,0.128517,0.128399,0.128529,0.128987,0.129713,0.130026,0.130345
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.137947,0.137464,0.137206,0.137098,0.137706,0.138433,0.139404,0.140213,0.140530,0.140859
Temperature (°C) [sea_water_potential_temperature]{300m},0.783547,0.781024,0.779184,0.778892,0.778912,0.779822,0.782679,0.786457,0.788881,0.792187
Salinity (PSU) [sea_water_salinity]{300m},0.851688,0.851577,0.851542,0.851520,0.851486,0.851487,0.851482,0.851520,0.851536,0.851555
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.121695,0.121053,0.120597,0.120311,0.120286,0.120602,0.121151,0.121824,0.121860,0.121825
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.127501,0.127152,0.126872,0.126738,0.127067,0.127434,0.128050,0.128572,0.129095,0.129724
Temperature (°C) [sea_water_potential_temperature]{500m},0.586613,0.585178,0.584532,0.584301,0.584235,0.585358,0.587609,0.589889,0.591481,0.593850
Salinity (PSU) [sea_water_salinity]{500m},0.756545,0.756475,0.756414,0.756368,0.756334,0.756300,0.756293,0.756292,0.756273,0.756252
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.109353,0.108814,0.108270,0.107879,0.107794,0.107778,0.107907,0.108041,0.108063,0.108356
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.111964,0.111450,0.111129,0.111076,0.111280,0.111299,0.111726,0.112235,0.112646,0.112882

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},24.966555,28.8447,31.351419,33.323303,34.60833,35.882336,37.17366,38.879902,39.905064,40.79855

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},2.041288,2.032583,2.030893,2.030844,2.030876,2.029730,2.028476,2.028841,2.027921,2.027897
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},1.654460,1.654323,1.655936,1.658914,1.659747,1.660675,1.660620,1.661391,1.665095,1.666973

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Temperature (°C) [sea_water_potential_temperature]{surface},0.744561,1.019779,0.976960,0.992633,0.985264,1.054729,1.166081,1.191816,1.309185,1.343490
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.551884,0.598302,0.683347,0.792729,0.967361,0.953875,1.172024,1.117033,1.165487,1.390461
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.827625,0.878030,0.716015,0.954098,1.141653,0.956343,1.021732,0.987673,1.051696,1.298937
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.751283,0.900095,0.733265,0.884822,0.851363,0.836071,0.911364,0.983101,0.880844,1.067451
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.539476,0.597951,0.501310,0.638003,0.545424,0.502243,0.528942,0.613623,0.566229,0.649376
Salinity (PSU) [sea_water_salinity]{0-5m},0.173227,0.256134,0.287878,0.339115,0.207391,0.198353,0.183048,0.276465,0.199532,0.259788
Salinity (PSU) [sea_water_salinity]{5-100m},0.163574,0.241518,0.224023,0.242415,0.271854,0.284353,0.287863,0.239026,0.251600,0.331313
Salinity (PSU) [sea_water_salinity]{100-300m},0.155722,0.228113,0.167362,0.145394,0.210036,0.125319,0.148981,0.139096,0.294582,0.384471
Salinity (PSU) [sea_water_salinity]{300-600m},0.089586,0.142061,0.084127,0.113096,0.090780,0.168460,0.087327,0.104629,0.142287,0.403441
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.112790,0.113810,0.116079,0.116324,0.119228,0.121879,0.122273,0.122841,0.126113,0.128945
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.213261,0.211501,0.223802,0.227661,0.213987,0.215987,0.227918,0.229569,0.239065,0.241900
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.190450,0.193786,0.206008,0.212723,0.207199,0.218096,0.221638,0.224992,0.217579,0.223109

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},14.048012,27.69496,40.922947,53.938225,66.573647,78.80233,90.728737,102.554535

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.024454,0.033476,0.038371,0.040366,0.047745,0.052877,0.056414,0.061862,0.064890,0.066752
Temperature (°C) [sea_water_potential_temperature]{surface},0.254454,0.410512,0.547393,0.658815,0.759377,0.868808,0.977297,1.077047,1.154845,1.231619
Salinity (PSU) [sea_water_salinity]{surface},0.134238,0.182619,0.221882,0.254358,0.281109,0.304903,0.323236,0.336615,0.347154,0.358805
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.085331,0.106286,0.116957,0.125689,0.129531,0.131964,0.137790,0.144384,0.148725,0.154498
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.098455,0.114335,0.125811,0.137073,0.148012,0.158678,0.167461,0.180700,0.189950,0.197812
Temperature (°C) [sea_water_potential_temperature]{50m},0.236553,0.323076,0.400621,0.475437,0.542914,0.611840,0.671758,0.726761,0.776232,0.822058
Salinity (PSU) [sea_water_salinity]{50m},0.061704,0.082261,0.099941,0.115548,0.128861,0.141883,0.154001,0.165425,0.173157,0.179370
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.055678,0.070759,0.079615,0.086380,0.092206,0.099519,0.108367,0.117676,0.123673,0.127816
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.050379,0.065691,0.078492,0.089082,0.098556,0.109287,0.119112,0.128745,0.137678,0.146737
Temperature (°C) [sea_water_potential_temperature]{100m},0.271100,0.352900,0.427670,0.512237,0.594883,0.664279,0.735061,0.795632,0.832915,0.881295
Salinity (PSU) [sea_water_salinity]{100m},0.048410,0.065156,0.077582,0.088411,0.099068,0.109190,0.118667,0.127173,0.133005,0.138290
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.039478,0.050318,0.059222,0.067973,0.077841,0.087613,0.095520,0.102607,0.107635,0.111724
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.039044,0.050811,0.060607,0.070162,0.079789,0.090670,0.100412,0.107763,0.113241,0.118575
Temperature (°C) [sea_water_potential_temperature]{200m},0.193442,0.256781,0.307707,0.358067,0.406909,0.453771,0.501114,0.545092,0.576126,0.603962
Salinity (PSU) [sea_water_salinity]{200m},0.036347,0.049207,0.059278,0.068102,0.076106,0.083704,0.091158,0.098035,0.103089,0.107571
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.031685,0.040729,0.047929,0.055231,0.062401,0.069975,0.077243,0.084426,0.088983,0.093351
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.030179,0.039443,0.047011,0.054091,0.061441,0.069022,0.076247,0.082539,0.087177,0.091518
Temperature (°C) [sea_water_potential_temperature]{300m},0.162045,0.220929,0.267600,0.310416,0.352717,0.392665,0.433466,0.470725,0.495865,0.518182
Salinity (PSU) [sea_water_salinity]{300m},0.031100,0.042699,0.051813,0.059477,0.066474,0.072997,0.079314,0.085087,0.089316,0.093138
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.028736,0.037696,0.044823,0.051932,0.059089,0.066510,0.073422,0.080012,0.084128,0.087983
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.027589,0.036436,0.043700,0.050382,0.057258,0.064347,0.071327,0.077166,0.081668,0.085953
Temperature (°C) [sea_water_potential_temperature]{500m},0.129124,0.179711,0.219582,0.254486,0.286485,0.316819,0.347693,0.375729,0.394884,0.412602
Salinity (PSU) [sea_water_salinity]{500m},0.025365,0.034425,0.041637,0.047555,0.052740,0.057536,0.062133,0.066324,0.069537,0.072456
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.025475,0.034282,0.041244,0.047828,0.054007,0.060330,0.066214,0.071808,0.075860,0.079600
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.024235,0.033255,0.040273,0.046440,0.052740,0.058854,0.064984,0.070273,0.074318,0.077907

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},19.012514,25.409052,29.602776,32.869183,35.093502,37.103699,38.988968,40.983154,42.070423,42.893475

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.116242,0.155940,0.182070,0.207240,0.229865,0.253707,0.274507,0.294127,0.312946,0.330934
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.127822,0.167328,0.200083,0.230253,0.257849,0.280466,0.297453,0.319560,0.343970,0.361291

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},8.98187,18.327217,28.184872,38.69873,49.725872,61.188736,72.984055,85.221062