In [1]:
import oceanbench

oceanbench.__version__

'0.2.1'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open XIHE forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://s3.waw3-1.cloudferro.com/oceanbench-bucket/public/ml-forecast-outputs/xihe/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 33GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 23,
                         latitude: 2041, longitude: 4320)
Coordinates:
  * depth               (depth) float32 92B 0.494 2.646 5.078 ... 541.1 643.6
  * latitude            (latitude) float32 8kB -80.0 -79.92 ... 89.92 90.0
  * longitude           (longitude) float32 17kB -180.0 -179.9 ... 179.8 179.9
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 353MB dask.array<chunksize=(1, 1, 256, 512), meta=np.ndarray>
Attributes:
    Conventions:              CF-1.8
    challenger:               xihe
    forecast_reference_time:  2024-01-02

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.074845,0.078226,0.078273,0.079328,0.080730,0.084009,0.082910,0.084030,0.086707,0.087933
Temperature (°C) [sea_water_potential_temperature]{surface},0.760618,0.712530,0.732348,0.777289,0.743164,0.781566,0.753763,0.789440,0.861944,0.843050
Salinity (PSU) [sea_water_salinity]{surface},0.481498,0.479165,0.490044,0.487172,0.487445,0.476038,0.468558,0.467147,0.467973,0.462805
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.124498,0.122728,0.122907,0.122359,0.122118,0.122668,0.121911,0.124747,0.122868,0.123224
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.128554,0.124777,0.125075,0.124881,0.125162,0.125240,0.125764,0.129627,0.129829,0.131041
Temperature (°C) [sea_water_potential_temperature]{50m},0.861215,0.847301,0.851334,0.876289,0.867828,0.912450,0.841375,0.901182,0.944890,0.982444
Salinity (PSU) [sea_water_salinity]{50m},0.230824,0.231776,0.230561,0.229744,0.230467,0.230668,0.229014,0.231117,0.233639,0.237598
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.115511,0.112837,0.112198,0.110572,0.110450,0.110783,0.110280,0.110760,0.109840,0.109285
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.116519,0.113506,0.112996,0.112006,0.112132,0.111038,0.110031,0.111435,0.110401,0.110248
Temperature (°C) [sea_water_potential_temperature]{100m},0.973458,0.988363,1.006569,1.034257,1.027765,1.049493,1.018328,1.030717,1.065900,1.077246
Salinity (PSU) [sea_water_salinity]{100m},0.169311,0.167859,0.166631,0.166017,0.167567,0.166750,0.165671,0.167843,0.173223,0.172780
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.111783,0.108617,0.107746,0.105779,0.105122,0.104653,0.102761,0.103162,0.102341,0.102480
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.116263,0.112987,0.112044,0.109753,0.110265,0.109815,0.107442,0.108378,0.106470,0.105710
Temperature (°C) [sea_water_potential_temperature]{200m},0.809972,0.769711,0.793345,0.755219,0.784039,0.779270,0.779598,0.806656,0.788391,0.801728
Salinity (PSU) [sea_water_salinity]{200m},0.129350,0.129930,0.131107,0.127342,0.128409,0.128107,0.125445,0.126965,0.125127,0.127369
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.108148,0.111552,0.108929,0.104931,0.105488,0.105321,0.105012,0.105261,0.103718,0.102733
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.114038,0.117189,0.115002,0.111073,0.112419,0.112244,0.111239,0.111890,0.110627,0.109877
Temperature (°C) [sea_water_potential_temperature]{300m},0.680286,0.639130,0.660061,0.629228,0.656020,0.663598,0.647925,0.671119,0.660900,0.662706
Salinity (PSU) [sea_water_salinity]{300m},0.103539,0.104553,0.106925,0.102889,0.103218,0.103947,0.100097,0.102621,0.099850,0.103029
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.103753,0.107364,0.104914,0.101014,0.101575,0.101555,0.101192,0.101227,0.099725,0.098452
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.107780,0.110976,0.109113,0.105513,0.106829,0.106439,0.105885,0.105938,0.104474,0.103411
Temperature (°C) [sea_water_potential_temperature]{500m},0.492808,0.471428,0.480061,0.461153,0.484217,0.485459,0.477713,0.492384,0.487440,0.485509
Salinity (PSU) [sea_water_salinity]{500m},0.076155,0.078620,0.076885,0.076218,0.075420,0.076843,0.073929,0.075525,0.074255,0.075888
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.093928,0.097558,0.095474,0.091804,0.092158,0.092049,0.091598,0.091092,0.090016,0.089040
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.097434,0.101058,0.099320,0.095947,0.096783,0.096203,0.095646,0.095339,0.094381,0.093265

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},47.304234,44.749226,43.767494,46.567707,44.691463,45.007633,47.182007,48.179237,50.051903,45.181774

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.520286,0.524178,0.515565,0.514124,0.505828,0.502853,0.476839,0.515396,0.522236,0.522940
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.606376,0.623308,0.608838,0.581841,0.590445,0.595180,0.532493,0.589707,0.604394,0.615429

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Temperature (°C) [sea_water_potential_temperature]{surface},0.741355,0.908738,0.865696,0.847972,0.810354,0.826951,0.827013,0.834956,0.898482,0.840396
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.576101,0.559245,0.633050,0.629589,0.755294,0.676848,0.761319,0.686002,0.755640,0.735572
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.873355,0.913204,0.695967,0.906466,0.937284,0.889871,0.874672,0.855227,0.968127,0.964485
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.759975,0.896981,0.658968,0.824574,0.781745,0.773738,0.828583,0.889703,0.789496,0.860098
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.537345,0.567188,0.468341,0.510793,0.509536,0.450355,0.504964,0.554318,0.507940,0.523672
Salinity (PSU) [sea_water_salinity]{0-5m},0.177240,0.241851,0.323546,0.352724,0.300806,0.295328,0.194281,0.244148,0.212300,0.244797
Salinity (PSU) [sea_water_salinity]{5-100m},0.159591,0.237909,0.216318,0.247104,0.263397,0.246297,0.269406,0.210021,0.248537,0.283121
Salinity (PSU) [sea_water_salinity]{100-300m},0.133046,0.161950,0.108605,0.133036,0.125704,0.110860,0.129186,0.125854,0.132630,0.151042
Salinity (PSU) [sea_water_salinity]{300-600m},0.082920,0.097521,0.079296,0.086079,0.080843,0.071952,0.074622,0.088798,0.079163,0.095133
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.055014,0.054082,0.055643,0.059050,0.059836,0.063653,0.065153,0.066703,0.068095,0.069749
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.207445,0.206641,0.220292,0.217324,0.208305,0.207986,0.217890,0.217373,0.226218,0.229239
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.189789,0.191173,0.202773,0.203120,0.203675,0.215120,0.210140,0.210689,0.203883,0.206675

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},11.967701,23.11561,33.457157,43.068398,52.214531,61.163979,69.911926,78.375603

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.035287,0.041929,0.043649,0.045685,0.051858,0.056206,0.059231,0.062162,0.064615,0.065334
Temperature (°C) [sea_water_potential_temperature]{surface},0.486207,0.509350,0.531354,0.587518,0.591670,0.660346,0.644899,0.714586,0.749458,0.761047
Salinity (PSU) [sea_water_salinity]{surface},0.244966,0.284890,0.279968,0.307382,0.316477,0.349311,0.359727,0.363103,0.376920,0.405419
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.060180,0.074999,0.085954,0.094154,0.102621,0.110656,0.116929,0.124233,0.127074,0.131379
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.066497,0.077852,0.087825,0.099048,0.105548,0.113448,0.118792,0.130213,0.136585,0.139402
Temperature (°C) [sea_water_potential_temperature]{50m},0.547917,0.596186,0.601660,0.663946,0.694349,0.769429,0.736330,0.795769,0.823214,0.885512
Salinity (PSU) [sea_water_salinity]{50m},0.118362,0.135205,0.135692,0.151350,0.155850,0.161600,0.167807,0.174907,0.182604,0.178961
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.048851,0.059150,0.068076,0.075418,0.083521,0.091419,0.099710,0.106574,0.109742,0.111536
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.047923,0.058335,0.066602,0.075360,0.083369,0.090876,0.097832,0.104943,0.109081,0.111378
Temperature (°C) [sea_water_potential_temperature]{100m},0.576457,0.623994,0.649549,0.702516,0.743099,0.787819,0.813015,0.864438,0.888013,0.894158
Salinity (PSU) [sea_water_salinity]{100m},0.102023,0.115310,0.115750,0.127412,0.128554,0.134796,0.137637,0.143326,0.148497,0.145957
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.043719,0.054847,0.063208,0.070801,0.079370,0.086763,0.092729,0.098888,0.102476,0.104478
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.043689,0.055676,0.063981,0.072103,0.080417,0.088351,0.094182,0.101737,0.105198,0.106764
Temperature (°C) [sea_water_potential_temperature]{200m},0.461070,0.421059,0.431819,0.486889,0.499153,0.528324,0.570617,0.598856,0.600156,0.609818
Salinity (PSU) [sea_water_salinity]{200m},0.077106,0.076266,0.075165,0.086218,0.087673,0.091481,0.098950,0.102863,0.104831,0.105442
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.067454,0.042261,0.047373,0.055517,0.060407,0.067364,0.073640,0.079277,0.081978,0.084830
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.061444,0.041544,0.046529,0.054633,0.059707,0.065924,0.072349,0.077354,0.079789,0.082203
Temperature (°C) [sea_water_potential_temperature]{300m},0.412742,0.361504,0.370686,0.415683,0.433321,0.454309,0.491133,0.521786,0.524838,0.528269
Salinity (PSU) [sea_water_salinity]{300m},0.067312,0.064804,0.066325,0.073505,0.075921,0.080022,0.084848,0.088607,0.089088,0.090546
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.061899,0.038855,0.043808,0.051887,0.056586,0.063228,0.069335,0.074483,0.076951,0.079621
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.055916,0.037964,0.042729,0.050641,0.055673,0.061172,0.067696,0.072381,0.074766,0.076991
Temperature (°C) [sea_water_potential_temperature]{500m},0.324668,0.295228,0.291899,0.332152,0.343910,0.354352,0.385265,0.406059,0.410522,0.412680
Salinity (PSU) [sea_water_salinity]{500m},0.055118,0.054313,0.053031,0.058702,0.059047,0.063251,0.065521,0.067821,0.067636,0.069639
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.051615,0.034580,0.039459,0.047075,0.051013,0.056549,0.062266,0.066844,0.069196,0.071520
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.046199,0.034039,0.038739,0.046022,0.050027,0.054777,0.060647,0.064606,0.066877,0.069313

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},51.574699,48.652779,49.230072,51.917744,49.747025,51.051342,53.278969,55.18996,56.691235,49.77364

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.630463,0.637401,0.634498,0.619928,0.615796,0.609600,0.589438,0.629290,0.630663,0.633040
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.746313,0.764536,0.743243,0.726070,0.726195,0.747802,0.657562,0.700885,0.724644,0.731012

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},5.684938,11.702065,17.827656,24.094152,30.799866,37.942993,45.520649,53.338135