In [1]:
import oceanbench

oceanbench.__version__

'0.6.0'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open XIHE forecasts with oceanbench, for a single first day
from datetime import datetime
import xarray
import oceanbench

challenger_dataset: xarray.Dataset = oceanbench.datasets.challenger.xihe([datetime.fromisoformat("2024-01-03")])

challenger_dataset

<xarray.Dataset> Size: 33GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 23,
                         latitude: 2041, longitude: 4320)
Coordinates:
  * depth               (depth) float32 92B 0.494 2.646 5.078 ... 541.1 643.6
  * latitude            (latitude) float32 8kB -80.0 -79.92 ... 89.92 90.0
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * longitude           (longitude) float32 17kB -180.0 -179.9 ... 179.8 179.9
  * first_day_datetime  (first_day_datetime) datetime64[ns] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 256, 512), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 353MB dask.array<chunksize=(1, 1, 256, 512), meta=np.ndarray>
Attributes:
    Conventions:              CF-1.8
    challenger:               xihe
    forecast_reference_time:  2024-01-02
    oceanbench_source_kind:   challenger
    oceanbench_source_name:   xihe

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.075634,0.080980,0.080971,0.079914,0.080431,0.085777,0.084131,0.084201,0.088795,0.088797,5,0.000001
Temperature (°C) [sea_water_potential_temperature]{surface},0.703861,0.675831,0.691939,0.732675,0.706080,0.761422,0.725835,0.781926,0.835995,0.835312,0,0.000000
Salinity (PSU) [sea_water_salinity]{surface},0.548081,0.545550,0.558402,0.550984,0.543984,0.531029,0.524992,0.524562,0.522662,0.508192,0,0.000000
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.131768,0.129752,0.129806,0.129493,0.129807,0.130056,0.128867,0.130927,0.130401,0.130938,0,0.000000
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.135588,0.131538,0.132084,0.133597,0.133414,0.134085,0.133094,0.139506,0.141409,0.143662,0,0.000000
Temperature (°C) [sea_water_potential_temperature]{50m},0.909292,0.911704,0.911827,0.936718,0.937286,1.003502,0.905107,0.970706,1.018879,1.071303,0,0.000000
Salinity (PSU) [sea_water_salinity]{50m},0.249314,0.250818,0.248759,0.249051,0.248936,0.249029,0.248299,0.250498,0.252773,0.255406,0,0.000000
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.122351,0.119549,0.118725,0.116994,0.117219,0.117333,0.116490,0.117378,0.116831,0.116239,0,0.000000
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.123591,0.120036,0.119311,0.118363,0.119167,0.118002,0.116572,0.119084,0.119412,0.118787,0,0.000000
Temperature (°C) [sea_water_potential_temperature]{100m},1.079486,1.103357,1.123773,1.162499,1.143375,1.184299,1.140487,1.149934,1.185770,1.201372,0,0.000000
Salinity (PSU) [sea_water_salinity]{100m},0.182262,0.182072,0.179920,0.181006,0.181538,0.180725,0.179497,0.181591,0.187273,0.186099,0,0.000000
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.119251,0.115538,0.114526,0.112099,0.111603,0.110989,0.108832,0.109242,0.108819,0.108777,0,0.000000
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.124907,0.121115,0.119850,0.117397,0.117864,0.117313,0.114538,0.116125,0.114298,0.113439,0,0.000000
Temperature (°C) [sea_water_potential_temperature]{200m},0.849391,0.814935,0.835603,0.799652,0.827189,0.811882,0.815899,0.845021,0.826124,0.836537,0,0.000000
Salinity (PSU) [sea_water_salinity]{200m},0.138401,0.139896,0.140470,0.136674,0.137497,0.136594,0.134478,0.135267,0.133578,0.135723,0,0.000000
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.117259,0.121554,0.118892,0.114418,0.115225,0.114701,0.114126,0.114271,0.112614,0.111600,0,0.000000
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.123039,0.126586,0.124429,0.120470,0.121997,0.121356,0.119897,0.120640,0.119325,0.118372,0,0.000000
Temperature (°C) [sea_water_potential_temperature]{300m},0.722885,0.683056,0.702811,0.673257,0.699055,0.693713,0.685052,0.710837,0.699083,0.696550,0,0.000000
Salinity (PSU) [sea_water_salinity]{300m},0.112752,0.113801,0.116436,0.111908,0.112795,0.113174,0.109549,0.111977,0.108835,0.112209,0,0.000000
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.113109,0.117700,0.115196,0.110757,0.111585,0.111282,0.110573,0.110462,0.108917,0.107593,0,0.000000
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.117437,0.121000,0.119279,0.115238,0.116904,0.116094,0.115399,0.115480,0.113878,0.112693,0,0.000000
Temperature (°C) [sea_water_potential_temperature]{500m},0.541901,0.520451,0.529103,0.510010,0.532542,0.526046,0.519748,0.535513,0.529672,0.526532,0,0.000000
Salinity (PSU) [sea_water_salinity]{500m},0.084973,0.087317,0.086223,0.084898,0.084541,0.086268,0.083250,0.084640,0.083242,0.084806,0,0.000000
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.102969,0.107368,0.105357,0.101009,0.101640,0.101289,0.100541,0.099882,0.098726,0.097578,0,0.000000
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.107380,0.111300,0.109761,0.105808,0.107079,0.106227,0.105293,0.104945,0.103884,0.102748,0,0.000000

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},51.953659,49.777985,49.677071,52.252659,51.142578,51.755665,53.597099,54.959175,56.352604,50.705196,0,0.0

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.633351,0.642126,0.638937,0.620783,0.617396,0.619838,0.588659,0.646162,0.645077,0.644481,49,0.000005
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.747442,0.769006,0.747100,0.727144,0.727637,0.748500,0.655246,0.700370,0.724112,0.734271,140,0.000007

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Observations,Missing
Temperature (°C) [sea_water_potential_temperature]{surface},0.715815,0.885731,0.842129,0.832939,0.763062,0.804905,0.806707,0.816754,0.880282,0.824610,2999,0
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.576124,0.561942,0.631304,0.627422,0.632310,0.636052,0.763316,0.676234,0.748692,0.722853,3784,0
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.876287,0.898665,0.694308,0.899532,0.912326,0.870721,0.866841,0.853651,0.963476,0.937442,55628,0
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.739464,0.885682,0.653716,0.826598,0.775320,0.740868,0.826699,0.895633,0.791845,0.857187,49367,0
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.525861,0.562393,0.468106,0.515077,0.506305,0.448261,0.492429,0.557960,0.504321,0.518051,48406,0
Salinity (PSU) [sea_water_salinity]{0-5m},0.176715,0.242486,0.272587,0.347272,0.236072,0.186050,0.194220,0.237326,0.212967,0.233037,3334,0
Salinity (PSU) [sea_water_salinity]{5-100m},0.151361,0.203567,0.203784,0.210012,0.226662,0.163431,0.204529,0.202510,0.205496,0.208243,44699,0
Salinity (PSU) [sea_water_salinity]{100-300m},0.125237,0.141816,0.106004,0.131845,0.122816,0.109761,0.127478,0.125615,0.121043,0.149144,40755,0
Salinity (PSU) [sea_water_salinity]{300-600m},0.079633,0.096239,0.077616,0.085668,0.080640,0.070675,0.072509,0.088161,0.077590,0.089585,41131,0
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.054490,0.053684,0.055259,0.058985,0.059574,0.063502,0.064940,0.066697,0.067847,0.069467,296169,0
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.123863,0.117768,0.128806,0.136578,0.130418,0.124008,0.124873,0.126998,0.127564,0.128018,22829,0
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.125289,0.121446,0.123055,0.126415,0.133495,0.143387,0.133634,0.120124,0.115474,0.124740,22829,0

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},11.967179,23.117939,33.45071,43.050167,52.181545,61.133362,69.897507,78.348312

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.035287,0.041929,0.043649,0.045685,0.051858,0.056206,0.059230,0.062162,0.064615,0.065334,5,1.072749e-06
Temperature (°C) [sea_water_potential_temperature]{surface},0.486207,0.509349,0.531354,0.587518,0.591670,0.660346,0.644899,0.714586,0.749458,0.761047,0,0.000000e+00
Salinity (PSU) [sea_water_salinity]{surface},0.244966,0.284890,0.279968,0.307382,0.316477,0.349311,0.359727,0.363103,0.376920,0.405419,0,0.000000e+00
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.060180,0.074999,0.085954,0.094154,0.102621,0.110656,0.116929,0.124233,0.127073,0.131379,5,1.072749e-06
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.066497,0.077852,0.087825,0.099048,0.105548,0.113448,0.118792,0.130213,0.136585,0.139402,5,1.072749e-06
Temperature (°C) [sea_water_potential_temperature]{50m},0.543182,0.590876,0.596192,0.659892,0.689879,0.765098,0.732059,0.791739,0.819158,0.882051,0,0.000000e+00
Salinity (PSU) [sea_water_salinity]{50m},0.114677,0.131250,0.132646,0.147936,0.153235,0.159027,0.164922,0.172429,0.180210,0.176676,0,0.000000e+00
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.048853,0.059162,0.068102,0.075495,0.083600,0.091512,0.099839,0.106720,0.109888,0.111698,4,8.514015e-07
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.047907,0.058337,0.066644,0.075439,0.083468,0.090985,0.097965,0.105088,0.109233,0.111548,4,8.514015e-07
Temperature (°C) [sea_water_potential_temperature]{100m},0.576457,0.623994,0.649549,0.702516,0.743099,0.787819,0.813015,0.864438,0.888013,0.894158,0,0.000000e+00
Salinity (PSU) [sea_water_salinity]{100m},0.102023,0.115310,0.115750,0.127412,0.128554,0.134796,0.137637,0.143326,0.148497,0.145957,0,0.000000e+00
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.043719,0.054847,0.063208,0.070801,0.079370,0.086763,0.092729,0.098888,0.102476,0.104478,28,6.023157e-06
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.043689,0.055676,0.063981,0.072103,0.080417,0.088351,0.094182,0.101737,0.105198,0.106764,28,6.023157e-06
Temperature (°C) [sea_water_potential_temperature]{200m},0.461070,0.421059,0.431819,0.486889,0.499153,0.528323,0.570617,0.598856,0.600155,0.609818,0,0.000000e+00
Salinity (PSU) [sea_water_salinity]{200m},0.077106,0.076266,0.075165,0.086218,0.087673,0.091481,0.098950,0.102863,0.104831,0.105442,0,0.000000e+00
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.067454,0.042261,0.047373,0.055517,0.060407,0.067364,0.073640,0.079277,0.081978,0.084830,13,2.812068e-06
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.061444,0.041544,0.046529,0.054633,0.059707,0.065924,0.072349,0.077354,0.079789,0.082203,13,2.812068e-06
Temperature (°C) [sea_water_potential_temperature]{300m},0.412742,0.361504,0.370686,0.415683,0.433321,0.454309,0.491133,0.521786,0.524838,0.528269,0,0.000000e+00
Salinity (PSU) [sea_water_salinity]{300m},0.067312,0.064804,0.066325,0.073505,0.075921,0.080022,0.084848,0.088607,0.089088,0.090546,0,0.000000e+00
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.061899,0.038855,0.043808,0.051887,0.056586,0.063228,0.069335,0.074483,0.076951,0.079621,11,2.340138e-06
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.055916,0.037964,0.042729,0.050641,0.055673,0.061172,0.067696,0.072381,0.074766,0.076991,11,2.340138e-06
Temperature (°C) [sea_water_potential_temperature]{500m},0.324668,0.295228,0.291899,0.332152,0.343910,0.354352,0.385265,0.406059,0.410521,0.412680,0,0.000000e+00
Salinity (PSU) [sea_water_salinity]{500m},0.055118,0.054313,0.053031,0.058702,0.059047,0.063251,0.065521,0.067821,0.067636,0.069639,0,0.000000e+00
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.051615,0.034580,0.039459,0.047075,0.051013,0.056549,0.062266,0.066844,0.069196,0.071520,12,2.798286e-06
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.046199,0.034039,0.038739,0.046022,0.050027,0.054777,0.060647,0.064606,0.066877,0.069313,12,2.798286e-06

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},51.574692,48.652771,49.230064,51.917736,49.747017,51.051338,53.278965,55.189957,56.691231,49.773636,0,0.0

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10,Missing,Missing fraction
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.630101,0.636860,0.635150,0.619136,0.617279,0.620864,0.589328,0.645941,0.645255,0.645952,18,0.000004
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.745560,0.763846,0.742534,0.725263,0.725176,0.747038,0.656784,0.699977,0.723569,0.730035,8,0.000002

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},5.68499,11.704445,17.829498,24.08997,30.793131,37.936043,45.509998,53.3395