In [1]:
import oceanbench

oceanbench.__version__

'0.0.3'

### Open challenger datasets

> Insert here the code that opens the challenger dataset as `challenger_dataset: xarray.Dataset`

In [2]:
# Open XIHE forecast sample with xarray
from datetime import datetime
import xarray

challenger_dataset: xarray.Dataset = xarray.open_mfdataset(
    [
        "https://minio.dive.edito.eu/project-oceanbench/public/XIHE/20240103.zarr",
    ],
    engine="zarr",
    preprocess=lambda dataset: dataset.rename({"time": "lead_day_index"}).assign({"lead_day_index": range(10)}),
    combine="nested",
    concat_dim="first_day_datetime",
    parallel=True,
).assign(
    {
        "first_day_datetime": [
            datetime.fromisoformat("2024-01-03"),
        ]
    }
)
challenger_dataset

<xarray.Dataset> Size: 33GB
Dimensions:             (first_day_datetime: 1, lead_day_index: 10, depth: 23,
                         latitude: 2041, longitude: 4320)
Coordinates:
  * depth               (depth) float64 184B 0.494 2.646 5.078 ... 541.1 643.6
  * latitude            (latitude) float32 8kB -80.0 -79.92 ... 89.92 90.0
  * longitude           (longitude) float32 17kB -180.0 -179.9 ... 179.8 179.9
  * lead_day_index      (lead_day_index) int64 80B 0 1 2 3 4 5 6 7 8 9
  * first_day_datetime  (first_day_datetime) datetime64[us] 8B 2024-01-03
Data variables:
    so                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    thetao              (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    uo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    vo                  (first_day_datetime, lead_day_index, depth, latitude, longitude) float32 8GB dask.array<chunksize=(1, 1, 1, 75, 4320), meta=np.ndarray>
    zos                 (first_day_datetime, lead_day_index, latitude, longitude) float32 353MB dask.array<chunksize=(1, 1, 75, 4320), meta=np.ndarray>

### Evaluation configuration

In [3]:
region = 'global'

### Evaluation of challenger dataset using OceanBench

#### Root Mean Square Deviation (RMSD) of variables compared to GLORYS reanalysis

In [4]:
oceanbench.metrics.rmsd_of_variables_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.077526,0.080072,0.080199,0.080466,0.081674,0.086342,0.084408,0.086351,0.088344,0.088599
Temperature (°C) [sea_water_potential_temperature]{surface},0.750129,0.704030,0.712400,0.754620,0.734946,0.764045,0.738816,0.792204,0.839555,0.831889
Salinity (PSU) [sea_water_salinity]{surface},0.724029,0.726620,0.752761,0.747579,0.738520,0.716550,0.707049,0.713106,0.717489,0.697855
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.122258,0.120584,0.120452,0.119975,0.120690,0.120648,0.119357,0.121389,0.120524,0.121266
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.124803,0.121870,0.121857,0.122193,0.122388,0.123161,0.121867,0.127186,0.128346,0.129918
Temperature (°C) [sea_water_potential_temperature]{50m},0.860260,0.846190,0.850400,0.871901,0.875340,0.921958,0.838357,0.905367,0.942726,0.985152
Salinity (PSU) [sea_water_salinity]{50m},0.354848,0.366044,0.366986,0.365441,0.369361,0.369703,0.360755,0.363497,0.367428,0.386085
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.113798,0.111173,0.110245,0.108638,0.108755,0.108745,0.107644,0.108281,0.107535,0.107003
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.114415,0.111259,0.110377,0.109342,0.109847,0.108961,0.107503,0.109503,0.109317,0.108909
Temperature (°C) [sea_water_potential_temperature]{100m},0.988410,1.003834,1.017556,1.049408,1.041660,1.068228,1.032001,1.047195,1.076009,1.089305
Salinity (PSU) [sea_water_salinity]{100m},0.228192,0.230820,0.227877,0.228842,0.230666,0.229477,0.229255,0.226696,0.236244,0.244180
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.111023,0.107748,0.106674,0.104508,0.103965,0.103423,0.101360,0.101734,0.101059,0.100911
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.115040,0.111615,0.110385,0.108223,0.108420,0.107899,0.105435,0.106779,0.105049,0.104422
Temperature (°C) [sea_water_potential_temperature]{200m},0.795006,0.766525,0.782082,0.753980,0.775306,0.768295,0.776432,0.794555,0.779413,0.786228
Salinity (PSU) [sea_water_salinity]{200m},0.139200,0.140472,0.141203,0.137877,0.138772,0.138474,0.136469,0.137141,0.135836,0.137728
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.108221,0.112039,0.109499,0.105461,0.106077,0.105693,0.105331,0.105460,0.103863,0.102867
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.112338,0.115639,0.113555,0.109897,0.111160,0.110652,0.109550,0.110121,0.108799,0.107867
Temperature (°C) [sea_water_potential_temperature]{300m},0.679483,0.644976,0.662054,0.636314,0.658491,0.658833,0.652984,0.672225,0.662694,0.659523
Salinity (PSU) [sea_water_salinity]{300m},0.106003,0.106923,0.109105,0.105296,0.105944,0.105917,0.103214,0.105172,0.102627,0.105607
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.104402,0.108459,0.106058,0.102068,0.102708,0.102488,0.102002,0.101904,0.100411,0.099180
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.107519,0.110834,0.109106,0.105367,0.106754,0.106103,0.105590,0.105631,0.104092,0.102979
Temperature (°C) [sea_water_potential_temperature]{500m},0.511531,0.492621,0.500548,0.484324,0.505068,0.500736,0.496052,0.508549,0.504345,0.500196
Salinity (PSU) [sea_water_salinity]{500m},0.079122,0.081392,0.080075,0.079249,0.078534,0.079949,0.077258,0.078783,0.077413,0.079033
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.095019,0.098985,0.096986,0.093077,0.093534,0.093269,0.092720,0.092153,0.091023,0.089954
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.098367,0.102051,0.100436,0.096787,0.097834,0.097131,0.096388,0.096072,0.095016,0.093961

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLORYS reanalysis

In [5]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},55.421625,52.515184,52.908078,55.316263,53.662025,55.157873,56.136312,57.554941,59.304363,53.601464

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLORYS reanalysis

In [6]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.701412,0.699894,0.721076,0.802359,0.791146,0.955004,0.835658,0.807204,0.760776,0.807311
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.622205,0.639501,0.621422,0.605789,0.605955,0.622894,0.545927,0.582386,0.601647,0.610311

#### Root Mean Square Deviation (RMSD) of variables compared to observations

In [7]:
oceanbench.metrics.rmsd_of_variables_compared_to_observations(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Temperature (°C) [sea_water_potential_temperature]{surface},0.912091,0.896297,0.834170,0.787557,0.843612,0.843666,0.820949,0.890920,0.843368,0.848070
Temperature (°C) [sea_water_potential_temperature]{0-5m},0.547942,0.709998,0.604866,0.684896,0.774063,0.746978,0.676345,0.711590,0.704134,0.733349
Temperature (°C) [sea_water_potential_temperature]{5-100m},0.907763,0.741574,0.920998,0.922109,0.920482,0.885047,0.881509,0.946602,0.944090,0.971877
Temperature (°C) [sea_water_potential_temperature]{100-300m},0.892359,0.685149,0.817885,0.787008,0.801481,0.829817,0.898863,0.806719,0.869088,0.899037
Temperature (°C) [sea_water_potential_temperature]{300-600m},0.528239,0.491107,0.504591,0.497139,0.479330,0.489245,0.543636,0.515336,0.545465,0.495406
Salinity (PSU) [sea_water_salinity]{0-5m},0.242720,0.308238,0.358060,0.256369,0.273871,0.194230,0.228481,0.200714,0.249009,0.227408
Salinity (PSU) [sea_water_salinity]{5-100m},0.241143,0.216699,0.237449,0.274694,0.252212,0.260029,0.198367,0.246037,0.285010,0.239886
Salinity (PSU) [sea_water_salinity]{100-300m},0.156201,0.113349,0.130392,0.128398,0.116227,0.127504,0.126552,0.136795,0.151688,0.140861
Salinity (PSU) [sea_water_salinity]{300-600m},0.090098,0.080103,0.083065,0.084107,0.075517,0.074087,0.087004,0.077580,0.095526,0.076413
Sea level anomaly (m) [sea_surface_height_above_geoid]{surface},0.104252,0.103616,0.105569,0.109451,0.114340,0.111420,0.117973,0.117074,0.115979,0.116880
Zonal current (m/s) [eastward_sea_water_velocity]{15m},0.210133,0.221845,0.220276,0.207826,0.211640,0.219627,0.217651,0.226181,0.230789,0.224520
Meridional current (m/s) [northward_sea_water_velocity]{15m},0.194432,0.202879,0.205910,0.203742,0.215113,0.212143,0.211992,0.207329,0.206910,0.203561

#### Deviation of Lagrangian trajectories compared to GLORYS reanalysis

In [8]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glorys_reanalysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},10.862011,21.091564,30.480133,39.052261,47.196159,54.967587,62.488182,69.8396

#### Root Mean Square Deviation (RMSD) of variables compared to GLO12 analysis

In [9]:
oceanbench.metrics.rmsd_of_variables_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Sea surface height (m) [sea_surface_height_above_geoid]{surface},0.035646,0.040797,0.044260,0.048060,0.054623,0.058437,0.064864,0.064078,0.063844,0.066327
Temperature (°C) [sea_water_potential_temperature]{surface},0.494692,0.476892,0.501428,0.556824,0.563662,0.600615,0.603139,0.662653,0.689489,0.689284
Salinity (PSU) [sea_water_salinity]{surface},0.237856,0.271794,0.267722,0.299634,0.313071,0.347139,0.369449,0.359899,0.377052,0.419881
Meridional current (m/s) [northward_sea_water_velocity]{surface},0.053532,0.065535,0.074247,0.079822,0.087899,0.095062,0.101216,0.108719,0.108749,0.112622
Zonal current (m/s) [eastward_sea_water_velocity]{surface},0.056874,0.066038,0.073366,0.080346,0.088152,0.094846,0.100557,0.108254,0.111771,0.113679
Temperature (°C) [sea_water_potential_temperature]{50m},0.511259,0.524996,0.536833,0.578938,0.614841,0.665453,0.626224,0.699329,0.715833,0.760255
Salinity (PSU) [sea_water_salinity]{50m},0.118343,0.124686,0.122716,0.134845,0.136330,0.140942,0.150217,0.155837,0.161301,0.155191
Meridional current (m/s) [northward_sea_water_velocity]{50m},0.041564,0.050083,0.058121,0.063895,0.071285,0.078427,0.085748,0.091063,0.093583,0.095459
Zonal current (m/s) [eastward_sea_water_velocity]{50m},0.039957,0.048672,0.055989,0.063577,0.070528,0.077289,0.083210,0.088992,0.091253,0.093931
Temperature (°C) [sea_water_potential_temperature]{100m},0.504470,0.521456,0.540309,0.581221,0.609750,0.634356,0.657810,0.715079,0.730521,0.729735
Salinity (PSU) [sea_water_salinity]{100m},0.096605,0.105172,0.105990,0.115248,0.114207,0.118640,0.119528,0.127844,0.128882,0.123554
Meridional current (m/s) [northward_sea_water_velocity]{100m},0.036469,0.045771,0.053248,0.059798,0.067331,0.074282,0.079859,0.085244,0.088125,0.089990
Zonal current (m/s) [eastward_sea_water_velocity]{100m},0.036215,0.045894,0.053313,0.060474,0.067783,0.074488,0.079850,0.086184,0.089095,0.090663
Temperature (°C) [sea_water_potential_temperature]{200m},0.396806,0.360007,0.363423,0.411288,0.419308,0.447871,0.485206,0.503095,0.504421,0.512761
Salinity (PSU) [sea_water_salinity]{200m},0.063963,0.062320,0.061310,0.070338,0.071389,0.075105,0.080700,0.083700,0.084846,0.085462
Meridional current (m/s) [northward_sea_water_velocity]{200m},0.059111,0.036060,0.040895,0.048297,0.053274,0.059832,0.065667,0.070911,0.073209,0.075590
Zonal current (m/s) [eastward_sea_water_velocity]{200m},0.054378,0.035573,0.040279,0.047692,0.052706,0.058497,0.064471,0.068998,0.071230,0.073423
Temperature (°C) [sea_water_potential_temperature]{300m},0.357275,0.308984,0.313989,0.354299,0.368388,0.393166,0.419815,0.440368,0.443205,0.447351
Salinity (PSU) [sea_water_salinity]{300m},0.054917,0.052480,0.053676,0.059536,0.061455,0.064634,0.069137,0.071153,0.071910,0.072718
Meridional current (m/s) [northward_sea_water_velocity]{300m},0.054558,0.033419,0.038067,0.045404,0.050108,0.056276,0.061827,0.066680,0.068887,0.071185
Zonal current (m/s) [eastward_sea_water_velocity]{300m},0.049787,0.032750,0.037272,0.044466,0.049363,0.054581,0.060494,0.064758,0.066933,0.068918
Temperature (°C) [sea_water_potential_temperature]{500m},0.275672,0.248958,0.242243,0.279927,0.290068,0.296390,0.322071,0.336041,0.340336,0.341922
Salinity (PSU) [sea_water_salinity]{500m},0.044171,0.043468,0.041945,0.047114,0.047035,0.050116,0.052369,0.053704,0.053449,0.055066
Meridional current (m/s) [northward_sea_water_velocity]{500m},0.045647,0.030106,0.034611,0.041405,0.045334,0.050527,0.055634,0.059785,0.061840,0.063861
Zonal current (m/s) [eastward_sea_water_velocity]{500m},0.041460,0.029662,0.034003,0.040499,0.044533,0.048989,0.054293,0.057987,0.060054,0.062075

#### Root Mean Square Deviation (RMSD) of Mixed Layer Depth (MLD) compared to GLO12 analysis

In [10]:
oceanbench.metrics.rmsd_of_mixed_layer_depth_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Mixed layer depth (m) [ocean_mixed_layer_thickness]{surface},49.172567,44.887249,45.762589,48.253012,44.397361,46.575301,49.061045,50.944273,53.216831,45.629056

#### Root Mean Square Deviation (RMSD) of geostrophic currents compared to GLO12 analysis

In [11]:
oceanbench.metrics.rmsd_of_geostrophic_currents_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 1,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9,Lead day 10
Meridional geostrophic current (m/s) [geostrophic_northward_sea_water_velocity]{surface},0.504908,0.477583,0.471402,0.533255,0.540302,0.645605,0.484456,0.603942,0.550649,0.532992
Zonal geostrophic current (m/s) [geostrophic_eastward_sea_water_velocity]{surface},0.488248,0.501076,0.489238,0.469880,0.477748,0.482627,0.434753,0.478423,0.489149,0.497194

#### Deviation of Lagrangian trajectories compared to GLO12 analysis

In [12]:
oceanbench.metrics.deviation_of_lagrangian_trajectories_compared_to_glo12_analysis(
    challenger_dataset,
    region=region,
)

,Lead day 2,Lead day 3,Lead day 4,Lead day 5,Lead day 6,Lead day 7,Lead day 8,Lead day 9
Lagrangian trajectory deviation (km) []{surface},5.278389,10.86578,16.309793,21.879992,27.938641,34.445763,41.332703,48.51997